### ISSUE TITLE
Benachrictigungen doppelt

### ISSUE THREAD

**Issue by plipK** [Human-Connection/Human-Connection#10]
Aktuell werden bei mir alle Benachrichtigungen doppelt angezeigt. Manchmal wird auch bei einer neuen Benachrichtigung eine alte wieder mit angezeigt.

**Comment by appinteractive** [comment]
Magst du mal ein Screenshot anfügen?

**Comment by plipK** [comment]
Kam in letzter Zeit nicht mehr vor, aber heute wieder:
![image](https://user-images.githubusercontent.com/40367807/42736626-10b0893e-8869-11e8-8a70-1f2e65832cc0.png)

**Comment by appinteractive** [comment]
Ist gelöst und wird in den nächsten Tagen live geschaltet. https://github.com/Human-Connection/API/pull/116
