### ISSUE TITLE
🚀 [Feature] @Username: Unique user identification if identical profile names exist

### ISSUE THREAD

**Issue by sushidave** [Human-Connection/Human-Connection#1069]
## :rocket: Feature

**Is your feature request related to a problem? Please describe.**
If two or more identical profile names exist it can be hard to select the correct user when addressing a user in a post or comment.

**Describe the solution you'd like**
Profile names should be unique. Allow only unique user names on account creation or profile name change.

**Describe alternatives you've considered**
Provide an additional/another identification method to select the correct user.

(Originally posted at https://github.com/Human-Connection/WebApp/issues/342)

**Comment by roschaefer** [comment]
Yes, thank you @sushidave. I think since #1640 this is addressed.

**Comment by sushidave** [comment]
Well done! Thank you @roschaefer & friends.
