### ISSUE TITLE
Create local event

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#114]
**Is your feature request related to a problem? Please describe.**
Some of our users expressed the desire to connect locally. We would like to create local events or meetups which users can find on a map and then attend.

**Describe the solution you'd like**
There should be an option on a contribution form to create event and place it on a map

**Additional context**

@360fun is currenlty in our call and propoes to implement a new specification for decentralized networks and meetups, which is called [ActivyPub](https://activitypub.rocks/news/activitypub-reaches-w3c-recommendation.html). That way, our events could be found in other applications and/or communities and vice versa.

There is a web application called [get2together](https://github.com/GetTogetherComm/GetTogether/) which is ~~already implementing~~ *wants to implement* that specification. Here is the website: https://gettogether.community/

**Comment by 360fun** [comment]
Here also some updates about this speech:
https://socialhub.network/t/federated-events/226
😄 🌴

**Comment by strypey** [comment]
Great to hear that you're in contact with the Communecter folks, and thanks for the invite. I'll be offline for the next month or so, but I'll certainly keep a weather eye on developments. Your team are warmly invited to join the [Open App Ecosystem group on Loomio](https://www.loomio.org/g/exAKrBUp/open-app-ecosystem) (if you haven't already), where I intend to be quite active this year, once I'm back online.

@roschaefer
> we're in a technology transition, so I'll move that feature request to our new repos.

Sweet as. I'll update the link on the [AP watchlist](https://gitlab.com/fediverse/fediverse.gitlab.io/wikis/watchlist-for-activitypub-apps) I maintain for fediverse.party.

**Comment by 360fun** [comment]
Nice we finally have a watchlist! :) I've been looking for it in the past months! ❤️ 🌴

**Comment by mattwr18** [comment]
still relevant... maybe after the next milestone of being ActivityPub compliant?

**Comment by strypey** [comment]
@mattwr18 wrote:
> still relevant... maybe after the next milestone of being ActivityPub compliant?

The discussion about standardizing the federation of event info between
ActivityPub apps has started up again at the new SocialHub forum:
https://socialhub.activitypub.rocks/t/federated-events/305

It would be great to have some of your crew participate there (if you
haven't already ;)

**Comment by strypey** [comment]
Just wanted to give this a nudge.

@mattwr18 wrote:
> maybe after the next milestone of being ActivityPub compliant?

Any updates on this?

FYI I recently tested various event promotion platforms that either have or instead to have AP support:
https://mastodon.nzoss.nz/@strypey/103696683904165823
