### ISSUE TITLE
🐛 [Bug] Improve Header – responsive behavior

### ISSUE THREAD

**Issue by ogerly** [Human-Connection/Human-Connection#1172]
## :bug: Bugreport
the header must be responsive - if i change the size of the display, there is a place where everything is moved. here should already come the MenuIcon. 

![FireShot Capture 005 - Datenschutz - Human Connection - localhost](https://user-images.githubusercontent.com/1324583/62408218-5cb41000-b5c5-11e9-9c6d-ffab0f850d9a.png)

### Steps to reproduce the behavior
1. change the display size manually. 
 

### Expected behavior
change the display size manually. between 
###  959px - 1031px  wide. 
either hamburger menu or responsive

**Comment by alina-beck** [comment]
I disagree (a bit :wink:).

I would prefer a fluid solution where the items (especially the search bar!) scale down to fit next to each other as long as possible. Only when there is no more space to fit all the items side by side should the 🍔-Button be displayed.

That's my two cents. @ogerly would you be happy with this solution, too?

**Comment by appinteractive** [comment]
Like that @alina-beck? https://dist.appinteractive.now.sh/

**Comment by Tirokk** [comment]
@ogerly and @alina-beck is this issue still needed?
Or can we close it?

**Comment by alina-beck** [comment]
Yes, please keep it open! I renamed it to better describe what it is about. I tried to tackle this issue in a PR a while ago but couldn't finish it because the styleguide buttons were not flexible enough... Migrating them now, so we should be able to get this done soon! :smile:

**Comment by alina-beck** [comment]
it's better now!
