### ISSUE TITLE
🚀 [Feature] Make Invite an Registration E-Mails translatable and pretty

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#1186]
## :rocket: Feature

At the moment the e-mails are not very nice and only in english.
Therefore we like to have the ability to make them translatable and pretty.

**Comment by Tirokk** [comment]
Would be wonderful if an admin and later a user can decide when they send an invitation in which language it should be send.
Default could be the language of the admin or user.

**Comment by alina-beck** [comment]
Yes! I agree! But this won't be solved in the current PR, it's a bigger feature. I will open another issue for it.

@Tirokk have you seen how I'm tackling the language problem for the moment? I think you might enjoy it – there's a demo in the PR. ;)
