### ISSUE TITLE
🚀 [Feature] Terms & conditions and data privacy have to be agreed to on the login page

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#1187]
## :rocket: Feature

The user has to agree to terms & conditions and data privacy.
Therefore we need a checkbox and the links to it on the login page which, for the moment, every user has to agree.

**Comment by ogerly** [comment]
same topic https://github.com/Human-Connection/Human-Connection/issues/1081

**Comment by roschaefer** [comment]
Closed in #1334.

The `termsAndConditionsAgreedAt` is missing though! @ogerly
