### ISSUE TITLE
🚀 [Feature] Delete teaser image

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#1188]
## :rocket: Feature

The user should be able to delete the teaser image.

### Design & Layout

May there should be a deletion icon in the right upper corner?

**Comment by mattwr18** [comment]
could you give more info on this @Tirokk ??
do you mean that a user when editing their post should see a delete icon to delete their existing image?
Or that after a user adds an image their should be a way to remove it before creating/saving a Post?
both?

**Comment by Tirokk** [comment]
I meant your first guess @mattwr18 .

- A user should see a delete icon to delete their existing image when editing their post.

Your second guess is fulfilled on production already in my eyes:

- After a user adds an image there is a way to remove it before creating/saving a post.
  - There is a deletion icon in the upper right corner.
