### ISSUE TITLE
🐛 [Bug] Editor placeholder and menu overlap

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#1197]
## :bug: Bugreport
Daniel says:
```
wenn man in das Textfeld reintabbt, sieht das komisch aus ;o
```

<img width="1920" alt="tabbing" src="https://user-images.githubusercontent.com/2110676/62531799-73679a80-b843-11e9-8c77-41d1e051495e.png">

**EDIT:**
@datenbrei:
> When i want to write a comment the placeholder in the comment field gets scrambled, as soon as the comment field gets the focus.

![error-when-commenting](https://user-images.githubusercontent.com/13457963/62927152-402e8980-bdb6-11e9-8bab-9b0f3a0cc835.png)

### Steps to reproduce the behavior
1. Write a post
2. Press tab twice
3. See ugly editor menu

**OR**

1. Read an article
2. Enter the comment field

### Expected behavior
The placeholder could disappear when the cursor is in the editor.

**Comment by alina-beck** [comment]
We decided in the daily yesterday that we would replace the [floating menu](https://tiptap.scrumpy.io/floating-menu) with a [regular menu bar](https://tiptap.scrumpy.io/) – it's better UX and should solve this issue, too.
