### ISSUE TITLE
🐛 [Bug] Editor link button has no effect

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#1198]
## :bug: Bugreport

When you highlight text, double-click and use the link button, the text will not turn into a link. Just the cursor position is moved.

![Screenshot - 2019-08-06T121930 480](https://user-images.githubusercontent.com/2110676/62532348-7747ec80-b844-11e9-800e-0de8297b19cb.png)

### Steps to reproduce the behavior
1. Write a post, add content
2. Highlight text, use editor menu to add a link
3. Nothing happens

### Expected behavior
The text should turn into a link.

**Comment by mattwr18** [comment]
I was unable to replicate this bug @roschaefer 
![2019-08-23-add-link-to-editor](https://user-images.githubusercontent.com/26943915/63593097-7f798900-c5b3-11e9-9661-e2313b1c8a12.gif)
