### ISSUE TITLE
🐛 [Bug] Categories are not localised

### ISSUE THREAD

**Issue by mattwr18** [Human-Connection/Human-Connection#1201]
## :bug: Bugreport

We are currently storing the Categories as English words in the database, which means they are not localised anywhere is the front end.

A user should be able to see the categories in their preferred language.

### Steps to reproduce the behavior
1. Change the language from the `LocaleSwitch` dropdown to `DE`
2.  Click on the filterPosts dropdown in the navbar on the homepage
3. Notice the Categories are still in English 
4. ...
5. Profit

### Additional context

There are several possible solutions:
here are some articles about the subject
https://www.vertabelo.com/blog/technical-articles/data-modeling-for-multiple-languages-how-to-design-a-localization-ready-system
https://www.smashingmagazine.com/2014/06/css-driven-internationalization-in-javascript/

**Comment by Tirokk** [comment]
There are three literal errors in the Categories Thomas Dehn pointed out to us in February:

<img width="1812" alt="Bildschirmfoto 2019-08-09 um 17 10 51" src="https://user-images.githubusercontent.com/25344101/62789929-4973d980-baca-11e9-8951-7ba5379cb73c.png">

Would be nice to have them corrected @mattwr18 . 😘

**Comment by Tirokk** [comment]
And please think about the Admin page for Categories: 🙏🏼

<img width="1812" alt="Bildschirmfoto 2019-08-12 um 13 10 12" src="https://user-images.githubusercontent.com/25344101/62861151-d1dcbf00-bd02-11e9-8a74-083605dfcf08.png">
