### ISSUE TITLE
🚀 [Feature] Expand and mark comment if one jumps to it by URL hashtag

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#1204]
## :rocket: Feature

- If a user gets a notification as an example, because they are mentioned in a comment, and they jump to the comment by clicking on the notification it would be wishful to expand the comment, because otherwise the mention could be in an invisible part of the comment.
- To get the focus of the user to the hashtaged comment it would be wishful to have a short (yellow) blinking at it like it was in the old Alpha.

### Additional context

To implement this functionality the notification by mention the user in a comment have to be implemented. See #1017 .

**Comment by mattwr18** [comment]
here is some info about nice UX when scrolling @Tirokk 
https://css-tricks.com/smooth-scrolling-accessibility/
