### ISSUE TITLE
🚀 [Feature] Create a pinned Post for administration

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#1205]
## :rocket: Feature
```gherkin
Feature: Pin a post
  As an admin
  I want to pin a post so that it always appears at the top
  In order to make sure all network users read it - e.g. notify people about security incidents, maintenance downtimes
```

### Design & Layout
![Screenshot - 2019-10-17T005347 639](https://user-images.githubusercontent.com/2110676/66964914-440daf00-f078-11e9-9e4b-eef149c59abd.png)

### Additional context
**Limitation of one pinned post maximum:**
We have evidence from the legacy alpha, that reaching all users is a feature that gets abused for marketing. On legacy alpha, it was the system notifications - originally intended to be rarely used for exceptional situations like planned downtimes - which got heavily abused for marketing purposes. Pinning a post is great for the admin but gives terrible user experience.

Therefore, we decided to go with a limitation of one pinned post max at the same time. That will leave enough space on the index page for the actual (desired) content and also create an incentive to think before you pin a post (because you have only one).

**Database:**
A `PINNED` relation with a property `pinnedAt` should point from this admin to all its pinned Posts. We could then order by `pinnedAt` on the post and not run into any performance issues as we do with "Most popular" or "Most commented" orderings. The `pinnedAt` would be `null` for all unpinned posts and they would come last.

**Comment by alina-beck** [comment]
hey @mattwr18, thanks for taking over! :)

I thought a bit about this feature design-wise already. In the old alpha the pinned posts were a kind of banner on top, if I remember it correctly? I think this is quite disruptive and takes away a lot of space from the actual content. So, I thought it would be nice to have pinned posts look like regular posts – except for (maybe?) a different background color and a ribbon in a different color saying 'pinned by admin' or something.

This is what I got from just replacing colors in the browser with the styleguide `warning` colors, for example. Definitely not perfect yet (the contrast is terrible), but maybe a start:

<img width="416" alt="Screenshot 2019-10-07 at 14 14 42" src="https://user-images.githubusercontent.com/11694483/66310616-fb822300-e90c-11e9-8faa-97587614ad8d.png">

what do you think?

**Comment by mattwr18** [comment]
I heard somewhere about the idea to make it look like a regular `Post`, not sure if it was you or not, but I like the idea! I like the idea of the ribbon, and might not have thought of that without your helpful message, so thank you... I'll give it a go, and maybe you can help with the contrast when we get it more or less working?

**Comment by alina-beck** [comment]
sure, just let me know when you want my input! :)

**Comment by datenbrei** [comment]
Yeah, we were talking about this about 1,5 month ago. We found, that a pinned post would be easier and better to implement compared with the message we had in the old Alpha.

**Comment by mattwr18** [comment]
@Tirokk maybe we could update this issue after our discussion to ensure that we don't forget about what we agreed to? To my recollection, we agreed that:
1) we will not pin a `Post` on creation because that would limit an admin to pinning only their own `Post`s, this should be done in `UpdatePost`
2) we will remove any previously pinned `Post`, to ensure there is only one at a time to avoid the temptation to have excessive `Post` that are more marketing. 
3) we can always visit :point_up:, if admins are unhappy and can give strong real-world reasons why they need more than one `pinned` post at a time, but then the limit should be kept as low as possible to not abuse this "power" and annoy the users.
4) should there be a way to mark the `pinned` post as read, and unpin it from the `User`'s newsfeed? Is this even easily achievable?
5) should there be any time limit on how long a `Post` should reasonably be pinned? Can we automate this somehow?

Anything else we agreed to or questions? @alina-beck has given some ideas about the UI/styling... any other ideas?

**Comment by alina-beck** [comment]
1. sounds good to me! 🙂 
2. when you say `remove` you mean the `pinned` status/relation will be removed and the post will be treated like a regular post and show up in the timeline further down?
3. yes!
4. I think it would be a cool feature but is probably not easy to implement and shouldn't have priority. I'd say add the pinned post feature first and then tackle this in the future when users start asking for it.
5. I don't think there should be a time limit – some posts might be relevant for a long time, others not so much. Let's rely on our admins to `unpin` posts when they no longer are important?

**Comment by datenbrei** [comment]
Sounds good. Today I had a talk with marketing. I told, that it would be better in general to seed more posts, so that people always know, that we are active and we are engaged. Pinning is bad and we should avaoid it, if ever possible. I was also talking about cell phones, you would also ever see just the one post, if pinned, at first.

**Comment by mattwr18** [comment]
does that mean you are questioning whether we want this feature at all? or that the limit of one is preferred? @datenbrei

**Comment by datenbrei** [comment]
No, everything fine. I just wanted to tell, that marketing is briefed to better not use pinned posts.

**Comment by mattwr18** [comment]
great, :sweat: :rofl:

**Comment by mattwr18** [comment]
thanks for giving feedback @alina-beck... I guess I'm kinda done with the `backend`, so will work on the `frontend`... shame that we won't see much of each other till next week... I guess we can maybe make improvements next week when you get back?

2. yep!
4. I was thinking about it, and don't have any great ideas how to implement it, really
5. that's what I thought

**Comment by alina-beck** [comment]
@mattwr18 sure! you can let me know when you've come up with something – maybe I'll have time to have a look and give some feedback over the weekend. or, if you prefer, we can work on it together next week. 🙂

**Comment by mattwr18** [comment]
hello @alina-beck, @roschaefer providing some styling, but would be great to get your opinion, one thing he left off that you poined out and @Tirokk also brought up would be to use a different color for the ribbon.
@Tirokk also asked for different icons for the `ContentMenu`, but I don't know which ones in the styleguide he prefers, I think maybe they aren't in the styleguide(??)
The functionality is all working as expected, I believe, so we could change any styling at the beginning of the week, and maybe add some more automated tests...

**Comment by mattwr18** [comment]
Although, I like the simplicity of @roschaefer styling, and I think it makes it clear that it's not a normal post(?)
![Screenshot from 2019-10-18 19-06-58](https://user-images.githubusercontent.com/26943915/67113770-9d8def00-f1da-11e9-9f18-f02e6ff21d8a.png)
