### ISSUE TITLE
🚀 [Enhancement] Footer has lacks of design

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#1206]
## :rocket: Enhancement

The new footer has lacks of design.

### Design & Layout

- [x] There should be a visible separation between the footer and the content. See #1500
- [ ] The add Post button should be not above the footer.

<img width="1812" alt="Bildschirmfoto 2019-08-07 um 11 27 51" src="https://user-images.githubusercontent.com/25344101/62612087-159c8680-b907-11e9-8aa1-c64d8401891f.png">

**Comment by vbelolapotkov** [comment]
@Tirokk I've just joined the project and think this issue would be a nice point to start. Could you please assign me to the ticket as I can't do it myself.

**Comment by vbelolapotkov** [comment]
@Tirokk could you please assign me to the ticket. I have already added a shadow to the footer as a solution (see screenshot attached). However, I can't submit a PR without access to the repo.

![Screenshot 2019-09-02 at 19.09.23.png](https://images.zenhubusercontent.com/5d6770ae320b5d31ab4f4743/3fd652f4-461e-46e1-8077-47a9f26cd17e)

**Comment by roschaefer** [comment]
why was this not being closedby #1500 ?
