### ISSUE TITLE
🐛 [Bug] after logging out a new log in is incorrect

### ISSUE THREAD

**Issue by ogerly** [Human-Connection/Human-Connection#1221]
## :bug: Bugreport
after logging out a new log in is incorrect. 

![ezgif com-crop](https://user-images.githubusercontent.com/1324583/62689144-88226a80-b9ca-11e9-9098-996c4852a343.gif)

### Steps to reproduce the behavior
1.  login
2. logout
3.login
4. BUG:  Jumps no to contribution !!
 

### Expected behavior
after logging in again, the user should jump back to the overview page of the contributions.

**Comment by Tirokk** [comment]
For me it looks like the logout does not functioning …
Because if I logout and go then to a former Post page it shows up as I would be still logged in.
