### ISSUE TITLE
💬 [Question] Does a Post have to have a Category?

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#1222]
## :speech_balloon: Question

A user can save a post even if there is no category chosen.
In the Alpha there had to be at least one category selected to save the post.

<img width="1812" alt="Bildschirmfoto 2019-08-08 um 16 20 46" src="https://user-images.githubusercontent.com/25344101/62711225-ef571380-b9f8-11e9-8bee-3bad0108b3bd.png">

**Comment by DennisHack** [comment]
Yes, for public posts, a category has to be chosen. 
If there is no category chosen, the post will be for (future) CONNECTIONS (Like fb friends) only. 
I will provide screens/drafts as soon as Björn is back.

**Comment by Tirokk** [comment]
Would be nice to have a clarification here @DennisHack .
At the moment I don’t understand:
`If there is no category chosen, the post will be for (future) CONNECTIONS (Like fb friends) only.`
