### ISSUE TITLE
🚀 [Feature] I should "follow" myself

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#1229]
## :speech_balloon: Question
If a User only lives in the filter bubble of the users they follow, are their own Posts visible on the main index page in the news feed?

At the moment this is not the case. My own Posts will never appear in the news feed!

But I ( @Tirokk ) as a User would like to see my own Posts in relation to the Posts of the Users I follow.

## :rocket: Feature Description
- [ ] When filtering posts by `Users I follow` a user's own posts should appear in the feed
- [ ] A user should **not** see herself in the lists: `User is following` and `User is followed by`
- [ ] A user should **not** be able to unfollow herself

**Comment by alina-beck** [comment]
Agreed! When I filter posts by _users I follow_ I would expect to see my own, too. But I would **not** like to see myself in the `User is following:` or `User is followed by:` lists on the profile, nor be able to unfollow myself.

**Comment by mattwr18** [comment]
Anyone else have opinions about this? I have no problem with your idea @Tirokk and @alina-beck is in favor of it, so maybe we can just do it?? I can help if someone wants to work on it...

**Comment by Tirokk** [comment]
Yes, we should to this. @mattwr18 @alina-beck 
And it can be a good first issue for open source contributors as well.
