### ISSUE TITLE
🐛 [Bug] Load more resets filter settings

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#1231]
## :bug: Bugreport
Apparently the "Load more" button at the bottom of the index page resets the filter (but not the pagination).

### Steps to reproduce the behavior
1. Visit `/`
2. Select a category, e.g. "Freedom of speech" (1 result)
3. Click on "Load more" (5 results)
4. The new posts don't have a category "Freedom of speech" (bug)

### Expected behavior
I should see the only one post with category "Freedom of speech" and not more.

### Additional context
![2019-08-09-125857_1920x1080_scrot](https://user-images.githubusercontent.com/2110676/62774787-27686000-baa6-11e9-812f-b91114c84ae4.png)

**Comment by Tirokk** [comment]
Didn’t you code the basics of the filter functionality @roschaefer ? 🤣
