### ISSUE TITLE
New sort criterion

### ISSUE THREAD

**Issue by Hardy-Peaceglobal** [Human-Connection/Human-Connection#124]
**Is your feature request related to a problem? Please describe.**
users sometimes wish to see the "hottest" posts: the posts with the most comments (for example in the last 10 days) 

**Describe the solution you'd like**
adding a 4th sort criterion, so that you see the post ranked top down depending on the number of comments (e.g. in the last 10 days)
![sort](https://user-images.githubusercontent.com/44495533/51693008-5f262380-1ffe-11e9-874d-c43fb37f1507.PNG)

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by appinteractive** [comment]
Nice idea, is now possible with the nitro.

**Comment by Mastercuber** [comment]
@appinteractive is this already deployed to the nitro-staging environment? Can't find the dropdown.

**Comment by appinteractive** [comment]
@Mastercuber not implemented but possible. Sorry if it was not clear.

**Comment by roschaefer** [comment]
closing in favour of #265
