### ISSUE TITLE
🐛 [Bug] Admin pages statistics undefined error

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#1242]
## :bug: Bugreport

As Admin I get sometimes a `_vm.statistics is undefined` error.

### Steps to reproduce the behavior
1. login as Admin
2. go over the users menu via clicking on `Admin` to the Admins pages
3. if the error, see image, does not appear right away …
4. … change between the pages
5. then it should appear suddenly

<img width="1812" alt="Bildschirmfoto 2019-08-09 um 18 04 18" src="https://user-images.githubusercontent.com/25344101/62860246-d784d580-bcff-11e9-9576-1d2d1d8986a3.png">

**Comment by roschaefer** [comment]
fixed
