### ISSUE TITLE
🐛 [Bug] Scroll to Posts Comment area doesn't work

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#1245]
## :bug: Bugreport

On a Post page clicking on `Comments`menu item should scroll to the Comments area.

### Steps to reproduce the behavior
1. be on a Post …
2. … click on right menus item `Comments`
3. nothing happens

### Expected behavior

Click on `Comments` menu item should scroll to Comments area!

<img width="1812" alt="Bildschirmfoto 2019-08-12 um 15 02 07" src="https://user-images.githubusercontent.com/25344101/62870064-415da900-bd19-11e9-9bbb-46c8cc1046e2.png">

**Comment by mattwr18** [comment]
I was unable to reproduce this bug @Tirokk, I haven't tried multiple browsers yet... just Firefox, and Chromium... what browser were you using? I tested on production, did you on development?
![2019-08-23-scroll-to-comment](https://user-images.githubusercontent.com/26943915/63593589-8bb21600-c5b4-11e9-9689-09642a8ff8d5.gif)

**Comment by roschaefer** [comment]
duplicate #1273
