### ISSUE TITLE
🐛 [Bug] TypeError: Cannot read property 'offsetTop' of null

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#1273]
## :bug: Bugreport
Clicking around on a post page can lead to this error page:

![2019-08-15-213240_1920x1080_scrot](https://user-images.githubusercontent.com/2110676/63121305-63b72700-bfa4-11e9-884f-ca74bd40f88e.png)

### Steps to reproduce the behavior
1. Click on a post with 0 comments
2. Click on "Comments"
3. Click on "More Info"
4. Click on "Comments" again
5. Boom! :boom: 

![Screenshot - 2019-08-15T213336 977](https://user-images.githubusercontent.com/2110676/63121285-5732ce80-bfa4-11e9-9543-3476fc3c8503.png)

### Expected behavior
Should see the comments

### Version & Environment
```
robert@e480 ~/D/h/Human-Connection> chromium --version
Chromium 76.0.3809.100 Arch Linux
robert@e480 ~/D/h/Human-Connection> cat /proc/version
Linux version 5.2.6-arch1-1-ARCH (builduser@heftig-3961) (gcc version 9.1.0 (GCC)) #1 SMP PREEMPT Sun Aug 4 14:58:49 UTC 2019
```
### Additional context
`git blame` shows me that the bug was introduced in 0a66ad56d. @Tirokk @ogerly never commit any code that has javascript globals like `window` or `document` without testing it for server side rendering. Feel free to remove the whole `watcher` block along with the link to comments - it's not that useful in my opinion.

**Comment by mattwr18** [comment]
I followed the steps to reproduce @roschaefer on `nitro-production` and I was unable to reproduce this in a production environment.... have you been able to?
is this just an issue in `development`?
