### ISSUE TITLE
🚀 [Feature] Update `lastActiveAt` on every JWT token check

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#1305]
## :rocket: Feature
```gherkin
As an administrator
I would like to have a `lastActiveAt` attribute on every user account
In order to know how many users have been active at least once in the last month
```

For every authenticated action, the server has to check if the user is present in the database and is neither `deleted` or `disabled`. On these occasions we could also update a particular `lastActiveAt` attribute for analytical purposes. Having this information we could write cypher statements to check how many percent of the user base have been active in the last month, the last week, etc.

### Design & Layout
As a start, no user interface is required. Administrators have access to the database and could execute cypher statements to get the relevant data.

### Additional context
Here is the relevant code: https://github.com/Human-Connection/Human-Connection/blob/master/backend/src/jwt/decode.js#L15

Probably you just have to change:
```cypher
    MATCH (user:User {id: {id} })
    RETURN user {.id, .slug, .name, .avatar, .email, .role, .disabled, .actorId}
    LIMIT 1
```
to:
```cypher
    MATCH (user:User {id: {id} })
    SET user.lastActiveAt = datetime()
    RETURN user {.id, .slug, .name, .avatar, .email, .role, .disabled, .actorId}
    LIMIT 1
```

**Comment by iylim** [comment]
Can I give this a shot?

**Comment by mattwr18** [comment]
absolutely @iylim, it would be great to have you contributing :smiley:
