### ISSUE TITLE
🐛 [Bug] Scroll to comment via anchor link not working

### ISSUE THREAD

**Issue by alina-beck** [Human-Connection/Human-Connection#1307]
## :bug: Bugreport
Anchor links are not working for comments – at least when navigating there from notifications. (More testing needed to verify if this happens in other situations as well, such as copying and pasting the link in the browser.)

### Steps to reproduce the behavior
1. Open notifications dropdown
2. Click on a notification for a comment
3. --> Land on corresponding post page and see `#commentId-xxx` in the URL but the page is not scrolling down to the comment

### Expected behavior
When visiting a URL including a valid anchor link, the page should scroll down to the HTML element with the corresponding `#id`.

### Version & Environment
 Type: [Desktop]
 - OS: [macOS10.14.5]
 - Browser: [Firefox]
 - Version [68.0.2]
 - Device: [MacbookPro]

### Additional context
Apparently this seems to work sometimes – see [discussion in the notifications-for-comments PR](https://github.com/Human-Connection/Human-Connection/pull/1018#issuecomment-522860269).
Probably related to https://github.com/Human-Connection/Human-Connection/issues/1245

**Comment by mattwr18** [comment]
this is working for me on firefox... I'll test it on other browsers and report here

**Comment by mattwr18** [comment]
just tested this on Chromium(and Chrome) as well, and it is working
tested on Opera, it's working

**Comment by mattwr18** [comment]
one question @alina-beck, when you tested this did you perhaps switch between branches without restarting the webapp server?
When we were developing this feature it wasn't hitting the `scrollBehavior` function and it took us a minute to realize that since it lived in the `nuxt.config.js`, we needed to restart the frontend server.
Or maybe it's a different issue??

**Comment by mattwr18** [comment]
tested this on `nitro-staging` as well, and it works as expected, I believe, but maybe I misunderstood the issue?
![2019-08-21-scroll2comment](https://user-images.githubusercontent.com/26943915/63429752-34c50900-c41b-11e9-82e8-2299c9059956.gif)

**Comment by alina-beck** [comment]
@mattwr18 You're right, I'm sorry! I usually restart when switching branches but... you know... unless this bug magically fixed itself within the past 24 hours it probably was my fault. 😅
