### ISSUE TITLE
🐛 [Bug] Cannot edit post

### ISSUE THREAD

**Issue by alina-beck** [Human-Connection/Human-Connection#1310]
## :bug: Bugreport
When I try to edit one of my posts the app crashes – with `this.author is undefined` (and a bunch of other console warnings on reloading the page).

### Steps to reproduce the behavior
1. Open one of the posts you created
2. In the menu on the top right click on `Edit Post`
3. Get redirected to `/post/edit` and see the app crash

### Expected behavior
The editor should be displayed so I can edit my post.

### Version & Environment
Type: [Desktop]
- OS: [macOS10.14.5]
- Browser: [Firefox]
- Version [68.0.2]
- Device: [MacbookPro]

**Comment by mattwr18** [comment]
I saw this today @alina-beck,
I believe that I got passed this error in https://github.com/Human-Connection/Human-Connection/pull/1268
I can't remember exactly what I did, but I think it was the changes to `webapp/pages/post/edit/_id.vue`
maybe you could check it out, and see what you think?

**Comment by mattwr18** [comment]
closed by https://github.com/Human-Connection/Human-Connection/pull/1268
