### ISSUE TITLE
🐛 [Bug][Production] Only 6 posts of the 27 posts on my profile on the alpha are visible

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#1369]
## :bug: Bugreport

Only 6 posts of the 27 posts on my profile on the alpha are visible.

Alpha:
![Bildschirmfoto 2019-08-23 um 12 15 29#2](https://user-images.githubusercontent.com/25344101/63586285-49cba480-c5a1-11e9-95af-6ffcce6ec890.png)

Nitro-Production:
![Bildschirmfoto 2019-08-23 um 12 16 04#2](https://user-images.githubusercontent.com/25344101/63586308-54863980-c5a1-11e9-9b37-a0b3a95c0538.png)

### Expected behavior

All 27 of my Alpha post should be visible.

**Comment by roschaefer** [comment]
Seems to be fixed now.
