### ISSUE TITLE
Events are filtered by current UI language

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#14]
My browser UI language is English and when I visit https://human-connection.org/veranstaltungen/ I see only events in English. I would like to see **all** events. I can still decide if I want to join or not. Each event is already assigned the right language, so that's enough for me to decide.

**Comment by mimicc83** [comment]
implemented a link to other language events for now.

**Comment by roschaefer** [comment]
To see **all** events would be better because nobody reads text.

The human brain is trained to search for content:
* Lengthy paragraph of text => Not relevant
* Table with Dates and Links => That's what I need

E.g. I missed the "to our german language events" link on the first glimpse.

**Comment by mimicc83** [comment]
I get where you come from but we'll leave as is for now. Let's wait until facelift is done.
