### ISSUE TITLE
🐛 [Bug] 413 Request Entity too large

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#1405]
## :bug: Bugreport

Bigger photos give an error

### Steps to reproduce the behavior
1. Write a new post
2. Add an bigger image (here 1,7 MB)
3. See the Error:
![bild-zu-gross](https://user-images.githubusercontent.com/13457963/63780127-ecf52480-c8e7-11e9-8711-675f57ec1d12.png)

### Expected behavior

It should be clear and statet what the biggest photo is, that can be uploaded, a clear limit.

### Version & Environment
 Type: [Desktop]      
 - OS: [Linux]      
 - Browser: [Firefox] 
 - Version [68.0.1]  
 - Device: [Notebook]

**Comment by mattwr18** [comment]
hey @datenbrei, I was just seeing if I could replicate this, and was unable to.
One thing I notice is that you shouldn't get an error if you upload a photo of 1,7MB as you state, the limit is set to 5,0MB see https://github.com/Human-Connection/Human-Connection/blob/master/webapp/components/TeaserImage/TeaserImage.vue#L45...
This is what I got as an error message when trying to add a file that is 7MB
![Screenshot at 2019-08-27 17:05:07](https://user-images.githubusercontent.com/26943915/63783464-5c214780-c8ed-11e9-8f63-2b546786083d.png)

As you can see, it clearly states why the upload was unsuccessful, and what the size limit is. 

Actually, I was able to replicate this error when I tried to upload an image below the `maxFileSize`, and the error is not from `vue-dropzone`, it appears to be from `nginx`, so maybe we don't have the space in our persistent storage(??)

**Comment by mattwr18** [comment]
it looks like we need to configure nginx, which I've done before, to accept larger file sizes
https://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/

**Comment by datenbrei** [comment]
The bug and related info was committed by @Hardy-Peaceglobal So I just wrote the issue.

**Comment by roschaefer** [comment]
@mattwr18 says it's fixed
