### ISSUE TITLE
🐛 [Bug] I see `notifications.menu.null` in notification list

### ISSUE THREAD

**Issue by alina-beck** [Human-Connection/Human-Connection#1412]
## :bug: Bugreport
On `master` when I open the notification list I see `notifications.menu.null` above each notification.

<img width="516" alt="Screenshot 2019-08-28 at 12 32 48" src="https://user-images.githubusercontent.com/11694483/63852381-14073100-c990-11e9-9258-52b32927921a.png">

### Steps to reproduce the behavior
1. login as `user`
2. open notifications dropdown
3. you'll see...

### Expected behavior
I should see something like `Commented on your post...` or `Mentioned you in a comment...` instead.

<img width="517" alt="Screenshot 2019-08-28 at 12 35 10" src="https://user-images.githubusercontent.com/11694483/63852572-8710a780-c990-11e9-93b4-1acd95ecbb00.png">

### Additional context
works on staging but not on `master`

**Comment by roschaefer** [comment]
fixed
