### ISSUE TITLE
🐛 [Bug] Unpleasant re-arranging of layout - SSR html different from CSR

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#1425]
## :bug: Bugreport

Our dear friend @Hardy-Peaceglobal has reported the following bug report per direct message to me:
> Hi Robert, bitte schaue Dir mal den Effekt an (bei Sekunde 8-9), der passiert, wenn man die Seite über F5 aktualisiert. Sieht etwas komisch aus und sollte, wenn möglich, behoben werden. 

"Hi Robert, please have a look into the effect (around second 8-9) that happens, when you refresh the page. Looks weird and should be fixed if possible.

### Steps to reproduce the behavior
1. Log in to https://nitro-staging.human-connection.org/
2. Refresh the page
3. See the server-side rendered html for ~500ms

![bug](https://user-images.githubusercontent.com/2110676/63961595-6b40fa80-ca91-11e9-9407-9ccb162217d1.gif)

### Expected behavior
It would be great if server-side rendered content and client-side content would match.

### Version & Environment
@Hardy-Peaceglobal  ?

**Comment by alina-beck** [comment]
@roschaefer I found out what's causing this and you will love it: two missing parentheses in the styleguide... 😵 How this is working at all on the client-side is a mystery to me.
