### ISSUE TITLE
🐛 [Bug] Notifications disappear after refreshing the page

### ISSUE THREAD

**Issue by mattwr18** [Human-Connection/Human-Connection#1456]
## :bug: Bugreport

A person can have many unread notifications, which after mentioning someone, or themselves, and refreshing the page, just disappear.

### Steps to reproduce the behavior
1. mention yourself on a post or comment
2. go to the root path
3. refresh the page
4. see your notification menu turn green and let you know you have one notification
5. go to another post and mention yourself again
6. follow steps 2 and 3
7. instead of step 4, see your notification disappear
8. follow steps 1-3 again as many times as you want
9. no more notifications for you

tested in development and `nitro-production`
![Screenshot from 2019-09-03 23-51-59](https://user-images.githubusercontent.com/26943915/64211272-ecd7c480-cea5-11e9-9496-73e90e57c82f.png)
![Screenshot from 2019-09-03 23-52-26](https://user-images.githubusercontent.com/26943915/64211275-f06b4b80-cea5-11e9-9c0f-e9f9b702c644.png)

was unable to get the notifications back even after logging out and back in

**Comment by roschaefer** [comment]
I'm testing this like cracy and I'm not able to reproduce it. Do you wait for a second or two until the notifications arrive from the backend? In the meantime, the notifications show `0` notifications.

Should we add a loading indicator maybe?
