### ISSUE TITLE
🐛 [Design-Bug] Sorting dropdown should be aligned with post cards

### ISSUE THREAD

**Issue by alina-beck** [Human-Connection/Human-Connection#1462]
## :bug: Bugreport
reported by @ulfgebhardt 

misalignment:
![image](https://user-images.githubusercontent.com/11694483/64241613-fe4bbb80-cefb-11e9-9f8a-7e1db60b7b78.png)

### Steps to reproduce the behavior
1. go to index page

### Expected behavior
sorting dropdown should be aligned with post cards

**Comment by ulfgebhardt** [comment]
Thanks @alina-beck for doing the effort to ticket all my reports <3
