### ISSUE TITLE
🚀 [Feature] Search for Users/Persons

### ISSUE THREAD

**Issue by alina-beck** [Human-Connection/Human-Connection#1463]
## :rocket: Feature
reported by @ulfgebhardt 

### Problem
I would like to search for persons. At the moment I only get posts as search results:
![image](https://user-images.githubusercontent.com/11694483/64241893-7914d680-cefc-11e9-9cea-4ae93a16f79b.png)

### Implementation
To the current search functionality we add the following:
- we search our user database for the given keyword – in both the `name` and the `slug`
- we display the found users below the found posts
- we display titles to separate posts from users
- when selecting a `user` result we redirect to this user's profile page

### Design
Something similar to this:
![Screenshot 2019-10-29 at 17.14.14.png](https://images.zenhubusercontent.com/5d1ef2c6fa967b04b3b34866/5818038e-92f1-4457-a9b1-44bc258e4e56)

### Additional context
This is **Step 1** in our search implementation – see #2146.

**Comment by Mogge** [comment]
![grafik](https://user-images.githubusercontent.com/15882241/67643006-4262a780-f912-11e9-91ab-6f1503a86b25.png)


May be we can use the search function of the user profile page to look up for people.

**Comment by alina-beck** [comment]
@Mogge I think we can do better. :wink: I'm afraid that the above solution might not be clear to all users and it could be frustrating to be forced to navigate to a user page before being able to search for users.

@appinteractive suggested a design solution a while ago which I would prefer:
![Screenshot 2019-10-29 at 17.14.14.png](https://images.zenhubusercontent.com/5d1ef2c6fa967b04b3b34866/5818038e-92f1-4457-a9b1-44bc258e4e56)

There is a clear distinction between users and posts in the results and I don't have to specify what I am looking for, so I can do it from anywhere on the page – which I think is a bonus. What do you think?

However, this solution would take us further away from the idea of displaying a dedicated `results page` instead of the `dropdown` which we recently discussed in one of our meetings. @datenbrei and @roschaefer is the results page something we will implement soon or should we go ahead with above (or a similar) solution for user search results?

**Comment by DennisHack** [comment]
Who will program it? Please make an apppointment with me about that to talk in detail and clarify all questions. THANKS

**Comment by alina-beck** [comment]
@DennisHack if you have a solution in mind please share it here! Feel free to update the feature description above (or have a chat with @datenbrei and have him do it? :wink:).

It is not enough if _one_ developer knows what's going on, because:
- they might get sick and someone else has to take over the issue
- we might work on this issue in a pairing session, so we all need to be on the same page
- in order to give proper code reviews the reviewers need to know what the expected outcome is

This issue description + discussion is our point of reference and just in yesterday's meeting we talked about how we need to get better at defining issues before we start working on them!

**Comment by datenbrei** [comment]
I suggested a clarification with Dennis Wed. 6th of Nov. 10 AM. will give you feedback, if agreed by him

**Comment by datenbrei** [comment]
Done

Martin is inviting you to a scheduled Zoom meeting.

Topic: Feature Clarification
Time: Nov 6, 2019 10:00 Amsterdam, Berlin, Rome, Stockholm, Vienna

Join Zoom Meeting
https://zoom.us/j/877887275

Meeting ID: 877 887 275

**Comment by alina-beck** [comment]
I updated the issue description with what we discussed in today's meeting – so I think this is good to go! :)

**Comment by Mogge** [comment]
@alina-beck Hello. Can we talk about this?

**Comment by alina-beck** [comment]
Sure! Ping me on discord? I'm easy to find –  `@Alina`. :smile:

**Comment by mattwr18** [comment]
we discussed this in our standup today, and have some implementation specifics I wanted to pass along @Mogge ... 

We discussed the Search in the daily standup today, and @Roschaefer suggested to just have two queries from the frontend, one for findPosts and a separate one for findUsers.
This would have the benefit of making it easier to group the results in their appropriate section in the dropdown results.

Also, he agreed that we should use `db.index`, as we do with Post... see `neo4j/db_setup.sh`  for an example of how we have it set up currently... he suggested maybe it should contain `name`, `slug`, and `about`... 

@alina-beck , we couldn't hear you this morning, so feel free to add any thoughts here, please.
