### ISSUE TITLE
🚀 [Feature] Image cropping

### ISSUE THREAD

**Issue by alina-beck** [Human-Connection/Human-Connection#1466]
## :rocket: Feature
reported by @ulfgebhardt 

I would like to control how images are cropped when I create a post. At the moment they are cropped automatically – and sometimes the most important part of the image is cut off:

![image](https://user-images.githubusercontent.com/11694483/64242978-6f8c6e00-cefe-11e9-8454-09c1e10ed7f8.png)

**Comment by mattwr18** [comment]
we agreed in our internal meeting today with @alina-beck, @Tirokk, @datenbrei, @DennisHack, @ogerly, and I that for the time being we will allow free ratio cropping by the user with a max-height of say `2000px`, which can be changed, if desired.

This means that at the moment, there will be cases where another user must scroll down to see the additional content of the `Post`. We agreed that an additional issue could be created to autocrop on the `Post` page, and allow the users to click on the image to see the original size.

If you are mentioned above, please check what I've written for accuracy and your understanding of what we agreed on.

**Comment by datenbrei** [comment]
agreed.

**Comment by mattwr18** [comment]
basic image cropping added in https://github.com/Human-Connection/Human-Connection/pull/1666
