### ISSUE TITLE
🚀 [Feature] Report with reason

### ISSUE THREAD

**Issue by alina-beck** [Human-Connection/Human-Connection#1469]
## :rocket: Feature
reported by @ulfgebhardt 

I want to give a reason when I report a user. There is no way to do this now:
![image](https://user-images.githubusercontent.com/11694483/64248346-c26b2300-cf08-11e9-8f17-09396daf0bde.png)

### Additional context
This could also help moderators to pinpoint the problem and decide what to do about the reported user.

**Comment by ogerly** [comment]
a list of reasons we provide or should the user be able to enter it in a text field?

**Comment by alina-beck** [comment]
very good question! I think it would probably be easier for moderators if we had a list with the 5 (or so) most common reasons but as a user I would also appreciate the possibility to add a comment. what do you think @ulfgebhardt?

**Comment by ulfgebhardt** [comment]
![image](https://user-images.githubusercontent.com/1238238/64537737-b1148300-d31b-11e9-8e6c-ac940d0fe717.png)
![2](https://cdn5.f-cdn.com/files/download/65810983/webp-net-g.gif)

Most tools provide options + comment

**Comment by alina-beck** [comment]
closing this in favor of #1707 which is more specific
