### ISSUE TITLE
💬 [Question] Should the 'follow user' option be placed with the other user interactions?

### ISSUE THREAD

**Issue by alina-beck** [Human-Connection/Human-Connection#1470]
:speech_balloon: Question
reported by @ulfgebhardt 

At the moment the (un)follow button is placed outside the menu where other user interactions take place (blocking, reporting, disabling). Do we want to keep it that way or could it be better to group all interactions together?

@ulfgebhardt said he was missing the (un)follow option in the dropdown:
![image](https://user-images.githubusercontent.com/11694483/64248596-77054480-cf09-11e9-997f-391bcdae09cc.png)

**Comment by ogerly** [comment]
i would leave the button for the follow and no longer follow where it is now. maximum one additional item in the menu

**Comment by alina-beck** [comment]
I agree with @ogerly. Any other opinions @datenbrei @DennisHack @Human-Connection/hc-dev-team? Otherwise feel free to close this issue!
