### ISSUE TITLE
Impose a temporary write lockout on a user for misbehaviour

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#15]
**Is your feature request related to a problem? Please describe.**
As a moderator, I would like to impose write lockouts on users who conduct misbehavior. If e.g. a user violates our code of conduct, but the misconduct is not bad enough to ban, I could prevent the user from creating posts or commenting on posts. This write lockout could be temporarily. In that case, the timeout could also be accumulative, ie. if a user violates the code of conduct many times, the timeout increases for every violation. 

**Describe the solution you'd like**
As a moderator I want to see a button on the user profile to impose a write lockout. It could be labeled "hold your breath" or sth. similar. After a confirmation the user cannot write posts or comments any more.

**Describe alternatives you've considered**
* We could restrict the power to admins, not moderators.
* We could put the button on the admin interface, but moderators have currently no access to it
* Different strategies as described above

**Additional context**
![screenshot 4](https://user-images.githubusercontent.com/2110676/45587908-8bbd8680-b90c-11e8-8cd5-b2a2e4584cd2.png)

**Comment by realB12** [comment]
@roschaefer I am sure it will dramatically improve your "not invented here" workstyle and behavior :-). Locking out all critics and different viewpoints will make you king of the silo, but will not help the project!
Better then locking users out, is 
a) to define specific Rules (with an ID/numbers) everybody can refer to
b) to mention those rules in the public, BEFORE you are blaming others for violating rules and
c) finally have the guts and time to discuss and justify your rulings in public. 
Otherwise, you just work against HCs primary goals to serve your own, selfish dominating, intransparent and non-discussable "I am always right because I am King" behavior!
Training young and inexperienced folks is a good thing. But when you just do it to grow people to dominate, but you are not able to communicate and accept grown-ups and to handle discussions beyond your limited viewpoint - you should be the last authorized person working on spam/trolling issues. 
I mean, who are you? Who is supervising you? And why do you think you should be authorized to kick others out? Kicking others out, should never be allowed to a single person.  Such authority needs to be earned by trust and not by code nor money!

**Comment by Lulalaby** [comment]
Opps 😄

**Comment by realB12** [comment]
@Lulalaby 
I am not aware, that my post has been against any rule and contains nothing, I would not have written evidence.  Your deletion here, just adds to my delete quote, that you guys are not ready to moderate a grown-up discussion (yet).
Deleting posts here without a reason is against OS principles and rules (maybe you should read them first before you are kicking out people!).
Running your stuff on GitHub under an OS flag brings rules and obligations beyond your own legal context and authority and has to be followed. 
Deleting my comment is strictly against those rules. I have copied all the context and I will escalate it to the OS community should you not reconsider!
You may continue with your kindergarden here - but I suggest to ask Dennis Hack first - about what it means having me against you on other channels fighting for my and OS community rights.
I really do not want to harm this project. But if you are starting again to behave against OS principles, you must not use the OS platform either and you will have to build up your own silo where you can do whatever you want! This is OS. Here YOU have to follow rules!

**Comment by realB12** [comment]
@All
This feature is about building a non-open system where a few - non community chosen - people are getting 100% control and the power - but not the "rights" - to delete whatever they want and to kick everyone they do not like. 
Just providing this features without having commonly agreed rules and enforcement process approved is against HC's core principles and against OS standards!
So, I think, there is more than one good reason to have a good and widespread discussion with the community first about those rules and processes before giving juniors the licence to kill :-)

**Comment by Lulalaby** [comment]
Don't tell me what i have to do :)
You are attacking @roschaefer. That's the reason why i deleted it.

**Comment by mimicc83** [comment]
this has nothing to do with power, it's about keeping laws, stop mobbing and diffamation and it's a temporary system until we implemented some smarter way to fight idiots. 

Example: someone has your address and is threat to your life telling you to come around and punch you in the face. This needs to be handled legally and we surely want to remove such users from our platform to protect everyone else. 

This is not a discussion on the feature. Please create an issue to discuss this feature in the future.

**Comment by realB12** [comment]
@mimicc83 I 100% agree with your point. On the other hand, your point is not the only aspect and there is no reason, why not handling both at the same time. Big power requires big responsibility. 
However, there is no point to delete my comments here. At least my last one was explicity addressed to @all and is not targeting anyone.. 
It is ok to move them to another channel, but it is not ok to delete them on GitHub. 
It is one thing to kick me out of the Alpha, but it is a different thing to kick me out on GitHub. Maybe you should discuss the consequences for going to GitHub mediation with Dennis Hack first, as this might have consequences for all the project and your further work as an OS developer.

**Comment by Lulalaby** [comment]
How you always refer borrowing to a higher placed person. 
can't you arrange anything yourself?

we are currently working with the discord community to create a guideline or set of rules that will apply to both dicsord and github.
As long as this is not done, I will act at my own discretion.

**Comment by realB12** [comment]
@Lulalaby Read my post you have deleted and give me the part that is attacking somebody specific. Thanks. And so I post again what you have deleted and I will post it all over the place till anybody gives a clear indication which OS or GitHub rule has been violated!
@ALL
This feature is about building a non-open system where a few - non community chosen - people are getting 100% control and the power - but not the "rights" - to delete whatever they want and to kick everyone they do not like.
Just providing this features without having commonly agreed rules and enforcement process approved is against HC's core principles and against OS standards!
So, I think, there is more than one good reason to have a good and widespread discussion with the community first about those rules and processes before giving juniors the licence to kill :-)

**Comment by Lulalaby** [comment]
I could play the game now and delete your post again and again, but I don't do that because I don't want to go down to your level.
Do what you want, but don't be surprised if everyone ignores you someday.
You're definitely pissing me off.

**Comment by realB12** [comment]
Just checked with my legal guy: 
As long as you do not have your own rules - which only get valid when confirmed by the user - national law applies. According to the national law you have the right to delete content that is against the law. 
However, deletion of content can and must always be legally questionable. So you have to keep it safe for at least 30 days and - on intervention - you will have to keep ALL THE CONTEXT till the dispute is settled. 
During settlement, YOU have to give evidence that your destruction of content and/or another person's reputation (public notification that someone's content has been deleted is). If you cannot provide such evidence you will lose the (expensive) case and eventually will have to pay a fine and compensation for damaged reputation.
Please discuss this with Dennis Hack (your Datenschutzbeauftrager is not enough).

**Comment by Lulalaby** [comment]
Seriously, I'm lying here on the floor laughing.

**Comment by mimicc83** [comment]
if you have personal difficulties with dennis please talk to him directly, this channel is for discussing development concerns. Last warning.

**Comment by datenbrei** [comment]
This should be possible for moderators, not admins. Later we possibly could have 2-3 levels of moderation. But it will stay an moderation task.

**Comment by mattwr18** [comment]
I guess this is still relevant? has the moderation team brought up any real cases where they would have liked to have been able to impose a temporary writing ban @datenbrei ??
