### ISSUE TITLE
🐛 [Bug] Comment expanded view has to much space underneath

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#1597]
## :bug: Bugreport

Comment expanded view has to much space underneath.

<img width="1812" alt="Bildschirmfoto 2019-09-05 um 08 20 47" src="https://user-images.githubusercontent.com/25344101/64967690-44f8c880-d8a1-11e9-9256-981e410908f5.png">

### Steps to reproduce the behavior
1. go on a long comment
2. expand the view by clicking `show more`
3. see the problem

### Expected behavior

No big space under the comments content.

**Comment by MarcoBomfim** [comment]
@Tirokk is this still happening? I couldn't replicate on a recently cloned repo.

**Comment by Tirokk** [comment]
Funny thing is @MarcoBomfim I put it an hour ago in an own tab in my browser to check later if this is still happening and you are right it's not happening anymore. So I close this …
Thanks for pointing it out !!!
