### ISSUE TITLE
🚀 [Feature] Automatic loading on user profile

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#1598]
## :rocket: Feature

Automatic loading on user profile tabs.

<img width="1812" alt="Bildschirmfoto 2019-09-09 um 09 29 41" src="https://user-images.githubusercontent.com/25344101/64968182-044d7f00-d8a2-11e9-8eb3-4627a4217e22.png">
<img width="1812" alt="Bildschirmfoto 2019-09-09 um 09 30 26" src="https://user-images.githubusercontent.com/25344101/64968196-08799c80-d8a2-11e9-91e3-0bfda226610e.png">
<img width="1812" alt="Bildschirmfoto 2019-09-09 um 09 30 36" src="https://user-images.githubusercontent.com/25344101/64968204-0d3e5080-d8a2-11e9-9919-0a3b32b5a8a2.png">

**Comment by mattwr18** [comment]
I think this might not be such an easy issue @Tirokk since the load more on scroll works fine, but only if you follow a deep link to a profile, or refresh the page, it does not work if you visit the profile by clicking on a user's name to visit a profile.

**Comment by Tirokk** [comment]
This issue is fixed in my eyes !
Works now in production …
