### ISSUE TITLE
🚀 [Feature] Refactor Moderator spec to use apollo-server-testing

### ISSUE THREAD

**Issue by aonomike** [Human-Connection/Human-Connection#1612]
## :rocket: Feature

Refactor tests in file `src/schema/resolvers/moderation.spec.js` to use appolo server testing library which is currently being used for all the tests

### Additional context

The tests in the file `src/schema/resolvers/moderation.spec.js` are currently failing and this refactor will make them pass

**Comment by roschaefer** [comment]
I think that got is solved @aonomike
