### ISSUE TITLE
🐛 [Bug] Re-send registration mail if user has not yet signed up

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#1616]
## :bug: Bugreport

If an admin has invited a user but this user has not registered yet or the email was lost - it won't be possible to resend the registration mail. The error shown looks like this:

![Screenshot - 2019-09-17T163729 658](https://user-images.githubusercontent.com/2110676/65051406-5c9b8400-d969-11e9-861f-b0e5d56c65df.png)

### Steps to reproduce the behavior
1. Log in as `admin@example.org` at nitro-staging.human-connection.org
2. Visit https://nitro-staging.human-connection.org/admin/invite
3. Invite `test@example.org`
4. Refresh the page
5. Try to invite the same email again
6. See the error page above

### Expected behavior
For not-registered users it would be great to resend the registration email.

**Comment by Tirokk** [comment]
Great idea and solution @roschaefer !!!
It even reminds the people to register.
