### ISSUE TITLE
🚀 [Feature] Refactor our kubernetes configuration into a helm chart

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#1629]
## :rocket: Feature

[Helm](https://helm.sh/) is a package manager for kubernetes. Refactoring our [current instructions](https://docs.human-connection.org/human-connection/deployment) would make it a lot easier to deploy our application:

* One click install
* Conditional deployment of mailserver
* Easy switch to maintenance mode
* Reliable rollouts by incrementing one docker image tag

**Comment by mattwr18** [comment]
There is a `[WIP]` PR for this already
