### ISSUE TITLE
🐛 [Bug] Create account has no info about email, no localisation, no HC logo

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#1631]
## :bug: Bugreport

Create account has no info about email, no localisation, no HC logo.

### Steps to reproduce the behavior
1. if an invited emails owner clicks on the inviting link
2. they go to the `Create user account` page
3. and they have no information about the email used 
4. ... no translation by localisation menu
5. … no Human-Connection logo

![Bildschirmfoto 2019-09-17 um 14 13 01](https://user-images.githubusercontent.com/25344101/65143711-f4ef4280-da15-11e9-80ef-3739fb3511bc.png)

### Expected behavior

The user should have these informations.

**Comment by mattwr18** [comment]
sorry @Tirokk , the logo and `LocaleSwitch` have disappeared for me as well :open_mouth:
