### ISSUE TITLE
🐛 [Bug] Can no users used all hashtags be correct?

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#1632]
## :bug: Bugreport

Can no users used all hashtags be correct?

![Bildschirmfoto 2019-09-17 um 13 17 43](https://user-images.githubusercontent.com/25344101/65144850-7d6ee280-da18-11e9-8d03-6d5ba112d37f.png)

After writing a #Natur post …

![After writing a #Natur post](https://user-images.githubusercontent.com/25344101/65144867-8790e100-da18-11e9-9e3c-0aaf8abfa112.png)

The changes are correctly !!!

### Steps to reproduce the behavior
1. login as admin
2. go to the menu and chose `Admin`
3. chose the `Hashtag` menu item

### Expected behavior

Show the correct numbers.

**Comment by roschaefer** [comment]
Uh oh, if you click on one of them, there are no results. I think the database import failed on the hashtags.

**Comment by roschaefer** [comment]
Can sb. explain this:

```
neo4j> MATCH (p)-[r:TAGGED]->(t) return p,t,r limit 10;
+---------------------------------------------------------------------------------------+
| p  | t                                                                    | r         |
+---------------------------------------------------------------------------------------+
| () | (:Tag {deleted: FALSE, disabled: FALSE, id: "Test"})                 | [:TAGGED] |
| () | (:Tag {deleted: FALSE, disabled: FALSE, id: "psychologieerziehung"}) | [:TAGGED] |
| () | (:Tag {deleted: FALSE, disabled: FALSE, id: "happytesting"})         | [:TAGGED] |
| () | (:Tag {deleted: FALSE, disabled: FALSE, id: "Gedicht"})              | [:TAGGED] |
| () | (:Tag {deleted: FALSE, disabled: FALSE, id: "Frühling"})             | [:TAGGED] |
| () | (:Tag {deleted: FALSE, disabled: FALSE, id: "Sonne"})                | [:TAGGED] |
| () | (:Tag {deleted: FALSE, disabled: FALSE, id: "Wald"})                 | [:TAGGED] |
| () | (:Tag {deleted: FALSE, disabled: FALSE, id: "Sonnenstrahlen"})       | [:TAGGED] |
| () | (:Tag {deleted: FALSE, disabled: FALSE, id: "Natur"})                | [:TAGGED] |
| () | (:Tag {deleted: FALSE, disabled: FALSE, id: "alpha"})                | [:TAGGED] |
+---------------------------------------------------------------------------------------+

10 rows available after 45 ms, consumed after another 0 ms
```

Why is `p` always `()`?? What the heck?

**Comment by mattwr18** [comment]
this issue is being closed because it was solved by a import script that correctly set up the relationship between `Tags` and their `Post`
