### ISSUE TITLE
🐛 [Bug] Admin statistics entries are missing

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#1633]
## :bug: Bugreport

Admin statistics entries are missing. And invites seems wrong.

### Steps to reproduce the behavior
1. login in as an admin
2. go to the menus `Admin` item
3. there you see the problem

![Bildschirmfoto 2019-09-18 um 12 40 06](https://user-images.githubusercontent.com/25344101/65145803-ae501700-da1a-11e9-996f-d962570288c2.png)

And invites can not be zero, because I just before invited somebody. And we know there should be already invites imported.

<img width="1876" alt="Bildschirmfoto 2019-09-18 um 18 00 58" src="https://user-images.githubusercontent.com/25344101/65165242-b0c46800-da3e-11e9-85ce-6a6455b09ad1.png">

### Expected behavior

The missing statistics entries should be visible.

**Comment by roschaefer** [comment]
Is this really a bug? It's just suboptimal layouting. Seven items placed in three columns.

**Comment by mattwr18** [comment]
There were no `invites` imported @Tirokk 
It is weird that when you invite someone it does not update the counter though.
Also, when you say go to this page and `there you see the problem`, I'm not sure what you mean by that...
Is @roschaefer correct that you are pointing out silly layout, or are there some statistics that are not being displayed, that you would like to be?

**Comment by roschaefer** [comment]
I checked the implementation and the `invites` are counting the `InvitationCodes` created by users.This is a feature which is not implemented. If you want, you can add `EmailAdress` to the stats. Total of email addresses subtracted by total of users should be the number of pending registrations.

**Comment by datenbrei** [comment]
I could not fugure out, what the behaviour shall be, according to the issue. Currently an open invitation does not appear. As soon, as the user has registered, it appears as one more invitation.
