### ISSUE TITLE
🐛 [Bug] Put the imprint page directly on the page again

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#1634]
## :bug: Bugreport

Put the imprint page directly on the page again.
It was removed here #1615 …

### Steps to reproduce the behavior
1. login
2. click on the imprint link on the footer
3. you are directed to an external page

### Expected behavior

You should be directed to an internal page.

**Comment by datenbrei** [comment]
Closed, see https://github.com/Human-Connection/Human-Connection/pull/1883
