### ISSUE TITLE
🐛 [Bug] Notifications do just update with page reload

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#1637]
## :bug: Bugreport

The notifiactions are not counting down when viewing the related content. Just after a page reload.

### Steps to reproduce the behavior
1. get a notification
2. click on the icon and choose some content
3. The notifications do not change or count down or disappear.
4. Reload the page and everythinig is fine
5. Profit

### Expected behavior

The notification counter should decrease when viewing the related content.

### Version & Environment
 Type: [Desktop]      
 - OS: [Linux]      
 - Browser: [Firefox] 
 - Version [69.0]  
 - Device: [Notebook]  

### Additional context

Maybe #1332 and #1456

**Comment by roschaefer** [comment]
@datenbrei can you have a look if notifications get dimmed out when you click on them? The difference is subtle. I believe this works but maybe the visual change is just not really noticeable.
