### ISSUE TITLE
🐛 [Bug] Prevention from DDOS-Attacks and Abuse

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#1638]
## :rocket: Feature

The network needs some mechanism to avoid hacking attempts by blocking the offending ip address. One solution could be an integration with failtoban or similar technologies. 

Here some links with further information, which may help or not:

- https://medium.com/@animirr/brute-force-protection-node-js-examples-cd58e8bd9b8d
- https://www.fail2ban.org/wiki/index.php/Main_Page
- https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/security/login-rate-limit.md
- https://github.com/animir/node-rate-limiter-flexible

### Design & Layout

n/a - just backend

### Additional context

Failed password attempts should possibly result in a blocking on ip level, so that the higher level technology is not involved and does not come under load. The same for DDOS attacks: If some ip tries to call an url for too many times a second or minute, it should be blocked.

Counting the failed attempts and locking the user is no solution, because anybody could lock a user then just to worry him.

**Comment by roschaefer** [comment]
What about DDOS protection by cloudflare? It's not an option?
