### ISSUE TITLE
🐛 [Bug] Mail Layout German/English not working in Webmail

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#1656]
## :bug: Bugreport

The switch between German and English language in Mails sent from the system does not work in most webmailers, **it is not even clickable**. At least it is displayed, but since webmailers normally just display a subset of HTML to protect people from beeing spyed out, it seems, that our functionality is affected.

Example from Mailbox.org webmail:
![deutsch-englisch](https://user-images.githubusercontent.com/13457963/65301489-11a38b80-db78-11e9-9c91-508fcdbda501.png)
Example from Rainloop webmail:
![deutsch-englisch2](https://user-images.githubusercontent.com/13457963/65301763-0b61df00-db79-11e9-889f-eeac1ed02177.png)
Example from gmx.de:
![deutsch-englisch3](https://user-images.githubusercontent.com/13457963/65301872-6f84a300-db79-11e9-98f9-9b1163fd385c.png)

### Steps to reproduce the behavior
1. Register for a new user or try to reset your password
2. Open your webmail
3. See, that you can't ue the German / english switch

### Expected behavior

The switch should work in all systems handling HTML at all. So maybe it has to be written in a simpler kind?

### Version & Environment
 Type: [Desktop]      
 - OS: [Linux]      
 - Browser: [Firefox] 
 - Version [69]  
 - Device: [Notebook]

**Comment by appinteractive** [comment]
Interactive mail is not possible and will break in mail clients for sure! Decide which language to send, by using the users Lang setting!

**Comment by roschaefer** [comment]
Yes, I agree with @appinteractive. When you open a mail with Thunderbird you can choose to view the mail as "Original HTML" (language chooser works) "Simple HTML" (language chooser does not work) and "Plain Text" (no html but both languages in one piece of text).

Can this be closed? It's German as first language, no?

**Comment by appinteractive** [comment]
Before it gets closed, it should be fixed first 😆

**Comment by alina-beck** [comment]
A radio button toggle actually works in all major email clients except outlook nowadays – I just didn't consider the fact that many _webmail_ clients refuse to support basic HTML and CSS even though they could...

I think it would be nice to keep the toggle where it works and display English below German for other clients. @datenbrei did both language versions get displayed in the examples you posted above? In theory they should but it would be good to get this confirmed. ;)
