### ISSUE TITLE
🐛 [Bug] Page Reload disables Filter

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#1662]
## :bug: Bugreport

If I reload my dashboard the filter is reset.
![filter-gone](https://user-images.githubusercontent.com/13457963/65338721-19405000-dbcb-11e9-9c7e-2511eb5824d0.png)

### Steps to reproduce the behavior
1. Set a filter
2. press F5 in browser

### Expected behavior

The filter shuld be persistent

### Version & Environment
 Type: [Desktop]      
 - OS: [Linux]      
 - Browser: [Firefox] 
 - Version [69]  
 - Device: [Notebook]

**Comment by mattwr18** [comment]
We still want to have persistent filters
