### ISSUE TITLE
🐛 [Bug] - all editor plugins should be disabled in the comment function

### ISSUE THREAD

**Issue by ogerly** [Human-Connection/Human-Connection#1664]
## :bug: Bugreport
the comment function has to be edited urgently. 
if you edit the editor with H3 and H4 the text ... 
the comment disappears as text ... 
all editor plugins should be disabled in the comment function .. links pure .. and only text. 

### Steps to reproduce the behavior
1. go to a contribution
2. write a mail
3. use H3 or H4 or the list function
4. after saving the text disappears

### Expected behavior
only text should be allowed in the answer ... and left should only be left.

**Comment by mattwr18** [comment]
hey @ogerly this doesn't seem to happen on staging... see 
![Screenshot from 2019-09-20 09-56-12](https://user-images.githubusercontent.com/26943915/65370624-53f1c900-dc5b-11e9-96b1-57bf7e5ac6fe.png)

**Comment by ogerly** [comment]
online ... nitro production .. is comment empty after save

**Comment by datenbrei** [comment]
As ar as I remember we were talking about this. THere was also a discussion, why w need an editor component (or not). @roschaefer @alina-beck , what is your opinion?

In general I have no problems with comments having more features, should I talk with Dennis?

**Comment by alina-beck** [comment]
I think it's nice to have formatting options in the comments and to be able to _@mention_ people and add _#hashtags_! 😍 

What I meant when I mentioned the editor the other day is that it's not very intuitive to use the `tiptap` editor not just for _editing_ but also for _displaying_ posts and comments. (And working with `tiptap` always ends up being messy...) But that's an implementation detail we can discuss and possibly improve in the future.

Formatting works for me – I just tested it on staging! So I would be ok with closing this issue. What about the others? @ogerly are you still having the problem you reported above?

**Comment by datenbrei** [comment]
Closing also ok for me.

**Comment by mattwr18** [comment]
Just as a clarification @alina-beck, we don't have the ability to use #hashtags on comments.
This was a decision made because at the moment when you click on a hashtag it takes you to the root path and searches for all _Posts_ with #hashtags...
We can always revisit that, but just to clarify

**Comment by Tirokk** [comment]
This can be closed in my eyes.
And I take this action.
