### ISSUE TITLE
🚀 [Feature] Direct answer on Comment

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#1680]
## :rocket: Feature

Like in the old Alpha there should be a button to answer on another comment directly, so that the mention of the old comments slug is immediately pasted into the editor.

### Design & Layout

Result with already existing mention after pressing **answer**:
![mention](https://user-images.githubusercontent.com/13457963/65423199-bf2cce00-de08-11e9-990d-4c41820a3fb6.png)

### Additional context

This was already implemented in the old Alpha system

**Comment by Tirokk** [comment]
Here is meant: There was a button on each comment in the old Alpha. When you clicked on it the author of the comment was mentioned in the editor field for writing a new comment.

So this here seems different to me as issue  #2332 .
There I thing @jkmssoft means a kind of tree structure as in Facebook, for example. Where you can write a direct answer to a comment underneath. @sushidave
