### ISSUE TITLE
Make it clearer how to get started from the organisation page

### ISSUE THREAD

**Issue by tansaku** [Human-Connection/Human-Connection#169]
If one starts at the organisation page it's not immediately clear how to get involved with coding:

<img width="1168" alt="Screenshot 2019-03-11 14 31 39" src="https://user-images.githubusercontent.com/30216/54131517-68cae580-440a-11e9-91b2-cd4e08e248d1.png">

Perhaps the description for the main Human Connection repo could say "start here"?  Or maybe we're happy to have people poke around

<img width="1288" alt="Screenshot 2019-03-11 14 33 30" src="https://user-images.githubusercontent.com/30216/54131652-af204480-440a-11e9-9afe-73c647c15e35.png">

would be great if we could somehow guide folks into the CONTRIBUTING.md so that there's a clear path of how to get started ... i.e. not rely on them having to reach out in discord etc.

**Comment by tansaku** [comment]
should the link associated with the project at the highest level perhaps go to the documentation, which would then hyperlink to the chat?  or can we have more than one link?

<img width="1048" alt="Screenshot 2019-03-11 14 52 35" src="https://user-images.githubusercontent.com/30216/54133116-67e78300-440d-11e9-93f4-d844295ac6f3.png">

**Comment by Lulalaby** [comment]
> 
> 
> If one starts at the organisation page it's not immediately clear how to get involved with coding:
> 
> <img alt="Screenshot 2019-03-11 14 31 39" width="1168" src="https://user-images.githubusercontent.com/30216/54131517-68cae580-440a-11e9-91b2-cd4e08e248d1.png">
> 
> Perhaps the description for the main Human Connection repo could say "start here"? Or maybe we're happy to have people poke around
> 
> <img alt="Screenshot 2019-03-11 14 33 30" width="1288" src="https://user-images.githubusercontent.com/30216/54131652-af204480-440a-11e9-9afe-73c647c15e35.png">
> 
> would be great if we could somehow guide folks into the CONTRIBUTING.md so that there's a clear path of how to get started ... i.e. not rely on them having to reach out in discord etc.

I'll do it, good one

**Comment by Lulalaby** [comment]
> should the link associated with the project at the highest level perhaps go to the documentation, which would then hyperlink to the chat? or can we have more than one link?

Only one link is possible, we will talk about it with the helpers at the discord.
Thanks for the notice!

**Comment by appinteractive** [comment]
@Lulalaby a link to the documentation would not be okay? It das some getting started there. What do you think?

**Comment by Lulalaby** [comment]
> 
> 
> @Lulalaby a link to the documentation would not be okay? It das some getting started there. What do you think?

I think a we could give a bit more and easier general informations there.
I'll try something tomorrow and talk with you guys about it.

**Comment by roschaefer** [comment]
+1 for single repository

**Comment by appinteractive** [comment]
You have given so many +1 for a mono repo @roschaefer that ist actually a multi repo again 😂

**Comment by roschaefer** [comment]
@tansaku I updated the pinned repos and we have a starting point now: https://github.com/Human-Connection/Human-Connection/
