### ISSUE TITLE
🚀 [Feature] Admin - Remove user profile

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#17]
**Is your feature request related to a problem? Please describe.**

```gherkin
Feature: Delete user data as admin
  As admin
  I want to delete all personal data of a user account, including posts and comments
  In order to comply with GDPR
```

If you disabled a user account as admin then this user cannot login anymore. Then this user can also not delete his/her user account anymore. If the user requests deletion of data e.g. by mail then we don't have an UI for that.

**Describe the solution you'd like**

![Screenshot - 2020-02-10T210146 444](https://user-images.githubusercontent.com/2110676/74185870-c8002e00-4c49-11ea-852d-eec5ced9e9ef.png)

![Screenshot - 2020-02-10T210314 338](https://user-images.githubusercontent.com/2110676/74185868-c7679780-4c49-11ea-9f34-4a37b786e836.png)

![Screenshot - 2020-02-10T210917 803](https://user-images.githubusercontent.com/2110676/74185867-c6366a80-4c49-11ea-8647-b4d591121c47.png)

**Describe alternatives you've considered**
We could use postman to access our API (without the UI).

**Comment by roschaefer** [comment]
@datenbrei we could also split this feature, I would suggest to 
* have a list of all user profiles on the admin page
* when I click on a user profile as admin, I see a "delete user" button

**Comment by Mogge** [comment]
not stale

**Comment by Tirokk** [comment]
Not stale and @ogerly is working on it!
