### ISSUE TITLE
🚀 [Feature] [Moderation] When reporting Content Users can add specific information

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#1707]
## :rocket: Feature

When somebody reports users, contributions or comments he would like to add some information why he is doing so. Proposal: This should be choosen from a list (for later statistics) and a free form field for additional optional information.

**Choices** for the list:

- Discriminatory posts, comments, utterances or insults
- Posting or linking of clearly pornographic material
- Glorification or trivialization of cruel or inhuman acts of violence
- The disclosure of others' personal information without their consent or threat there of ("doxing")
- Intentional intimidation, stalking or persecution
- Advertising products and services with commercial intent
- Criminal behavior or violation of German law
- Other

### Additional context

The data should later be visible within the reports list in the moderator panel

**Comment by Tirokk** [comment]
@datenbrei can you give me the German translations of the choices, please.

**Comment by datenbrei** [comment]
Here the translations to German:

- Diskriminierende Beiträge, Kommentare, Äußerungen oder Beleidigungen, insbesondere solche, die sich auf Geschlecht, sexuelle Orientierung, Rasse, Religion, politische oder weltanschauliche Ausrichtung oder Behinderung beziehen.
- Das Posten oder Verlinken eindeutig pornografischen Materials.
- Verherrlichung oder Verharmlosung grausamer oder unmenschlicher Gewalttätigkeiten.
- Das Veröffentlichen von personenbezogenen Daten anderer ohne deren Einverständnis oder das Androhen dessen ("Doxing").
- Absichtliche Einschüchterung, Stalking oder Verfolgung.
- Bewerben von Produkten und Dienstleistungen mit kommerzieller Absicht.
- Strafbares Verhalten bzw. Verstoß gegen deutsches Recht.

Textlength for the optional field: 200 chars I'd say.

**Comment by datenbrei** [comment]
It may be, that we add some list items later

**Comment by Tirokk** [comment]
Okay, thanks.

The reporter can only chose one choice? @datenbrei
