### ISSUE TITLE
🚀 [Feature] Block User 2.0

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#1724]
## :rocket: Feature

~~~ gherkin
As a network User 
I'd like to block one or more other users
to not get confrontated with them any longer.
~~~
This is deciding what **an other user can't do anymore with me**.
This is different from blacklisting users: **what I'd like to see**.
This is agreed with Dennis on 2019-09-23.

**Changes to current implementation**
- [ ] The blocked user can always see my articles, these are not hidden
- [ ] Blocked users always get notices if they are mentioned by me (no shadow banning)

Shadow banning: (the other user does not know, that he is blacklisted)

**Behaviour as current implementation**
- [ ] But the blocked user can't comment under my articles
- [ ] Blocked users can't @mention me

- [ ] Optionally ask, if a user should also be blacklisted #279 

### Design & Layout

![block-user](https://user-images.githubusercontent.com/13457963/65611592-53d32f80-dfb3-11e9-98ef-37541be557ba.png)

### Additional context

- [ ] Later: Blocked users can't have friendship with me
- [ ] Later: Blocked users can't contact me via chat

**Comment by alina-beck** [comment]
@datenbrei this feature needs more clarification!

We are talking about two different features here, right? `Blacklist` and `block user`? If I understand you correctly, then what we currently have in the database as `blocked` should actually be `blacklisted` and we need to add a new relation type? If so, then can we please clarify both features in separate issues?

Here is what I understand (and don't understand :wink:) so far:

**When I blacklist a user**
- I no longer see their posts in my feed
- can I see their comments?
- do I get a notification when they mention me?
- it has no direct effect on them, the things they can do?

**When I block a user**
- they can see my posts and comments
- they get notifications when I mention them (but they can never respond to what I am saying about them – is this fair? maybe I should not be able to mention them either?)
- they can not comment on my posts (how do we explain this? will they see that they have been blocked? where/how should this be displayed?)
- they can not mention me (how is this implemented? does my handle just disappear from the list of possible mentions?)
- it has no direct effect on me, the things I can do?
- I am asked if I also want to blacklist them (how/where does this happen? do I click a button? do I see two checkboxes? does the question pop up in a modal?)

And one more question: Do you think the distinction between `blocked` and `blacklisted` will be clear to the users? What would the German translations be?

**Comment by datenbrei** [comment]
Hi @alina-beck There still is a seperate EPIC for the blacklist, #307 . This one is really epic, so you are right: The current implementation was an all-in-one-like. After done, Dennis decided, that he would like to have a change on it. So from my point of view currently we just would need to reverse some restrictions we'd done and nothing else for now:

 The blocked user can always see my articles, these are not hidden (currently he can not)
 Blocked users always get notices if they are mentioned by me (currently they can be mentoned, but don't see this == shadow banning)

**Comment by alina-beck** [comment]
@datenbrei thanks, that helps!

Still some open questions. So far a user can not see a post and therefore not comment on it. If they now see the post:
> - they can not comment on my posts (how do we explain this? will they see that they have been blocked? where/how should this be displayed?)

And:
> they get notifications when I mention them (but they can never respond to what I am saying about them – is this fair? maybe I should not be able to mention them either?)

**Comment by alina-beck** [comment]
Update after today's meeting with @ogerly and @DennisHack:

**Blacklist** is always related to content!
Content (currently `Posts`) can be blacklisted (i.e. permanently filtered) _in the future_
- by `categories`
- by `author`
- by a word or phrase entered by the user

**Blocking** is always related to a user!

Questions:
- What do I see when I visit the user profile of a user I have `blocked`? (Probably the whole profile?)
- What do I see when I visit the user profile of a user I have `blacklisted`? (Probably no posts?)
- Do I still find `blocked` and/or `blacklisted` users in the user search results? (Probably yes to both?)
- Do I still find `Posts` by users I have `blacklisted` in the post search results? (Probably not – but is this currently implemented?)

**Comment by roschaefer** [comment]
@DennisHack @datenbrei  ping :point_up:

**Comment by datenbrei** [comment]
## What do I see when I visit the user profile of a user I have blocked? (Probably the whole profile?)

You see everything as normal

## What do I see when I visit the user profile of a user I have blacklisted? (Probably no posts?)

No post, no comments (in the profile

## Do I still find blocked and/or blacklisted users in the user search results? (Probably yes to both?)

Yes, both, because you need to be able to revert your decision

## Do I still find Posts by users I have blacklisted in the post search results? (Probably not – but is this currently implemented?)

No, blacklisting means: You would not like to see any of his content

**Comment by mattwr18** [comment]
We have talked about this in today's meeting, and while there wasn't perfect agreement, one way forward is to break this into two tasks.
1) Convert the current `BLOCKED` relationship to `BLACKLISTED`, since it is currently working, with minor adjustments, to achieve a blacklist of user's content, which another user is not interested in seeing. See https://github.com/Human-Connection/Human-Connection/issues/279
2) Develop the `BLOCKED` relationship between two users, which would mean that a user can not interact with me on the network, ie they cannot comment on my `Post`s

**Comment by roschaefer** [comment]
I suggest to rename `BLACKLISTED` to `MUTED` because that's how other networks including Mastodon call it. People will feel familiar with it

**Comment by mattwr18** [comment]
hehe... I guess I could go through and change the `28` files I've just finished updating
https://github.com/Human-Connection/Human-Connection/pull/2686/files

I wonder how this fits in the greater idea of `blacklisting` content... see https://github.com/Human-Connection/Human-Connection/issues/307

**Comment by mattwr18** [comment]
@datenbrei when you say we need to find the `User` we have blocked/muted in our search results so that we can revert our decision... 
you can go to your settings page and revert these decisions.
I have removed the code that would remove `BLOCKED` users from search results, however, as requested.
let me know if the above info changes anything.
