### ISSUE TITLE
🐛 [Bug] Return to old position in Dashboard from Article View

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#1742]
## :bug: Bugreport
If somebody opens an article and presses the back arrow or button, he will not land on the same position of the article list, as before.

### Steps to reproduce the behavior
1. Step into an article
2. Go back

### Expected behavior
Although the article dashboard is dynamic, one should come back to the at least nearly the same place, if he presses the back arrow in the browser

### Version & Environment
 Type: [Desktop]      
 - OS: [Linux]      
 - Browser: [Firefox] 
 - Version [69]  
 - Device: [Notebook]  

### Additional context
This Bugfix may not be a priority. :-)

**Comment by mattwr18** [comment]
This happens on mobile as well, and is super annoying... It makes the site very difficult to use
