### ISSUE TITLE
🚀 [Feature] Extend Emoticons

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#1745]
## :rocket: Feature
The available Emoticons in the articles are to be extended.

### Design & Layout
This is the actual set:
![emoticons](https://user-images.githubusercontent.com/13457963/65764486-0e833f00-e126-11e9-88f7-7e33a4522735.png)
These are the emoticons which have to be added:
(will follow)

### Additional context
Also the corresponding filters have to be adapted.

**Comment by datenbrei** [comment]
Closed in favor of #66

**Comment by DennisHack** [comment]
Who will add the addtitional emojis? How long will it take? Issue #66 THANKS!

**Comment by datenbrei** [comment]
@DennisHack We will do our planning for the next sprint tomorrow. If you would like to have it as part of our next sprint, just tell me. You and me together as product owner do the priorization.

Here is the release "Go Public" 

https://app.zenhub.com/workspaces/nitro-5c0154ecc699f60fc92cf11f/reports/release?release=5d8b515a022c8d0001c05f45

THe above emoticons extension is part of the next release so far: 

https://app.zenhub.com/workspaces/nitro-5c0154ecc699f60fc92cf11f/reports/release?release=5d8b531ebb171300016bef5b

**Comment by datenbrei** [comment]
Sorry, accidentilly closed

**Comment by datenbrei** [comment]
And closed again...
