### ISSUE TITLE
🚀 [Feature] Blur explicit Image Content

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#1746]
## :rocket: Feature
The content of sensitive images NSFW (not safe for work) can be blurred so that it does not scare sensitive people.

### Design & Layout
Original Picture:
![sensitive1](https://user-images.githubusercontent.com/13457963/65765076-7e45f980-e127-11e9-9774-4a76168be8e2.png)

Blurred picture:
![sensitive-2](https://user-images.githubusercontent.com/13457963/65765089-8867f800-e127-11e9-8d7a-1f65d7040312.png)

Video: [Sensitive Filter](https://www.youtube.com/watch?v=9Oq6v7nG2XA)

### Additional context

It has to be defined, if just the author of an article should be able to mark it as sensitive or if any user should be able to do so. If so, it has to be decided, how the algorithm should work.

**Comment by mattwr18** [comment]
Can I get clarification on this issue before starting to work on it? 
1) this is intended not just to blur "explicit" images, ie nudity, but maybe "shocking" content, as in what others might consider not family-friendly, ie disturbing in some way? Like violent, scary, not appropriate for children(?)
2) who decides this, as @datenbrei asked? at first the user would have a check mark to mark their image as not child friendly?
3) users would then be expected to report content that they consider not child friendly?
4) would we add a filter at this time to remove anything users marked as not family-friendly, or do we want to just blur the images?
5) what about content that is age appropriate? do we want to just blur images, but not have a way to filter content the user doesn't think is appropriate for their children to read?
6) Anyone else have questions about this feature that I'm not thinking about?

**Comment by datenbrei** [comment]
Hope I can answer your questions:
1. Don't think about reasons at all. Let us just find a good word for it: desturbing, shocking. In German: "Ggf. verstörend". We could take the wording from other networks, like Mastodon.
2. Yes, exactly, the original author would mark this at first.
3. Yes, users could later report desturbing content and the moderation would decide. So I could imagine, that we would need two flags, one set by the original author and one set by moderators (like the disabled flag). Later, it would be imaginable to find an algo to let users decide about this without beeing able to use this as some kind of political "weapon".
4. just blurring, just images.
5. The same, let us just be able to blur, don't think about hte reasons behind. People could use it for anything annoying
6.

**Comment by DennisHack** [comment]
to Question 4: what about YT-Video preview picture? Can we blur it as well?

**Comment by DennisHack** [comment]
Rest should be ok without warranty!

**Comment by mattwr18** [comment]
sorry, a question I hadn't thought of, users should have some way of removing the blur effect from the images, right?
