### ISSUE TITLE
🚀 [Feature] Article's Shout displayed in Profile or not

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#1747]
## :rocket: Feature
If somebody shouts an article it should be possible to decide, if this shout should be also displayed in the profile or not.

### Additional context
This is a privacy option. Somebody could just shout non-political articles for example so that nobody could guess his political direction from it.

**Comment by DennisHack** [comment]
is this really so important right now? If yes, I would also like to ask for a short meeting to clarify in detail how it will be made or if there are still questions open. Thanks!

**Comment by mattwr18** [comment]
We have a `PR` with part of the implementation that would allow users to be able to decide for themselves whether they would like to show their `shouted` Posts to other users here: https://github.com/Human-Connection/Human-Connection/pull/2101

There were questions about the frontend implementation that @alina-beck added to the `PR` :point_up_2: 

Whether it is important right now is a question sure. I think we didn't have user-based evidence that shouts should be hidden from other users, but you, @DennisHack, felt very strongly that they should be anonymous. We decided in that meeting, with yourself and the development team, that we would make them anonymous, but then program it to give the decision to the user, not make the decision for them and enforce it.

I guess a meeting could be organised, alternatively, maybe you could see how @alina-beck proposed it to be implemented and comment on what you think about her ideas? Then, you don't have to be available at the same time, but can work asynchronously.
