### ISSUE TITLE
🐛 [Bug] Logged in as one user refreshing page switches user

### ISSUE THREAD

**Issue by mattwr18** [Human-Connection/Human-Connection#1789]
## :bug: Bugreport

Weird bug where it seems the cookies are not getting deleted properly

### Steps to reproduce the behavior
1. Log in as one user
2. Log out
3. Log in as another user
4. Write a comment as second user
5. Do a hard refresh
6. Sometimes it switches user back to first user

### Expected behavior

The cookie should be properly deleted on log out so there is no chance of switching users

![Screenshot from 2019-10-01 19-18-45](https://user-images.githubusercontent.com/26943915/65984688-9350be80-e480-11e9-9d31-6d23a359a43a.png)

### Version & Environment
 Type: []      Desktop
 - OS: []      Linux
 - Browser: [] Chromium

**Comment by mattwr18** [comment]
Also sporadically happens on `Firefox` as well

**Comment by datenbrei** [comment]
@mattwr18 Is this still fixed? As good as I remember, it had to do with cookies beeing permanent instead of for the session or so?
