### ISSUE TITLE
User settings: change email address

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#18]
**Is your feature request related to a problem? Please describe.**
As a user, I would like to change my login email address. E.g. to change my email provider, because I lost access to my former email address, etc.

**Describe the solution you'd like**

When I visit https://alpha.human-connection.org/auth/settings I want to change my email address, just as I can change my name already.

**Describe alternatives you've considered**
The current alternative to contact support is a rather time consuming, manual and error-prone procedure.

**Additional context**
![e5470f16-0b6d-4499-b582-53ebe22332d2](https://user-images.githubusercontent.com/2110676/45563609-2c00a600-b84e-11e8-826f-25d8e3b34e5a.png)

**Comment by appinteractive** [comment]
Keep in mind that we need to validate that address by double opt in again!

**Comment by ulfgebhardt** [comment]
closed in favor of https://github.com/Human-Connection/Human-Connection/issues/407
