### ISSUE TITLE
🚀 [Feature] [Moderation] Enforce the moderators to first report before they can disable

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#1830]
## :rocket: Feature

Users, posts, and comments should be only possible to disable if they are reported before.

- This is important for transparency. A moderator can not disable nodes without reason and knowledge of other moderators.
- This makes the human interface less complex. See Additional context …

### Design & Layout

- For moderators the context menu should have no item `Disable Contribution` (and other nodes) if the node is not reported.
- As a hint only for moderators the context menu report item `Report Post` (and other nodes) should be named `Report Post (necessary for disabling)`.

### Additional context

Then we need no extra list for disabled nodes.

### Todo

- [x] Backend should only disable nodes that are reported already.
- [x] Change the database: All disabled nodes get a report relation with the submitter as the disabler, the `reasonCategory` as `other` and the `reasonDescription` as `Automatically created for database consistency …`.

**Comment by datenbrei** [comment]
Very good. This way we always have a protocol about why something was disabled, when it was done and who has done so. This is very important if we think about users trusting in us.

**Comment by Tirokk** [comment]
This is or can be still necessary.
Please prove.

**Comment by Tirokk** [comment]
This issue has been already totally fulfilled by PR List and protocol moderation #1954 and can be closed.
Or? @mattwr18

**Comment by Tirokk** [comment]
I close this, because it is in my eyes totally fulfilled.
