### ISSUE TITLE
🚀 [Feature] Make Tags below Posts  clickable as Hashtags are

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#1851]
## :rocket: Feature
You can click on a hashtag, but not on the tags below the post, which are made out of them.

Also the **Tag below should be clickable, as the hashtag is**.

### Design & Layout
![tags](https://user-images.githubusercontent.com/13457963/66474220-239a8f00-ea91-11e9-92d6-828547b58b4f.png)

### Additional context

![Bildschirmfoto 2019-10-25 um 22 03 29](https://user-images.githubusercontent.com/25344101/67616070-99626280-f7d4-11e9-97ee-6bdf0619fd20.png)

Should have links like here:

![Bildschirmfoto 2019-10-26 um 09 43 55](https://user-images.githubusercontent.com/25344101/67616136-64a2db00-f7d5-11e9-92c6-65403c9b3f7d.png)

**Comment by mcdead154** [comment]
Hi, i would like to work on this issue.

**Comment by DennisHack** [comment]
Hi mcdead154, 
yes, sure! Would be good to make an appointment for an short briefing together on Zoom. @datenbrei 
Thanks in advance! 
Dennis

**Comment by mcdead154** [comment]
Sure, I've made an account on Zoom. Briefing would be good for me to have a better understanding of issue and application in overall.

**Comment by Tirokk** [comment]
@mcdead154 are you still interested to work on this issue?

**Comment by mcdead154** [comment]
Yes, I would like to work on this.

**Comment by roschaefer** [comment]
@mcdead154 are you still on this issue? Because I would like to use it as an exercise for some computer science students tomorrow.

**Comment by mcdead154** [comment]
@roschaefer yes I work on this I just waited for some response since @DennisHack wrote we will have a briefing. But I'll make a PR on this in this sprint.

**Comment by datenbrei** [comment]
Hi @mcdead154 , I'm sorry for this, I didn't get and get a notification although I have switched on that I get notifications for discussions I take part on.

For this minor feature we don't need a briefing. It is just, that the same happens, if you click on a tag below the article as if you click on the hashtag in the article itself.

**Comment by mattwr18** [comment]
closed by https://github.com/Human-Connection/Human-Connection/pull/2091
