### ISSUE TITLE
🐛 [Bug] Hover on Avatar disables Scrollbar

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#1857]
## :bug: Bugreport
When you move your mouse over an avatar/user picture a tooltip appears and the scrollbar on the right disappearss. Because of this the whole window content moves a bit to the right.

Normal view with normal scrollbar
![ok](https://user-images.githubusercontent.com/13457963/66576656-66836200-eb78-11e9-9403-adcdf21f6df2.png)

Bad view with missing scrollbar
![not-ok](https://user-images.githubusercontent.com/13457963/66576695-756a1480-eb78-11e9-852d-be16dcaf092d.png)

### Steps to reproduce the behavior
1. Put your mouse over an article's author picture

### Version & Environment
 Type: []      
 - OS: []      
 - Browser: [] 
 - Version []  
 - Device: []

**Comment by izhuravlev** [comment]
Hey @datenbrei,
Can I work on this one?
