### ISSUE TITLE
🐛 [Bug] Add Reference ToS and Data privacy Statement to Register Dialogue

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#1873]
## :bug: Bugreport
When opening the registration dialogue there is not link or reference the the terms of ervice and the data privacy statement.
![register](https://user-images.githubusercontent.com/13457963/66644658-c41fb900-ec21-11e9-95be-70e9689a1310.png)

### Steps to reproduce the behavior
1. Open tregistration
2. See missing reference

### Expected behavior
Before registering you should see a reference to the above information

### Version & Environment
 Type: [all]      
 - OS: [all]      
 - Browser: [all] 
 - Version [all]  
 - Device: [all]  

### Additional context
It is a legal need, that anybody is informed **before** registration. ;-)

**Comment by ogerly** [comment]
and a point you're at least 18 years old.

**Comment by datenbrei** [comment]
Have a look in the corresponding issue: #1785

There is a list of all things, which are important to be part of that register dialoge. @mattwr18 , the #1785 is not yet complete, but already closed. I think best would be, if I will re-open it.

**Comment by ogerly** [comment]
![FireShot Capture 088 - Human Connection - Human Connection - localhost](https://user-images.githubusercontent.com/1324583/66826657-458e8880-ef4d-11e9-8509-384448d07a39.png)
![FireShot Capture 087 - Human Connection - Human Connection - localhost](https://user-images.githubusercontent.com/1324583/66826658-458e8880-ef4d-11e9-9d7e-ae1ef8258d46.png)
https://github.com/Human-Connection/Human-Connection/pull/1901
