### ISSUE TITLE
🐛 [Bug] Login page translation error DE

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#1874]
## :bug: Bugreport

Login page translation error DE.

### Steps to reproduce the behavior
1. go to login page
2. see here

![Bildschirmfoto 2019-10-11 um 12 19 21](https://user-images.githubusercontent.com/25344101/66645386-9d628200-ec23-11e9-9106-7c80dc54ab77.png)

**Comment by janethavi** [comment]
Can I get assigned to this issue? @Tirokk

**Comment by Tirokk** [comment]
Yes, for sure @janethavi . I assigned you.
Glad to have you here, caring for it ! 🙏🏼👍🏼
