### ISSUE TITLE
🚀 [Feature] Show Link to embedded Content when Embedding is off

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#1875]
## :rocket: Feature
Currently you just decide to:

1. can play embedded content as embedded
2. or you can't see it at all

If embedding is off you should be able to just see a link which openes **in a new browser windows/tab**.

### Design & Layout
![add-link](https://user-images.githubusercontent.com/13457963/66645327-73a95b00-ec23-11e9-866a-68dea28cdfc0.png)

### Implementation
Please add a storybook story for the embed component.

### Additional context
If we enforce people to see content embeeded or not at all, they will alyways click it.

**Comment by roschaefer** [comment]
I had this reopened for a second but when I tried to reproduce it, it looks very much implemented already. Closing.
