### ISSUE TITLE
🚀 [Feature]  Remembering last position in timeline

### ISSUE THREAD

**Issue by hermann-san** [Human-Connection/Human-Connection#1879]
## :rocket: Feature
when I'm scrolling down in the list of articles and at some point open an article, then when I click the back button from within the article, then it should bring me to the position where I left the timeline (list of articles) .  This is how Facebook does it and I think it makes sense to have it this way when browsing a list of articles.
At the moment, when I get back to the timeline it brings me to the top of the list instead of to the position where I was last.

![grafik](https://user-images.githubusercontent.com/7679654/66679715-28b53500-ec6f-11e9-8c84-b1fc22d85912.png)

**Comment by sushidave** [comment]
Decision required if this feature or #2514 should be implemented.
