### ISSUE TITLE
🐛 [Bug] Double ellipses for truncated strings

### ISSUE THREAD

**Issue by mattwr18** [Human-Connection/Human-Connection#1893]
## :bug: Bugreport

We refactored to use an npm library `trunc-html`, and now we have double `ellipses`

### Steps to reproduce the behavior
1. write a comment more than 180 characters
2. you should see show more link to click on and two sets of ellipses
3. you should see the same for long users names/long post titles
4. ...
5. Profit

### Expected behavior

we should only have one set of ellipses

At the moment, we are using `vue-filters` for our truncating...
```
 if (output.length < value.length) {
   output += ' …'
 }
```
this bit of code is superfluous
see https://github.com/Human-Connection/Human-Connection/blob/master/webapp/plugins/vue-filters.js#L42

**Comment by Tirokk** [comment]
Wonderfull that you took this issue and assigned yourself. @drowvoloper 
It would be very helpful for us if you can go for it, because we feel a pressure to get rid of the annoying design problem!

**Comment by drowvoloper** [comment]
I unassign myself for now and reassign at Friday if nobody works on this issue before!

**Comment by Tirokk** [comment]
Great dear! Thanks!

**Comment by Mogge** [comment]
I fexed it with the help of Roschaefer. Asking for  help for the commit workflow in discord
