### ISSUE TITLE
🐛 [Bug] Deleted or disables Users can't be unblocked for ever

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#1902]
## :bug: Bugreport
If a normal User blocks a second user and this one is disabled or deleted his own data, the former blocked users entry stays for ever in the list of blocked users.

The deleted or disabled user appears as UNAVAILABLE:
![blocked-unavailable](https://user-images.githubusercontent.com/13457963/66830235-49260d80-ef55-11e9-846a-fe3e971ac8bf.png)

When clicked it leads to an error:
![blocked-not-found](https://user-images.githubusercontent.com/13457963/66830256-57742980-ef55-11e9-84a0-42c05f650306.png)

### Steps to reproduce the behavior
1. Block a user
2. Let an admin disable him
3. Never get rid of the list item

### Expected behavior

1. A deleted User should also be deleted from  block lists
2. A disabled user should ether not appear in the blocked users list or it should be possible to remove a blocking without having the user himselfes available.

### Additional context
I have tested both, with disabled users and with deleted users.

**Comment by ogerly** [comment]
is this behavior also in chrome and firefox?

**Comment by sushidave** [comment]
@datenbrei Please reopen this issue if the bug still exists. 
Would it make sense to change the bot's settings so that it ignores bugs?
