### ISSUE TITLE
🐛 [Bug] Hashtags - one line after an embed no hashtags are recognized

### ISSUE THREAD

**Issue by ogerly** [Human-Connection/Human-Connection#1937]
### Steps to reproduce the behavior
1. create a new contribution

2. write a **#hashtag** about it 

3. bind a youtube video on **https://www.youtube.com/watch?v=P0_YVKkUJXA** 

4. write a **#hashtag** on the next line after the embed ( doesn't work)

5. write a **#hashtag** on the second following line (works)

![FireShot Capture 096 - Die Macht um Acht (37) - Human Connection - alpha human-connection org](https://user-images.githubusercontent.com/1324583/66951866-aa380900-f05b-11e9-8c10-017eb923aeab.png)

6. go to edit contribution 
7. go with the cursor to the #hashtags which didn't work 
8. now they should be selectable, respectively they should work
9. save the edited post (now all #hashtags go )

![FireShot Capture 097 - Die Macht um Acht (37) - Human Connection - alpha human-connection org](https://user-images.githubusercontent.com/1324583/66952621-4a426200-f05d-11e9-9f36-9d34ba4dfa66.png)

### Expected behavior
a hashtag should also work on the first following line of an embed
 
 

### Contribution
https://alpha.human-connection.org/post/6901630c-657a-4f74-94e7-e8274cbc8f47/die-macht-um-acht-37

**Comment by MarcoBomfim** [comment]
Can I take this one?

**Comment by sushidave** [comment]
@MarcoBomfim 

Thank you for contributing to this project! 

This also happens with mentions after embeds.

Absolutely. In HTML, a DIV tag inside a P tag is semantically incorrect. In the W3C specs it says about P elements that "It cannot contain block-level elements (including P itself).", see https://www.w3.org/TR/html401/struct/text.html#h-9.3.1. 

So the solution would be the separation: Closing the P element of the text before opening the DIV block for the embed.

**Comment by MarcoBomfim** [comment]
Good to have confirmation, actually! I'll start working on it, then.

**Comment by datenbrei** [comment]
Hi guys. There seem to be a lot of other HTML issues. I checked our output with some validators and there had been lots of issues.

Here I add a sampling of tools, which culd be used for analysis:

## Generic online validation tools

- [W3C Markup Validation Service](https://validator.w3.org/) - shows you if your HTML is correct
- [NU HTML Checker](https://validator.w3.org/nu/) - the same, but more modern and still experimental
- [W3C CSS Validation Service](https://jigsaw.w3.org/css-validator/) - for validating your CSS stylesheets
- [W3C Feed Validation Service](https://validator.w3.org/feed/) - shows you if the RSS feed you created is set up correctly
- [Validome Sitemap Validator](http://www.validome.org/google/validate) - check if your sitemap.xml is ok.
- [W3C mobileOK Checker](https://validator.w3.org/mobile/) - see if your website is well usable on mobile phones
- [Sistrix hreflang Validation](http://www.sistrix.de/hreflang-guide/validator/) - shows if your website has [correct international language information](http://www.ranking-check.de/blog/hreflang-die-5-haeufigsten-fehler-und-hall-of-fame/)

**Comment by MarcoBomfim** [comment]
So, I've managed to get a version working locally, which allows mentions and tags on the line below the Embed. **Although**, due to the change I've made, it broke a test, which I'm checking right now if I can fix this in any other way, or if we'll have to change the test itself. 

I'll keep this thread going, just to keep you folks posted, but I'll estimate that I'll be opening a PR by Friday.

**Comment by roschaefer** [comment]
@MarcoBomfim I've randomly estimated the working hours to 5, so we see some progress in our burndown chart:
https://app.zenhub.com/workspaces/nitro-5c0154ecc699f60fc92cf11f/reports/burndown?milestoneId=4816186
