### ISSUE TITLE
🐛 [Bug] Search delivers non-exact/fuzzy Matches

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#1948]
## :bug: Bugreport
When searching in the network there are too many results shown, which have nothing to do with the search term. The search algorithm is too fuzzy:

![fuzzy-search](https://user-images.githubusercontent.com/13457963/67070087-61797080-f17f-11e9-9894-f41caf0e7da6.png)

### Steps to reproduce the behavior
1. Search for 'Künast'
2. Get 'Knast'

### Expected behavior
The search should be less fuzzy

### Version & Environment
 Type: [Desktop]      
 - OS: [Linux]      
 - Browser: [Firefox] 
 - Version [69]  
 - Device: [Notebook]

**Comment by alina-beck** [comment]
no, mr bot – keep it open! :grin:
