### ISSUE TITLE
🚀 [Feature] Set default image cropping size to 100%

### ISSUE THREAD

**Issue by alina-beck** [Human-Connection/Human-Connection#1993]
## :rocket: Feature
brought up by Dennis

Users who don't want to crop their images are currently forced to adjust the cropping frame for every image they upload. In the future this feature should be optional (see #1934). As a quick workaround the default image cropping size could be set to 100%.

**Comment by Mogge** [comment]
autoCropArea: 1.0 in the options of Cropper does the job
