### ISSUE TITLE
🚀 [Feature] Load latest posts on logo click

### ISSUE THREAD

**Issue by alina-beck** [Human-Connection/Human-Connection#1994]
## :rocket: Feature
brought up by Dennis

When clicking on the Human Connection logo in the header the page should scroll up and latest posts should be loaded if not yet done - if possible without implementing too much new functionality. At least some kind of feedback to the user should be visible.

## Additional background
An alternative would be to automatically load the latest posts every few minutes – but this needs to be thought through UX wise! Will the latest posts be added to the top, messing up the user's scroll position? Will we display a notification that new posts are available? Then how can the user decide to see/load them?

**Comment by datenbrei** [comment]
We once was talking and deciding about this with @roschaefer in a discussion. My memory is, that we decided upon this, that there would be a ways without reloading the whole page. We also decided to choose the easy way. But I can't tlak about implementation details. Robert, can you add these?

**Comment by mattwr18** [comment]
We talked about it @datenbrei, but it is not easy to implement because where the logo lives is not where the query for the `Post` are, so we would have to refactor to move everything to the `Vuex` store, probably...

**Comment by alina-beck** [comment]
And the websocket/subscription feature you wanted to build is a lot of work as well, right? Is there an issue for it somewhere that we could prioritize instead of this one?

Because I feel like putting a lot of time into refactoring this to use `Vuex` and then removing it again a few weeks later in favor of subscriptions might be a waste of time...

**Comment by mattwr18** [comment]
It might not be that much work to refactor to use `Vuex` because we can still use a smart query and add one mutation and one getter, then use them in both the page, and the layout...
Now, I've gotten distracted by the duplicate posts on the root path, which I can't seem to find an issue for at the moment
