### ISSUE TITLE
Hubzilla 

### ISSUE THREAD

**Issue by ShalokShalom** [Human-Connection/Human-Connection#2]
This decentralized open source alternative to Facebook provides an API to include streams from practically every other platform, so HC is probably interested to provide one also: https://project.hubzilla.org/page/hubzilla/hubzilla-project

**Comment by appinteractive** [comment]
Hey thanks for that link, we will look into it by time. 

How would you imagine the Integration in HC?

**Comment by ShalokShalom** [comment]
Well, implementing their protocol?

**Comment by appinteractive** [comment]
Yeah, I meant not technically but if you have a concrete scenario for the user. I mean it could be used in deferent scenarios depending how we would make it beneficial for the user.

**Comment by ShalokShalom** [comment]
https://hub.libranet.de/help/en/developer/zot_protocol

https://project.hubzilla.org/help/en/member/member_guide#Connecting_To_Channels

**Comment by frankgerhardt** [comment]
@appinteractive how does integration of things like this supposed to work? Is there a  plug-in system? Is there a discussion about such topics anywhere?

**Comment by datenbrei** [comment]
Reimplementing Zot protocol in javascript may be a task too big actually. Possibly Hubzilla could be connected via the ActivityPub interface of Hubzilla? Implementing Zot on our side would mean, that also internally we would have to implement all things like nomadic identity, a detailed permission system and so on.  Up to now the HC network is thought as a more or less public network, like Wikipedia. It is not thought as a private messaging platform. This does not mean, that thing will be added at time. ;-)

**Comment by frankgerhardt** [comment]
I watched Martin's video from November yesterday where he showed the todo list for January 2019 and said that Nitro would go live by the end of March, which is now. Have you focused on those must-have features and will you go live soon?
If not, why then even look at secondary nice-to-have but not critical issues like this one?

**Comment by frankgerhardt** [comment]
BTW, why go for a more complicated feature like ActivityPub if you don't even have a simple RSS feed yet.

**Comment by roschaefer** [comment]
@frankgerhardt regarding the dates: I'm sorry that we won't go live at the end of March. Setting up deadlines, communicating those deadlines and and not keeping up with those is a procedure which originates from the time when we did not follow a development process like [scrum](https://en.wikipedia.org/wiki/Scrum_%28software_development%29). We 're currently adopting that process. My preferred way is to communicate a list of todos (not deadlines) and each item is either done or not. This way, you wouldn't be disappointed when we miss deadline after deadline, instead you see the progress.

Regarding ActivityPub: 90% of the current implementation is done by our fellow contributor @Mastercuber rather independently, ie. the rest of the team did not spend time on it. Therefore it was a high-value, low-cost decision which I certainly don't regret.

**Comment by roschaefer** [comment]
@ShalokShalom Human Connection will implement ActivityPub first before moving on to other protocols. I see that Hubzilla [also implements ActivityPub](https://fediverse.party/en/hubzilla/), so we will be able to communicate. I would like close this, wait for our AP implementation to finish and re-open once we see a use-case to implement Zot or any other Hubzilla-related protocol.
