### ISSUE TITLE
Versus

### ISSUE THREAD

**Issue by Mastercuber** [Human-Connection/Human-Connection#20]
![versus](https://user-images.githubusercontent.com/14162739/45636165-44b7c880-baa7-11e8-8fa0-2655b4a5bbeb.png)
![versus-all](https://user-images.githubusercontent.com/14162739/45636167-44b7c880-baa7-11e8-8221-282e85bee8c7.png)

**Comment by roschaefer** [comment]
Can sb. add some explanation to this feature? What is the problem? How does the solution look like? How does that help a user?

**Comment by roschaefer** [comment]
closed in favour of #310
