### ISSUE TITLE
🚀 [Feature] Donation Button Directly On The Social Network

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#2040]
## :rocket: Feature
We want to put a little info graphic showing the monthly donation status along with a donation button on the network to encourage more people to donate.

### Problem
We need to make users aware that we depend on them and their support through donations. We also want to show them how dire the situation can be to create an appropriate sense of urgency.

### Implementation
- We will add a page to the admin interface where admins can enter numbers for the `total required donations` and `incoming donations`.
- We will place a `progress bar`, `the above numbers` and a `donate now button` on top of the index page, next to the sorting dropdown.
- The progress bar should represent the relation between the `total` and the `incoming` numbers. It should not go higher than 100%.
- The button should lead to the `donations` page on https://human-connection.org.
- On mobile we could a) alternate between the button and the progress bar, b) show the button below the progress bar or c) display just the button (whichever is easiest, for now!)

Open question: How will the numbers be stored in the database?

### Design & Layout
Here is a quick mockup:
<img width="362" alt="Screenshot 2019-11-07 at 10 53 31" src="https://user-images.githubusercontent.com/11694483/68370109-c4da3b00-014c-11ea-9f0b-9683f9b95755.png">

Different from this mockup we agreed that we will place the button _next to_ the progress bar and we'll of course use the same button design as everywhere else on the network.

### Validation
- more donations coming in! :smile:

### Additional context
In the future we could think about displaying this only to users who are not yet donating monthly because it might be annoying otherwise. On the other hand, it might motivate people to increase their monthly donations if they see how badly we need it. 😬

**Comment by mindcodemediator** [comment]
I'm interested in tackling this

**Comment by alina-beck** [comment]
Hey @mindcodemediator, sorry for the late response. Are you still interested in working on this issue? That would be great! :rocket:

I just think it needs some clarification first, @Tirokk and @datenbrei:
- where on the page should this be located (header, footer, user profile... ?)
- should it be a call to action `button` or a `link` to the donations page?
- what's the target URL or what is supposed to happen on button click?
- any design specifications?

@mindcodemediator if you have any thoughts on this already feel free to share them, too! :smile:

**Comment by datenbrei** [comment]
I asked Dennis about these questions. Will give feedback as soon, as I got it.

**Comment by datenbrei** [comment]
Martin is inviting you to a scheduled Zoom meeting.

Topic: Feature Clarification
Time: Nov 6, 2019 10:00 Amsterdam, Berlin, Rome, Stockholm, Vienna

Join Zoom Meeting
https://zoom.us/j/877887275

Meeting ID: 877 887 275

**Comment by alina-beck** [comment]
I updated the description according to what we discussed in today's meeting, so as soon as I get the design mockup this is good to go! @mindcodemediator, please let me know if you're still interested in working on this and if you have any more questions. 🙂
