### ISSUE TITLE
🚀 [Feature] Back link is missing, if e-mail address already exists.

### ISSUE THREAD

**Issue by chriswalg** [Human-Connection/Human-Connection#2042]
## :rocket: Feature
If the e-mail address is already found in the database, a new page will appear with the message, but the user will not know how to get back to the login page. Here is a back link missing.

![mail-already-exist](https://user-images.githubusercontent.com/2790065/67561874-ec2d1300-f71d-11e9-9024-b83f928b76f3.png)

**Comment by Mogge** [comment]
See #1832 
It seems to be the better solution
