### ISSUE TITLE
🚀 [Feature] Filter Posts by language 

### ISSUE THREAD

**Issue by Mogge** [Human-Connection/Human-Connection#2045]
## :rocket: Feature

![grafik](https://user-images.githubusercontent.com/15882241/67595078-1276a100-f766-11e9-9c14-0bac4ffb9d52.png)

I think that entering HC as non German speaker may cause the impression of a pure German Network, because until now nearly all the posts you see are in German.
To avoid this, it should be possible to filter the post by language, and may be set the default of the filter to the selected language.

### Design & Layout
As indicated in the screenshot. May be it is better placed below the emotes.

### Additional context
Thinking about the possiibilty to save filters.

**Comment by Mogge** [comment]
First implementation in branch 2045-filter-posts-by-language.
Where can we get Icons for the languages in an easy way?
Please check store/posts.js if the filters are doing what we want.

**Comment by Mogge** [comment]
We could add a image prop to the locales object in locales/index.js containing the route to the image of the flag of the language

**Comment by datenbrei** [comment]
@Mogge Great. Although I can't say so much about your code, there would be th e possibility to just use the UTF-8 Flag-set. But better would be specific icons for that, becuasen not any browser may have a font with full UTF-8 flags installed...

**Comment by Tirokk** [comment]
And the flags are not absolutely related to the flags of the countries as well. @Mogge @datenbrei 
English language should have the English or the USA flag as an example … ?

Additional we need related countries on the posts and be able to filter for them as well. See #782

**Comment by Tirokk** [comment]
We should switch with the discussion to the PR #2059 !

**Comment by Mogge** [comment]
![grafik](https://user-images.githubusercontent.com/15882241/67951160-441abc80-fbeb-11e9-9623-391773bd009f.png)

New solution. As agreed with @mattwr18
