### ISSUE TITLE
💬 [Question] Regions where you cannot select location in profile

### ISSUE THREAD

**Issue by Mogge** [Human-Connection/Human-Connection#2047]
![grafik](https://user-images.githubusercontent.com/15882241/67643048-f106e800-f912-11e9-8588-38669d0ca794.png)

## :speech_balloon: Question
May be it is a bug. I login form Spain and I cannot select any location. I checked it again together with a friend on her account and her machine and she had the same problem.

**Comment by Mogge** [comment]
Forget about it. I was confused by the dropdown menu

**Comment by mattwr18** [comment]
hey @Mogge is this in development, or in production? it would be great to capture the url in the screen shot, so it's clear... there can be different solutions depending on the environment
