### ISSUE TITLE
🐛 [Bug] Password-Reset/Registration Dialogue is Case-Sensitive

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#2057]
## :bug: Bugreport
When users want to reset their passwords or want to register and they use emails with uppcercase in it, these can not be found and you get an email which says:  _You requested a password reset but unfortunately we couldn't find an account associated with your e-mail address. Did you maybe use another one when you signed up?_

![wrong-email](https://user-images.githubusercontent.com/13457963/67678002-cbff8d00-f985-11e9-9123-9f8d44b6771f.png)

### Steps to reproduce the behavior
1. Open reset Password dialogue
2. Type in your emial with upper case letters

![Screenshot - 2019-10-29T171429 064](https://user-images.githubusercontent.com/2110676/67786950-06455900-fa70-11e9-964e-156aa18aec4b.png)

![Screenshot - 2019-10-29T171929 698](https://user-images.githubusercontent.com/2110676/67786924-fded1e00-fa6f-11e9-893a-c6351d2433cf.png)

### Expected behavior
The given email for reset should be converted to lowercase

### Version & Environment
any

**Comment by StephenHogsten** [comment]
Can I give this one a shot?

**Comment by datenbrei** [comment]
Yes, please do so, I can't see anybody working on it so far. @roschaefer , @Tirokk , @ogerly , @mattwr18

**Comment by medizinmensch** [comment]
@datenbrei @roschaefer, isn't that a backend issue? Shouldn't it be converted to upper or lowercase there?

**Comment by medizinmensch** [comment]
@roschaefer , @datenbrei , I changed it in Branch 2057 for frontend. It needs to be changed in backend as well. Can somebody take over?
