### ISSUE TITLE
Neo4J DB initialization

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#206]
**Is your feature request related to a problem? Please describe.**
For performance, we would like to have a reproducible set of indices in our Neo4J database.

**Describe the solution you'd like**
Write a script, e.g. `migrate` or `db:setup` to create indices in Neo4J. This script will be run when a container starts and it should run after the default `entrypoint.sh`.

**Additional context**:
[Read about how to create an index in Neo4J](https://www.quackit.com/neo4j/tutorial/neo4j_create_an_index_using_cypher.cfm)

We could also add an initial user with admin privileges. This could replace the need for an unauthenticated server for seeding during our test suite.

**Comment by ulfgebhardt** [comment]
@roschaefer I assigned you because I think there was an issue about this lately - please check this issue out and confirm if its implemented or not. Feel free to unassign yourself

**Comment by roschaefer** [comment]
@ulfgebhardt there is a script which we call `migrate` but this particular issue here is not implemented. The solution that I would suggest is that we ship a custom docker image for neo4j (which we do already, see [dockerhub](https://hub.docker.com/r/humanconnection/neo4j)).

The tricky part is to create constraints in `Dockerfile`. Why? To create constraints via `cypher-shell` the database needs to be up and running. Also, we cannot use the default user, because `cypher-shell` refuses if you use the default user+password combination. So there are some headaches to fight if you want to fix this issue here.
