### ISSUE TITLE
Multiple user login - Should it be possible to login multiple times at the same time?

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#208]
**Is your feature request related to a problem? Please describe.**
Should it be possible to login multiple times at the same time?
I like to know if somebody else is on my account while there should be nobody, because I try to log-in.

**Describe the solution you'd like**
For safety and control I would prefer a user only can login once at the same time.

**Describe alternatives you've considered**

I know that we need multiple logins at the same time for the staging at the moment.

But a user only has the chance to acknowledge that somebody else is logged-in in his or her or _ account, if he(…) tries out to log-in and can not. He(…) only knows that he(…) should not be logged-in at the moment.
Therefore I have the opinion while I am not in staging I like to know if somebody else is on my account while there should be nobody.

**Comment by Mastercuber** [comment]
In one Browser(Mozilla Firefox) it's not possible to login twice. If you try it with 2 tabs or 2 windows it's not possible. With a different browser, e.g chrome, it is possible so in general multiple logins to one account is possible.

**Comment by roschaefer** [comment]
@Tirokk I would certainly expect multiple logins to be possible. e.g. if you login with your Desktop and your mobile at the same time. But how about to re-phrase this user-story and implement a list of "recent logins" in the security tab of your user settings? You could see a list of devices and IP address ranges and check it for plausibility.

**Comment by Tirokk** [comment]
@roschaefer a list of "recent logins“ is a wonderful and seemingly better solution.
Thank you!
@Mastercuber

**Comment by ulfgebhardt** [comment]
closed in favor of https://github.com/Human-Connection/Human-Connection/issues/634
