### ISSUE TITLE
🚀 [Feature] Order posts by recently commented

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#2099]
## :rocket: Feature

```gherkin
Feature: Order posts by recently commented
As a user
I would like to order posts on the start page by "most recently commented"
In order to keep up with ongoing discussions
```

### Design & Layout
![Screenshot - 2019-10-31T175147 809](https://user-images.githubusercontent.com/2110676/67967930-c2d12300-fc06-11e9-9bc0-b60491b17fa0.png)

### Additional context
Quote from a user:

    mich bewegt gerade die extreme Schnellebigkeit der Startseite. Bin ich es gewohnt aus Foren, dass ein Thema sich über Tage bis Wochen über viele einander ergänzende Beiträge entwickeln kann, sind derzeit bereits Beiträge vom Vortag gnadenlos ohne jede Chance, noch einmal von der Gemeinschaft bemerkt und gelegentlich noch gewürdigt zu werden.

    Peter Brotkauer-Waschmaschine beispielsweise interessiert sich sehr für ein Thema, zu welchem ich vorgestern einen Beitrag geschrieben habe. Er war aber leider zwei Tage verhindert und kommt erst in drei Stunden wieder online.

    Von meinem Beitrag bekommt er nichts mit. Schlimmer noch für mich: Ich bekomme nichts von seinen sehr wertvollen Gedanken mit, welche meine Sicht auf die Welt entscheident ergänzen würden, denn genau an dem Punkt, an dem mein fiktiver Peter steht, an den würde ich gerne gelangen, schaffe es aber nicht, weil mir ein zündender Gedanke fehlt.

    Wie könnte dem begegnet werden?

    Wie in Forensystemen eine Option, neue Beiträge seit dem letzten Besuch anschauen zu können.

    Themen, zu denen neue Kommentare verfasst werden, in einer "Diskussions"-Ansicht wieder nach oben zu sortieren. Sähe Peter meinen zwei Tage alten Beitrag und würde darauf reagieren, wäre er für eine gewisse Zeit auch wieder für alle anderen sichtbar und könnte mit Peters sehr wichtigigen und wertvollen Gedanken der Gemeinschaft von wertvollem Nutzen sein.

    In einer "Übersichts"-Ansicht könnten in verschiedenen Bereichen/Boxen/Feldern Beiträge nach unterschiedlichen Sortierungskriterien darbegoten werden, beispiesweise je 10 Stück. Das könnten Kriterien wie Beitragslänge, Beitragsinhalt ((Video)Verweise auf Drittseiten, Musik, Bilder, Text), Themenfelder, Gefühle, Wie oft "ausgerufen", Beitrag/Can Do, ...

    Wenn jede dieser Ansichten dann noch nach Bedarf konfigurierbar wäre, dann könnte (vielleicht nicht ur ich) mich hier irgendwann so richtig menschenwohl fühlen, wohler als ich mich in den "schönsten Foren" mich je gefühlt hatte...

    Mir liegt wie gesagt viel an bereicherndem Austausch, aber dieses "gnadenlose Versinken" älterer Beiträge betrübt mich.

    Naja, es ist eine Alpha und sie funktioniert ja auch in einigen Bereich schon ziemlich gut.

    Für eine Beta oder dann die erste finale Version von HC wären das so Wünsche, die mir jetzt gerade einfallen.

English translation:

    I'm moved by the extreme fastness of the homepage. If I am used to it from forums that a topic can develop over days to weeks over many complementary contributions, are at present already contributions of the previous day merciless without every chance to be noticed again by the community and occasionally still appreciated.

    Peter Brotkauer washing machine for example is very interested in a topic, to which I wrote a contribution the day before yesterday. Unfortunately, he was unable to attend for two days and won't be back online for another three hours.

    He doesn't notice anything about my contribution. Worse still for me: I get nothing of his very valuable thoughts with, which would supplement my view of the world decidedly, because exactly at the point, at which my fiktiver Peter stands, to which I would arrive gladly, it does not create however, because me a igniting thought is missing.

    How could this be met?

    As in forum systems an option to look at new contributions since the last visit.

    Sort topics for which new comments have been written up again in a "discussion" view. If Peter saw my two-day old post and reacted to it, he would be visible to everyone else for some time and could be of valuable use to the fellowship with Peter's very important and valuable thoughts.

    In an "overview" view, contributions could be presented in different areas/boxes/fields according to different sorting criteria, e.g. 10 pieces each. This could be criteria like contribution length, contribution content ((video) references to third pages, music, pictures, text), topic fields, feelings, how often "called out", contribution/can do, ...

    If each of these views would be configurable according to your needs, then (maybe not me) I could feel really comfortable here sometime, more comfortable than I had ever felt in the "most beautiful forums"...

    As I said, I am interested in enriching exchange, but this "merciless sinking" of older posts saddens me.

    Well, it's an alpha and it works pretty well in some areas.

    For a beta or then the first final version of HC, those would be wishes I can think of right now.

    Translated with www.DeepL.com/Translator

**Comment by ogerly** [comment]
@roschaefer I've had that in before. What was the problem with it being taken out?
