### ISSUE TITLE
Mentions - Permanent, unbreakable and text changeable mentions for users, posts etc.

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#210]
**Is your feature request related to a problem? Please describe.**
If I have understand right the slug of a user is used to store its identity in a comment or somewhere else. Therefore the link is breakable if the user changes its name. This is inakzeptable in my opinion, because it destroys important information.

**Describe the solution you'd like**
Using the users ID would make this link unbreakable, even when the user changes its name. And like on Discord a users ID or even the picture should show up in the dropdown, if you type the `@`‚ to distinguish between users with the same name.

**Describe alternatives you've considered**
I can not think of an other solution at the moment …

**Comment by mattwr18** [comment]
I think this can be closed @Tirokk, or I'm mistaken... as far as I've understood the `mentions` use the user's uuid and therefore if they change their name and/or slug... the link still points to their profile, oder?

**Comment by Tirokk** [comment]
This is fulfilled I think.
Thanks @mattwr18 ! 👍🏼
