### ISSUE TITLE
🐛 [Bug] Notifications query ignores poll interval and queries infinitely

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#2102]
## :bug: Bugreport
When you switch the language, you get infinite requests of the notifications. As if the notifications query would ignore the polling interval (I knew the poll interval would bite us again :disappointed: ). If you refresh the page, it's back to normal.

### Steps to reproduce the behavior
1. Visit https://nitro-staging.human-connection.org/
2. Login with an account
3. Open developer tools, switch to network tab
4. Switch the language
5. See way too many requests

@datenbrei this could very well be the reason for our high CPU utilization recently.

### Expected behavior
Notifications query might be refetched at most once until it's back to the normal poll frequency.

### Additional context
![2019-11-01-004335_1920x1080_scrot](https://user-images.githubusercontent.com/2110676/67993592-c59d3980-fc41-11e9-9b9c-af60a7b8dd46.png)

**Comment by ogerly** [comment]
this behavior is only after login. and only in the template default.vue in the template basic.vue it is not. 
to see if you go to the agb page after login and change the language. here the basic.vue template is used.

**Comment by ogerly** [comment]
there are requests in loop "mentioned_in_comment". which local are also filled with data. 

on the nitro are the doctrine fields and there is the loop "notifications" requests

**Comment by ogerly** [comment]
the error is in the NotificationMenu"
