### ISSUE TITLE
🚀 [Feature] Youtube links with play symbol

### ISSUE THREAD

**Issue by hermann-san** [Human-Connection/Human-Connection#2103]
## :rocket: Feature
Youtube links contain a preview image of the video. It is common that such Youtube preview images have a play symbol on it. It will animate the user to click on the video to start watching it and it also indicate that it is possible to watch the video within the page it is embedded in and one does not to leave HC to watch it. At the moment it is IMO not obvious that one can watch it within the article.
It would be nice if such a play symbol could be added to the image, even before one clicks at the image. 

### Design & Layout
see screenshot
![Auswahl_013](https://user-images.githubusercontent.com/7679654/67993687-41978180-fc42-11e9-99f0-4925e0d7ad64.png)

**Comment by ogerly** [comment]
please see what's embedded. 
for video or audio a play button can be inserted. for other embeddings not. so this has to be checked.

**Comment by hermann-san** [comment]
I had only Youtube in mind where there is only video. But if it's possible for other video's and audio as well, it would be nice too. 
With "please see what's embedded" you mean to check all of the below sites , whether they are vid or audio?

     Codepen, https://codepen.io
    DTube, https://d.tube/
    Facebook (Post), https://www.facebook.com/
    Facebook (Video), https://www.facebook.com/
    Flickr, https://www.flickr.com/
    GIPHY, https://giphy.com
    Instagram, https://instagram.com
    Meetup, http://www.meetup.com
    MixCloud, https://mixcloud.com/
    Reddit, https://reddit.com/
    SlideShare, http://www.slideshare.net/
    SoundCloud, http://soundcloud.com/
    Twitch, https://www.twitch.tv
    Twitter, http://www.twitter.com/
    Vimeo, https://vimeo.com/
    YouTube, https://www.youtube.com/

**Comment by ogerly** [comment]
@hermann-san 
yes, this is the list of third party suppliers we are currently allowing. it will definitely be extended soon. 
basically it would be an icon which we can put over the embed. vidoes and audios a playsymbol .. at left a linkOut symbol and at the rest we can think of something ... 

do you want to program this ?

**Comment by hermann-san** [comment]
@ogerly   I would  if I could, but unfortunately I'm not a developer and have no clue about Javescript, etc.

**Comment by ogerly** [comment]
Okay. No problem. 
it is made with :) beautiful week to you
