### ISSUE TITLE
🐛 [Bug] Comment Counters are Different

### ISSUE THREAD

**Issue by ogerly** [Human-Connection/Human-Connection#2112]
## :bug: Bugreport
the counter on the card post page counts out deleted comments, the counter on the contribution counter counts out deleted comments with  

![FireShot Capture 151 - Spenden- statt werbefinanziert! - Human Connection - human-connection social](https://user-images.githubusercontent.com/1324583/68092221-413cf780-fe89-11e9-960c-afb9aba60a30.png)

![FireShot Capture 149 - Human Connection - Human Connection - human-connection social](https://user-images.githubusercontent.com/1324583/68092223-44d07e80-fe89-11e9-925f-a1b1c7134101.png)

**Comment by yeltawil** [comment]
hi! I'm interested in working on this!

**Comment by sushidave** [comment]
@yeltawil Hello yeltawil, thank you for your readiness to work on this and I'm very sorry for the waiting. I just found this issue as being closed by error, so I reopened it and hope you're still interested. @Tirokk Kindly advise yeltawil how to proceed. Thank you!

**Comment by Tirokk** [comment]
At the moment I haven’t the role or rights here to give anyone permissions.
Hope this will change soon … @sushidave

**Comment by Elweyn** [comment]
Hello don't know if @yeltawil or someone else is working on this issue!? 
If not I would be interessted

**Comment by Tirokk** [comment]
Hey @Elweyn !
Wonderful! Great that you like to pick this up. 💫

I organise that you get invited you to our volunteer team via an e-mail invitation you can except.
After you excepted, please push your feature branch directly to this repo and create a PR using master as the base branch.

I assigned you to this issue …

On Discord we have kind of every day a Daily Standup at UTC 09:30 am (CEST 11:30 am) in the Conference Room. Sometime we switch to Zoom.

**Comment by Tirokk** [comment]
Hello @yeltawil ,
in case you are still interested in working on Human-Connection, please let me or us know.
We’ll find something else …

Our conversation runs over our discord channels:
http://hc.world/discord
Another possibility to get to it:
https://discord.com/invite/DFSjPaX

On Discord we have kind of every day a Daily Standup at UTC 09:30 am (CEST 11:30 am) in the Conference Room.

**Comment by Elweyn** [comment]
Hello @Tirokk,
yesterday I started a second pairing session and we steped on a much bigger problem...

Their was a behavior that appears randomly on my local maschin:
- Sometimes when I delete a comment this one is not directly deleted on the Post; when I reload the site afterwards the comment is deleted...

When this behavior appears then the commentsCount property is not actualized either.

Don't know if it is a new issue or we do it in here... Will speak about it with the team later.

Cheers

**Comment by sushidave** [comment]
Hello @Elweyn
Thanks for your comment. That seems to be issue #3357 and a user reported a similar problem in the network, see [here](https://human-connection.social/post/ec809b7a-9599-4ef8-8fd7-63a1c5d682f2/wird-hc-zensiert-1). Also, there is an issue with updating notifications, see #2821 .
@Tirokk

**Comment by Tirokk** [comment]
We’ll find this out @Elweyn . 👍🏼
Hope we can have a pairing session later …
