### ISSUE TITLE
Online Status 

### ISSUE THREAD

**Issue by appinteractive** [Human-Connection/Human-Connection#212]
**As a User**
I would like to see if someone is currently online. 
**so I know** if they can respond quickly on my writings or comments. 

### possible Solution:
Create some basic middleware that writes the current date of activity to the user. 

Only output if the user allows it, otherwise only admins can see it.

**Comment by mattwr18** [comment]
I think this might still be something people would like to see
we have a `lastActiveAt`, which is set when the `JWT` is decoded, but it is not displayed to anyone, and we'd need to add other activities like commenting, posting, reading notifications, etc...

**Comment by Mozar10** [comment]
Is this something I can start looking into ?
