### ISSUE TITLE
🚀 [Feature] Use Browser Language Setting for Registration Dialogue

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#2139]
## :rocket: Feature
1. If somebody want's to register, the browser default language is not taken into respect. Currently it falls back to english as default for a mostly german language network. There 2. should be a configurable default (e.g. German).

### User Problem
1. A German User may not feel comfortable with an English message box 
2. If I share a link to the registration dialogue, die meta-information is always in english:

### Implementation
The browser language setting should be respected for all dialogues. If no browser preset is given, a configurable default should be possible.

### Design & Layout
The language should be preset, matching the browsers default language
![register](https://user-images.githubusercontent.com/13457963/68277520-a7836f00-006f-11ea-88e9-2d64d4690825.png)

### Validation
A user get's the content in his language.

### Additional context
none

**Comment by ogerly** [comment]
at the start of the page the system checks which browser setting a user has. default is english. there is no possibility to check if another language speaks unless he chooses it. 
alternatively the language of HC default can be german. 
or we check a part of the ip that indicates the local space. 
and leave the check away from the browser.
