### ISSUE TITLE
Add tests for rewarding badges to users

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#214]
**Is your feature request related to a problem? Please describe.**
Make Backend function correct.

**Describe the solution you'd like**
Implement a reward relation mutation that saves the date and the user who created the reward of the badge.

**Describe alternatives you've considered**
Don’t save the date and the user who rewarded the badge.

**Additional context**

There a re some questions with my suggestions:

1. Should the date and user ID of the rewarder saved? *I would prefer to save the date and the user ID who rewarded the reward. What do you think?*
2. Who should be able to reward? *I think only admins should be able to do so and take them away.*

**Comment by mattwr18** [comment]
Closing as these tests were added in https://github.com/Human-Connection/Human-Connection/blob/master/backend/src/schema/resolvers/rewards.spec.js
