### ISSUE TITLE
🚀 [Feature] Have A Short Link For Organisations That Points To Their Profile

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#2141]
## :rocket: Feature

Have a short link for organisations that (for now) points to their profile.

- Make the slug part of the link case insensitive.
- It shall work for all user profile slugs which are not blocked by existing folders or other uses.

### User Problem

- We have no special link for organisations at the moment.
- The slug of such a link is case sensitive.

### Implementation

We need a link like:
`https://human-connection.social/RubikonMagazin`

Already working is:
`https://human-connection.social/profile/rubikonmagazin`

Does not work, but should also work:
`https://human-connection.social/profile/RubikonMagazin `

- Talk with @roschaefer ( or with me ( @Tirokk )) how to do it.

### Design & Layout

- None

### Validation

- None

### Additional context

- None

### ToDo

- [ ] make kind of a redirection (301)
- [ ] make the slug part of the link case insensitive, because slugs are always lowercase in the database

**Comment by Tirokk** [comment]
@roschaefer can you give the programmer a hint, how to do this.

@datenbrei @mattwr18 @alina-beck @ogerly It should be done in general in a timely manner as far I do understand. Just to make us aware …

**Comment by roschaefer** [comment]
@Hardy-Peaceglobal we discussed in a developer meeting that it would be easier to implement if all URLs could be [kebab-cased](https://kulturbanause.de/faq/was-ist-kebab-case/).

@Hardy-Peaceglobal would it be OK if all URLs get transformed into kebab-case before we search in the database for an organization?

http://human-connection.social/RubikonMagazin

would redirect to

http://human-connection.social/rubikon-magazin

**Comment by Hardy-Peaceglobal** [comment]
That‘s ok for me. 👌
