### ISSUE TITLE
🚀 [Feature] Limit search results to 15 per type

### ISSUE THREAD

**Issue by alina-beck** [Human-Connection/Human-Connection#2142]
## :rocket: Feature
In order to not overwhelm our users with search results we want to display only the top 15 search results of each type (`post`, `user`, later also `hashtag`) in the search dropdown.

### Implementation
Open question: should the search results be limited in the backend or frontend?

### Design & Layout
The size of the dropdown might have to be expanded, to make sure a user not only sees `posts` but also `users` in their search results without scrolling.

### Additional context
This is **Step 2** in our search implementation – see #2146.
**Step 1** is adding `users` to the list of search results: #1463 

We decided it should be `15` because at the moment there is no search results page and the dropdown is the only place where search results are listed. With the results page in place we can set this to a lower limit (e.g. `5`).

**Comment by mattwr18** [comment]
@alina-beck I think it would be quite simple to limit it with the graphql query, like we do with `Post` where we send `first` which later gets turned into `LIMIT $first` for the database query

**Comment by mattwr18** [comment]
At the moment, we are limiting the `Post` search results to 10
```
findPosts(query: String!, limit: Int = 10, filter: _PostFilter): [Post]!
    @cypher(
      statement: """
      CALL db.index.fulltext.queryNodes('full_text_search', $query)
      YIELD node as post, score
      MATCH (post)<-[:WROTE]-(user:User)
      WHERE score >= 0.2
      AND NOT user.deleted = true AND NOT user.disabled = true
      AND NOT post.deleted = true AND NOT post.disabled = true
      AND NOT user.id in COALESCE($filter.author_not.id_in, [])
      RETURN post
      LIMIT $limit
      """
    )
```

**Comment by alina-beck** [comment]
still relevant

**Comment by alina-beck** [comment]
not stale

**Comment by Mogge** [comment]
I would like to close this issue. The results for each category (post, user, hashtag) is limited to five. So there is a maximum of 15 results in the drop down in the current version.
