### ISSUE TITLE
🚀 [Feature] Filter search results by type

### ISSUE THREAD

**Issue by alina-beck** [Human-Connection/Human-Connection#2145]
## :rocket: Feature
blocked by #2144!

Users should be able to filter search results by type (`post`, `user` or `hashtag`).

### User Problem
Having all search results displayed on a single page can be overwhelming and unnecessary when
a user already knows they are interested in posts only.

### Implementation
Similar to the search results page filter on facebook: with clickable tabs on top of the page.
- By default the `all` tab should be selected and display all types of results.
- There should be tabs for `posts`, `users` and `hashtags` – by selecting one of them the displayed search results are limited to results of that type.
- Fetched search results should be cached in the frontend to enable quick navigation between the tabs – and avoid re-fetching of the same data.

### Design & Layout
Missing! The `tabs` on the user profile could be an inspiration:
<img width="712" alt="Screenshot 2019-11-06 at 17 52 08" src="https://user-images.githubusercontent.com/11694483/68308528-0cfe4c80-00be-11ea-971a-62b33528c712.png">

### Additional context
This is **Step 5** in our search implementation – see #2146.
**Step 1** is adding users to the list of search results: #1463.
**Step 2** is limiting the number of search results to 15: #2142.
**Step 3** is adding hashtags to the search results: #2143.
**Step 4** is displaying a page with all search results: #2144.

**Comment by alina-beck** [comment]
still relevant

**Comment by alina-beck** [comment]
not stale

**Comment by Mogge** [comment]
Query in the search field will search for when starting with
 - ! posts only
 - @ users only
 - \# hashtags only

On the search page, the frontend can use these prefixes to specify the task to the backend. Combinations should be possible (e.g. @\# searches for users and hashtags only)
