### ISSUE TITLE
🚀 [Feature] Refactor Http signature spec

### ISSUE THREAD

**Issue by martinneumann** [Human-Connection/Human-Connection#2149]
## :rocket: Feature

Refactor Http signature spec to use apollo server testing.

### User Problem

Allows test to run with mock server.

### Implementation

Implement using the apollo server testing library.

### Validation

All tests in file `src/activitypub/security/httpSignature.spec.js` pass.

**Comment by aonomike** [comment]
Turns out this was an issue with my node version, running the tests in node 11 solved the issue and the tests passed.
