### ISSUE TITLE
🐛 [Bug] console.error in Hashtag.spec.js 

### ISSUE THREAD

**Issue by mattwr18** [Human-Connection/Human-Connection#2161]
## :bug: Bugreport

We are getting this error in components/Hashtag/Hashtag.spec.js:
```
console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
      [Vue warn]: Unknown custom element: <nuxt-link> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
      
      found in
      
      ---> <HcHashtag>
             <Root>
```

### Steps to reproduce the behavior
1. Pull down the latest changes from `master`
2. from `/webapp` run `yarn test components/Hashtag/Hashtag.spec.js`
3. see error in console

### Expected behavior

We should not have runtime errors... please register `nuxt-link` properly in the test :point_up: 

Here is an example of how we have registered the component in the past https://github.com/Human-Connection/Human-Connection/blob/master/webapp/components/CommentList/CommentList.spec.js#L15

**Comment by Mozar10** [comment]
I added the fix for this, how should I contribute? just fork and PR?

**Comment by mattwr18** [comment]
please put in a `PR` to the repo directly! a fork will never pass our `Travis` build since we use encrypted env variables. see https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml for an explanation
