### ISSUE TITLE
🐛 [Bug] the user image should be included as a small thumbnail

### ISSUE THREAD

**Issue by ogerly** [Human-Connection/Human-Connection#2168]
## 🐛 :bug: Bugreport
  the user image should be included as a small thumbnail

![Bildschirmfoto von 2019-11-08 14-04-43](https://user-images.githubusercontent.com/1324583/68478733-ea407500-0230-11ea-906e-d5d475d2d13d.png)

user image can have any size. this delays the loading time and unnecessarily increases the data volume e.g. on mobile rooming devices.

a small thumbnail should be created when saving which can be used for user images. the original should still remain. 

i actually thought that this would happen when saving. greg showed me this once.  

on the .social there are very big pictures like 34x34 displayed but they are not calculated down. 

when saving the user image something should check that the image also saves as a small thumbnail and this is also only used in the display.

**Comment by ogerly** [comment]
https://github.com/Human-Connection/Human-Connection/issues/2255

**Comment by DennisHack** [comment]
Auch vielleicht mit Andrey absprechen? Das hängt zusammen, oder?

**Comment by AndreiBu** [comment]
yes i think this task should be included in my challenge - upload/image microservice
