### ISSUE TITLE
Refactor Lat/Lng to a Neo4J Point object

### ISSUE THREAD

**Issue by appinteractive** [Human-Connection/Human-Connection#218]
https://medium.com/neo4j/working-with-neo4j-date-and-spatial-types-in-a-react-js-app-5475b5042b50?source=safariShare-9d5b4130ae48-1551000065&_branch_match_id=632568347423648363

Saving lat/lng as a `point({latitude:33.329 , longitude:-111.978})` point object in the database.

**Comment by Mastercuber** [comment]
Could be useful for events, when a map is implemented

**Comment by mattwr18** [comment]
still relevant, I guess... maybe not a priority, for now
what do others think?
