### ISSUE TITLE
🐛 [Bug] Selected language is changed when editing a post

### ISSUE THREAD

**Issue by alina-beck** [Human-Connection/Human-Connection#2187]
## :bug: Bugreport
reported by @infinite-dao at the related issue #1467:

> Seeing the same on https://human-connection.social, I just want to add:
> 1. I had posted a news article with English language setting, it is saved as such
> 2. On reediting this article it displays in gray as @ulfgebhardt reported and the very first option is selected regardless that an English language setting was saved before

> So it needs also a selected check, wich language option has to be selected in relation to the previously saved post article language setting

### Steps to reproduce the behavior
1. Write a new post
2. Select a language _other than your selected locale_
3. Save the post
4. Edit the post
5. See the language setting changed to your _selected locale_

### Expected behavior
When I select a language for a post I expect it **not** to change automatically when editing the post. I still want to be able to manually change the language.

### Version & Environment
originally found on `production`, reproducible on `develop`

### Additional context
The `language select field` needs to be decoupled from the `locale setting`.

Question: Do we want to pre-select a language, based on the current `locale setting`  or should it be empty and the user forced to select a language manually? Can we make sure to _only_ set the language automatically when no language has been selected yet?

possibly related to #2119

**Comment by Mogge** [comment]
The language property was not fetched by the postFragment
