### ISSUE TITLE
Add creation date to follow and shout relation

### ISSUE THREAD

**Issue by appinteractive** [Human-Connection/Human-Connection#219]
We need to add a date to the shout and follow relationships to also maybe able to sort them.

**Comment by Tirokk** [comment]
@roschaefer @appinteractive @ulfgebhardt @mattwr18 
Is it not interesting since when I do follow somebody?

**Comment by KapilJ22** [comment]
@mattwr18, The issue has been resolved with the following PR:
https://github.com/Human-Connection/Human-Connection/pull/1853

**Comment by mattwr18** [comment]
yes, if you write `fixes #<issue_number>` in the `PR` description, the issue will get closed automagically when the `PR` is merged... we added it to the `PR` template for this reason. 
thanks again for working on it :)
