### ISSUE TITLE
Block activity for blocking users to interact with my content

### ISSUE THREAD

**Issue by Mastercuber** [Human-Connection/Human-Connection#222]
**Is your feature request related to a problem? Please describe.**
No, it's an extension of the available block funtionality.

**Describe the solution you'd like**
Implement the [Block activity](https://www.w3.org/TR/activitypub/#block-activity-outbox), so users can block other users. The blocked user should then not be able to interact with content of the user. This relates to the blacklist feature. Maybe @roschaefer can classify if the block logic can create a Block activity and send it via activityPub.

**Describe alternatives you've considered**

**Comment by datenbrei** [comment]
Closed in favour to #1054
