### ISSUE TITLE
🐛 [Bug] Misspelled “their” of profile::invites::description

### ISSUE THREAD

**Issue by infinite-dao** [Human-Connection/Human-Connection#2230]
## :bug: Bugreport
In there is a misspelled “thier” in https://github.com/Human-Connection/Human-Connection/blob/a0fe9cb94cb7d814b42dc46c48bdcd432e676e51/webapp/locales/en.json#L174 and also the “their” seems to refer to the very “somebody” in the title 
https://github.com/Human-Connection/Human-Connection/blob/a0fe9cb94cb7d814b42dc46c48bdcd432e676e51/webapp/locales/en.json#L173 
I wonder about the “their” but I learned that “their” referring to “somebody/someone” is just English (see https://forum.wordreference.com/threads/never-sit-on-someone-elses-blanket-without-their-permission.2245981/). In German is a discussion in [lokalise.com](https://lokalise.com/project/556252725c18dd752dd546.13222042/?view=single&reference_lang_id=640&single_lang_id=666) to term it more neutral, e.g. “Enter the e-mail address for invitation” or so. But we can leave it at “their” and just correct the misspelled word.

- Are there multiple e-mails to be inserted or just one?

**Comment by mattwr18** [comment]
Hey @infinite-dao, definitely a typo that can be fixed. Their, in English is a good gender neutral pronoun, so we'd like to keep it.
Thanks for spotting this!

**Comment by infinite-dao** [comment]
OK, right. And the answer to my final question? ;-)

**Comment by Mogge** [comment]
Please check also the German translation. It uses the term 'seine' meaning 'his' which may exclude female users.

**Comment by Mogge** [comment]
I also think we should have a consistent usage of the term URL. Sometimes it is in lowercase, sometime in uppercase.

**Comment by infinite-dao** [comment]
> Please check also the German translation. It uses the term 'seine' meaning 'his' which may exclude female users.

OK, exclude female users yes and no. Interesting maybe is the [German Youtube talk of „Dr. Tomas Kubelik: Wie Gendern unsere Sprache verhunzt“ (45min)](https://www.youtube.com/watch?v=Ri-kVYDTEAk) and I concur with Tomas Kubelik, that our German language uses “male” grammar, if you do not know the sex of a person, eg. „Die Polizei, Dein Freund und Helfer“ instead of „Die Polizei, Deine Freundin und Helferin“ ;-) 

Anyway I tend to translate the correct English “…enter their e-mail…” to German „…die E-Mail …“ Or as we will have a German title wiht something like „_Lade jemanden zu Human Connection ein_“ may be followed by
- „_Zur Einladung dessen E-Mail-Adresse eintragen_“ ?
- „_Zur Einladung gib jemandes E-Mail-Adresse ein_“ to reuse the Genetiv or so ;-)

**Comment by Mogge** [comment]
@infinite-dao I agree with what you are saying. Aber ich finde "gebe SEINE E-Mail Adresse ein" wirklich sehr maskulin. When I checked today I saw it already changed. Now in lokalize it is "Zur Einladung die E-Mail-Adresse hier eintragen.", which is fine. And thanx for the link, I will take a look at it.
