### ISSUE TITLE
🚀 [Feature] Comments 4-Times As Long Before Show More

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#2237]
## :rocket: Feature

The comments shall be 4-times as long in character amount before the `Show more` button appears.

### User Problem

@DennisHack (our product owner) says that the user to often has to click on `Show more` to see the full comment of someone.

### Implementation

Make the character count four times as high before the `show more` button appears.

### Design & Layout

- none

### Validation

- none

### Additional context

- none

**Comment by bocajnannerb** [comment]
Hi! I would like to work on this issue as my first time contributing to this project
