### ISSUE TITLE
🐛 [Bug] Wrong German Umlaut Handling in Editor

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#2238]
## :bug: Bugreport
The Editor component does not encode German umlauts in URLs correctly:
![umlauts](https://user-images.githubusercontent.com/13457963/68835468-72eb6500-06b8-11ea-94e9-5ae0943c8bcb.png)

Browsers decode encoded umlauts in the URL bar. This one:
~~~
https://www.dw.com/de/bundeswehr-benennt-kaserne-nach-ns-widerständler/a-51101207
~~~
gets
~~~
"https://www.dw.com/de/bundeswehr-benennt-kaserne-nach-ns-widerst%C3%A4ndler/a-51101207">
~~~

Umlauts are not allowed in URLs, but users don't know about this. So if they make use of these, the editor should correct this and encode the umlauts and other special characters.

### Steps to reproduce the behavior
1. Insert a link with a German Umlaut into the Editor
2. See the URL to be split or broken

### Expected behavior
The editor component should encode umlauts in URLs correctly

### Version & Environment
 Type: [Desktop]      
 - OS: [MacOS]      
 - Browser: [Firefox] 
 - Version [70]  
 - Device: [PC]  

### Additional context
This means, that even if a user inserts bad URLs with Umlauts the editor should fix this. Browsers encode umlauts in the URL bar, so should our editor handle this.

**Comment by yeltawil** [comment]
Hi! I am interested in handling this!

**Comment by tidus9** [comment]
I would like to add some links, which will seperated by special characters.


star in the middle of a link:
https://web.archive.org/web/*/https://www.zeit.de/politik/ausland/2019-04/julian-assange-journalismus-anklage-pressefreiheit-meinungsfreiheit

semicolon in the link:
https://www.ka-news.de/region/karlsruhe/Karlsruhe~/Monika-Seelmann-rettet-76-Baeume-in-Karlsruhe-doch-kann-das-Einheitsbuddeln-wirklich-dem-Klima-helfen;art6066,2437942

**Comment by tidus9** [comment]
> Hi! I am interested in handling this!

Would you like to do it? :)

**Comment by rbeer** [comment]
source: `pasteRule` expression in /webapp/components/Editor/nodes/LegacyEmbed.js
merge with #3395
