### ISSUE TITLE
🚀 [Feature] Show Language On Post Page

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#2239]
## :rocket: Feature

If you go directly on the posts page the language of the post should be seen there.

### User Problem

If no users can see the language the author has set for their post nobody is able to make the author aware to maybe correct this.

This makes informations in our network less reliable and is an additional reason for bad user experience.
If a user selects English language in the filter of the main page they will see mostly German posts with the wrong post language setting.
A very bad experience for english nativ speakers!

### Implementation

See create post page.

### Design & Layout

Just show the language of the post on its page here:

![Bildschirmfoto 2019-11-14 um 08 33 44](https://user-images.githubusercontent.com/25344101/68836117-e17cf280-06b9-11ea-9ab2-b7c2ba3e5b04.png)

Position like on the create post page:

![Bildschirmfoto 2019-11-14 um 08 33 19](https://user-images.githubusercontent.com/25344101/68836124-e6da3d00-06b9-11ea-87bd-df8c42af2f79.png)

### Validation

- none

### Additional context

- none

**Comment by Mozar10** [comment]
@Tirokk Can I take a look at this? 

As a native English speaker I had the exact experience you are referring to here. I double checked to make sure I had set the correct language settings on the main page.

**Comment by alina-beck** [comment]
@DennisHack requested we change the whole structure of the post – see issue #2363. This does not need to be solved in the same `PR`, I just think it's good to be aware of the direction we want to take with the post page.

I think the language does not need to be indicated exactly like on the `edit`/`create` post page, as it takes up a lot of space. A tag with the language code (`EN`, `DE` etc.) could be enough – then it can be placed next to the categories, maybe right aligned? Or what do you think @Mozar10, @Tirokk?

**Comment by Mozar10** [comment]
@alina-beck Thanks for providing direction, that was actually going to be my next question. Is this something like what you had in mind for the time being?
![fix](https://user-images.githubusercontent.com/20374324/69759862-0dc05680-1131-11ea-82db-ff9d049d11ae.png)

**Comment by alina-beck** [comment]
@Mozar10 yes, this is great! You could maybe use uppercase letters, like we have it for the language filters.

**Comment by Tirokk** [comment]
Hello @Mozar10 ,
I am back from holidays now.
Are you still interested in or already working on this issue?

**Comment by Mozar10** [comment]
Yes I have finished. I am just at work now, I can push it this weekend ? @Tirokk

**Comment by Tirokk** [comment]
Hey, wonderful @Mozar10 .

Please make a pull request directly on our master.
I see you should have permission to do so, you are a team member already …
