### ISSUE TITLE
🚀 [Feature] Order tags in tag cloud alphabetically

### ISSUE THREAD

**Issue by sushidave** [Human-Connection/Human-Connection#2244]
## :rocket: Feature

Order tags in the tag cloud in posts alphabetically.

### User Problem

The more tags there are in a cloud the harder it gets to find a tag.
![hc-tag-cloud-unsorted](https://user-images.githubusercontent.com/17728384/68905897-fbaee300-0742-11ea-8485-b9ed159e55b3.png)

### Implementation

Order them alphabetically.

**Comment by Mogge** [comment]
not stale

**Comment by DriesCruyskens** [comment]
I'll gladly help on this one if available. As I understand it, sorting tags in both index.vue and more-info.vue as well as a test function in index.spec.js should suffice?

**Comment by Tirokk** [comment]
Yes @DriesCruyskens , 🤗
I think that should be suffice!
I assigned you to this one. 💫

**Comment by sushidave** [comment]
@DriesCruyskens Thank you for your help 🙏
