### ISSUE TITLE
💬 [Question] News Feed Image Sizes Preset Possible?

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#2254]
## :speech_balloon: Question

 Is it possible to preset the image sizes in the news feed by a pixel size stored in the database?

- We would avoid all the jumpings and taking more and higher space by loading the images.

**Comment by alina-beck** [comment]
Just talked about this with @mattwr18 – he will check if it's possible to get the `imageHeight` and set it as a property on `Post`. If we get this working then, yes, we can use it to improve the layout calculation in the frontend and get rid of all the jumping!

It might even fix the scrolling issue Dennis reported on zoom:
<img width="732" alt="scrolling bug" src="https://user-images.githubusercontent.com/11694483/69048663-11f0c380-0a0f-11ea-84c8-56b60819f1b2.png">

**Comment by mattwr18** [comment]
closed in release 0.2.0
