### ISSUE TITLE
💬 [Question] Best practice with lokalise

### ISSUE THREAD

**Issue by Mogge** [Human-Connection/Human-Connection#2275]
I would like to set this option in the upload configuration of lokalise:
![grafik](https://user-images.githubusercontent.com/15882241/69089657-e25ead00-0a48-11ea-91ed-190e3b4a37f3.png)

The reason is, that obsolete keys stay in lokalise with an English translation "Empty" which is very confusing for the translators. So far I removed them manually but this is obviously no solution.

**Comment by Mogge** [comment]
![grafik](https://user-images.githubusercontent.com/15882241/69091190-11295300-0a4a-11ea-95df-6c8df9969e4a.png)

I changed the path here. So in future the files should change in the folder `locales`

**Comment by Mogge** [comment]
What is a reasonable interval for updating the locales? Once a week?

**Comment by Mogge** [comment]
It seems that lokalise is pulling in some way automatically. Every time this happens, the same obsolete keys appear although I chose clean up mode. I guess they are coming in from another language than English, so lokalise cannot identify them as obsolete. I suggest only to import the English json file, to verify my assumption.

**Comment by Mogge** [comment]
Looks like that this was the trick. Now after import no keys are obsolete.

**Comment by roschaefer** [comment]
@Mogge nice, well done! :+1: So are we supposed to remove all files and re-import from time to time?

**Comment by Mogge** [comment]
@roschaefer I do not think that we have to remove the files. The last PR by lokalise worked fine, and we can see the changes.
There is a possibilty to trigger the pull by a web hook:
https://docs.lokalise.com/en/articles/1684090-github
But this must be done from here, so I cannot try it.
Resume:
* the base file is `en.json`. It is the only file pulled by lokalise
* Set the option Clean Up to delete obsolete keys
* the push is triggered manually in lokalise. We have to observe what happens, when we push the English locale too.
* make sure that the file structure is set correctly as shown in the screenshot above.

Open questions:
* a way to find keys that are not used in the English locale.
