### ISSUE TITLE
🐛 [Bug] Browser support

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#2287]
## :bug: Bugreport
There are some browsers, like edge or older Safari browsers, which are not supported.

### Steps to reproduce the behavior
1. Try to login
2. See, that it does not work

### Expected behavior
Any browser should ether work or one should get a warning, that it is not supported - and what you could possibly do (take another browser)

### Version & Environment
- [x] support latest Edge version
- [ ] support IE from version .. ? No! ;-)

### Additional context
@datenbrei will add more specific information, which browsers have problems.

IE is currently failing on the login page because of missing `babel` settings in the styleguide. This could be fixed by either releasing a new version of the styleguide with updated settings or by completing the migration of the styleguide.

The implementation of the masonry layout is also not optimized for IE – this needs to be tested and might require a CSS fallback.

**Comment by alina-beck** [comment]
can always be improved – but at least login is working in all browsers now
