### ISSUE TITLE
🚀 [Feature] diaspora compatibility

### ISSUE THREAD

**Issue by jkmssoft** [Human-Connection/Human-Connection#2331]
## :rocket: Feature
Hello,
I don't know if human-connection has any chance against facebook?
So it would be great if it would be compatible to other social networks, like diaspora.

**Comment by proofy** [comment]
I understood it to mean that in general it is about an interface that allows exchange with other platforms. Diaspora has its own protocol and belongs here rather to the largest island solution. If @jkmssoft  specifically wants to support this protocol, I would make another feature request. 
A great overview can be found at https://the-federation.info/#protocols .
So here https://activitypub.rocks/ and ostatus lead. Unfortunately, Ostatus has recently lost its importance and many platforms, like GNU Social, that support this protocol are hardly developed any further. Perhaps also an opportunity for HC to fill out this notch. Maybe you could contact @pfefferle, who has a lot of experience in this area.
