### ISSUE TITLE
🚀 [Feature] Enlarge The ‚following' And 'followed by‘ Lists On User Profile

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#2336]
## :rocket: Feature

Several users demanded:
Enlarge the ‚following' and 'followed by‘ lists on user profile on click.

![Bildschirmfoto 2019-11-24 um 10 31 08](https://user-images.githubusercontent.com/25344101/69493098-b8731380-0eaa-11ea-8d09-d9651427a366.png)

### User Problem

I and other user like to see all who I do follow and all who do follow me.

### Implementation, Design & Layout

- Making the information text under the lists clickable and then show the whole list.
- Have a ’show less’ clickable text under the full list to make it short again. Like on the comments of posts.

### Validation

- none

### Additional context

- none

**Comment by DennisHack** [comment]
Hi @Tirokk, issue will be closed as we will remove the feature (Following is not meant to be public).

**Comment by mattwr18** [comment]
This was a duplicate issue, so maybe should stay closed and any new info here copy pasted into the existing issue.
Just because some users want this not to be public doesn't mean all user's agree. Shouldn't this be configurable by each user?

**Comment by Tirokk** [comment]
This should be configurable in my eyes. Yes! @mattwr18 

@DennisHack I would like to see whom all I do follow at least. So this will get privat but not removed?

**Comment by Tirokk** [comment]
This is a duplicate of issue #1741 .
