### ISSUE TITLE
[AP] Search a user on mastodon gives 503 error

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#234]
**Describe the bug**
We have the backend deployed which now should be able to return results for webfinger searches.

E.g. if I type in `https://nitro-staging.human-connection.org/api/.well-known/webfinger?resource=acct:bob-der-baumeister` into the URL I get:
```json
// 20190322110313
// https://nitro-staging.human-connection.org/api/.well-known/webfinger?resource=acct:bob-der-baumeister

{
  "subject": "acct:bob-der-baumeister@nitro-backend.human-connection",
  "links": [
    {
      "rel": "self",
      "type": "application/activity+json",
      "href": "https://nitro-backend.human-connection/users/bob-der-baumeister"
    }
  ]
}
```

However, if I search for this seeded user through Mastodon, I get a 503 HTTP error.

**To Reproduce**
1. Visit a mastodon instance
2. Click on "Search"
3. Type in `bob-der-baumeister@nitro-staging.human-connection.org/api/`
4. See 503 HTTP error

**Expected behavior**
I would expect to see the user "Bob der Baumeister" in the result set.

**Screenshots**
![2019-03-22-110425_1920x1080_scrot](https://user-images.githubusercontent.com/2110676/54815784-00de8f80-4c93-11e9-912b-756d900e3501.png)

**Comment by Mastercuber** [comment]
For any reason the TLD is missing.. The `hostname` attribute of the `URL` class is used to extract the whole domain. It's also missing when I try to fetch an Actor Object.
