### ISSUE TITLE
🐛 [Bug] Misleading description on "Delete your account"

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#2355]
## :bug: Bugreport

**German original**

> Habe das hier im Support bekommen:
> 
> "ich finde das Projekt spannend und interessant.
> Mir ist etwas in der deutschen Oberfläche aufgefallen, was verwirrend
> klingt.
> Unter Einstellungen gibt es einen Punkt "Daten löschen".
> Dort steht folgender Erklärungstext:
> 
> "Daten löschen
> Sei dir bewusst, dass deine Beiträge und Kommentare für unsere Community
> wichtig sind. Wenn du sie trotzdem löschen möchtest, musst du sie unten
> markieren."
> 
> Nun werden nach der Bestätigung allerdings nicht nur die Beiträge und
> Kommentare gelöscht, sondern das gesamte Benutzerkonto... was mir erst
> im nachhinein klar wurde ;)
> Es wäre bestimmt vorteilhaft, wenn das in dem Beschreibungstext erklärt
> würde."

> Das Thema hatte ich vor Wochen bereits angesprochen, wo es hieß, dass der Text wirklich relativ unklar ist und geändert werden müsste. Seitdem hat er sich leider nicht geändert. Ich würde das gerne noch einmal anregen.

**English translation via https://www.deepl.com/translator**

> Got this at support:
> 
> "I find the project exciting and interesting.
> I noticed something in the German surface, which is confusing.
> sounds.
> Under Settings there is an item "Delete data".
> There you will find the following explanatory text:
> 
> "Delete data
> Be aware that your contributions and comments for our Community
> are important.  If you want to delete them anyway, you have to do it below.
> "Mark."
> 
> After the confirmation, however, not only the contributions and
> Comments deleted, but the entire user account...  which first
> became clear afterwards ;)
> It would certainly be advantageous if the following were explained in the descriptive text
> "I would."
> 
> 
> I had already mentioned the subject weeks ago, when it was said that the text was really relatively unclear and would have to be amended.  Unfortunately, it has not changed since then.  I would like to suggest that once again.

### Steps to reproduce the behavior
1. Login at https://develop.human-connection.org/
2. Visit https://develop.human-connection.org/settings/delete-account
3. Read text
4. Be confused because it does not say that your account will be deleted

### Expected behavior
It should be clearly stated that deleting your account means deleting your accout. The question is whether you want your old posts be preserved (the author gets anonymized)

**Comment by Mogge** [comment]
@erhardtstiefel How are you going to work on the text files? The current workflow of the i18n is to do the changes in the English locale (`en.json`) and have all the other languages translated via lokalise.

**Comment by erhardtstiefel** [comment]
I mean 'Settings' is the wrong place for a feature as important as 'Delete account'. Maybe it should be one level up below 'Logout'. Also, the explicit deletion of data should not be suggested if this is not possible at all. I.e. here a redesign is necessary and not only some text changes.

**Comment by erhardtstiefel** [comment]
I can't 1. Login at at https://develop.human-connection.org/ and I can't 2. Visit https://develop.human-connection.org/settings/delete-account but I reproduced the bug with my local environment and found a solution. Now I need advice how to put the solution in a Pull Request.

**Comment by erhardtstiefel** [comment]
A good help to a better understanding of this issue can be found in the FAQ https://support.human-connection.org/kb/faq.php?id=83&lang=en_US and also in German https://support.human-connection.org/kb/faq.php?id=83&lang=de_DE
