### ISSUE TITLE
🐛 [Bug] Accounts with `@googlemail.com` address cannot sign in anymore

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#2364]
## :bug: Bugreport
So we used `validator.js` to normalize emails. Preferably to lowercase emails. But the normalization did more than we expected. It also turns `googlemail.com` addresses into `gmail.com` addresses.

This is not a problem for new accounts. But it is a problem with the old ones.

### Steps to reproduce the behavior
1. Travel in time (~1 month in the past) signup with a `@googlemail.com` address 
2. Wait until we deploy the email normalization
3. Try to sign in again
4. Authorization error :cry: 

We need to normalize the emails manually. So basically do sth. like:

```cypher
MATCH(e:EmailAddress) WHERE e.email ENDS WITH 'googlemail.com'
WHERE NOT exists(gmailAddress)
SET e.email = someRegex(e.email)
```

Make sure that we don't violate the unique constraint on `EmailAddress`. Some users worked around the problem by creating another user account. We could either skip the Email Address or we somehow merge the two user accounts (?).

### Expected behavior

Sign in should work just fine

### Additional context

```
neo4j> MATCH(e:EmailAddress) WHERE e.email ENDS WITH 'googlemail.com' RETURN COUNT(e.email);
+----------------+
| COUNT(e.email) |
+----------------+
| 295            |
+----------------+

1 row available after 51 ms, consumed after another 0 ms
```

**Comment by roschaefer** [comment]
Here's the statement that should fix most of the email addresses:

```cypher
MATCH(e:EmailAddress)
WHERE e.email ENDS WITH 'googlemail.com'
OPTIONAL MATCH(e2:EmailAddress)
WHERE e2.email = replace(e.email, 'googlemail.com', 'gmail.com')
WITH e, e2
WHERE e2 IS NULL
SET e.email = replace(e.email, 'googlemail.com', 'gmail.com')
;
```

Please **do not execute this statement without a backup**.

**Comment by mattwr18** [comment]
taking a `backup` now...
I'll restore it locally, then run the script, and let you know the results before doing it in `production`
