### ISSUE TITLE
🐛 [Bug] Merge duplicate user accounts and email addresses

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#2381]
## :bug: Bugreport

So we just changed 940 *unnormalized* email addresses (those gmail email addresses which had dots) into their normalized version. We had to skip 40 email addresses where the users already registered again with their email addresses. That created another user account with the normalized email.

So in the long term should merge those unnormalized and normalized email addresses into one node and also merge the user accounts that are connected to these email addresses. That would allow the 40 users to get the former posts back.

In the short term we should maybe notify those 40 users and tell them about this issue?

**Comment by mattwr18** [comment]
This is what I've come up with so far
```
MATCH (user:User) 
WHERE user.email = firstEmai.email 
OR user.email = normalizedEmail.email 
WITH collect(user) as nodes
CALL apoc.refactor.mergeNodes(nodes, {properties: {role: 'discard', coverImg: 'discard', avatar: 'discard', encryptedPassword: 'overwrite', createdAt: 'discard', deleted: 'overwrite', wasInvited: 'discard', name: 'discard', disabled: 'overwrite', id: 'discard', email: 'overwrite', slug: 'discard', updatedAt: 'overwrite'}}) 
YIELD node 
RETURN node;
```

We need:
1) a list of all the duplicate accounts and their emails
2) decide on wheter to `discard`, `overwrite` or `combine`
3) test it with production data locally
4) take a backup
5) run in production

Here is the documentation:
https://neo4j.com/docs/labs/apoc/current/graph-updates/graph-refactoring/merge-nodes/

**Comment by roschaefer** [comment]
Small typo `firstEmai.email` but this is pretty much exactly what I imagined. Well done!

I would like to use this as an opportunity to come up with some database migration procedure. Where should the migration happen? If we run it from the backend, we are in the Javascript world.

**Comment by mattwr18** [comment]
yeah, thanks for catching the typo, I actually had the emails as strings cause I just merged one, but didn't want to publish the person's email here...
Of course, it would be great to have a script that iterates and does this one at a time...
The backend doesn't have access to the neo4j-data-claim though...
I thought we would just use a script and do it from the `neo4j` pod

**Comment by mattwr18** [comment]
@roschaefer you alluded to some progress on this issue, no?
could you maybe update the issue, or is there a `WIP` PR?
