### ISSUE TITLE
🚀 [Feature] Badge for monthly donors in profile picture

### ISSUE THREAD

**Issue by proofy** [Human-Connection/Human-Connection#2383]
## :rocket: Feature
On the German side for the donation collection https://human-connection.org/spenden/monatliche-spende/ from "SCHNAPP DIR DIE ABZEICHEN! -> grab the badges. I would like to have these badges on my profile picture as well. In the first step it would be enough that you belong to the donors and you can see a small tree on the profile picture.

**Comment by datenbrei** [comment]
Hi @proofy , this once was switched on, but is disabled for now, because for displaying badges we also need the possibility to adminstrate them. The code exists, but till we can change wrong data, we decided to let it be switched off.
These issues are related: #1183 and #284

**Comment by proofy** [comment]
![icon_papierflieger_blue](https://user-images.githubusercontent.com/580891/70308519-bba3c300-180b-11ea-9ff8-7e36d21b9fff.png)
