### ISSUE TITLE
🐛 [Bug] Nitro Privacy Settings Page not Found

### ISSUE THREAD

**Issue by infinite-dao** [Human-Connection/Human-Connection#2387]
## :bug: Bugreport
Going to the privacy settings shows a page error: not found (tested 1st of December 2019)

### Steps to reproduce the behavior
1. Go to https://nitro-staging.human-connection.org/settings/settings/privacy
2. then comes: «This page could not be found. Back to the home page»

### Expected behavior
See the page of settings for privacy stuff

### Version & Environment
 Type: Desktop
 - OS: Linux, OpenSuse 42.3
 - Browser: opera, Version 63.0.3368.94

**Comment by mattwr18** [comment]
![Screenshot from 2019-12-03 21-02-56](https://user-images.githubusercontent.com/26943915/70085346-546def00-1610-11ea-9d8f-89e2845d5ba3.png)

**Comment by mattwr18** [comment]
I put in a `PR` here https://github.com/Human-Connection/Human-Connection/pull/2417
have a look if you can/want
