### ISSUE TITLE
🐛 [Bug] User-not-found-page not translated

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#2409]
## :bug: Bugreport
The page "User not found" is not yet translated.

![user](https://user-images.githubusercontent.com/13457963/70033753-60c25f80-15b0-11ea-9a47-70999235d222.png)

### Steps to reproduce the behavior
1. Call a user profile which had been deleted

### Expected behavior
The Page should
1. Be translated
2. Explain, why this page comes up. For example: "The user deleted his own account".

### Version & Environment
any

**Comment by cluzier** [comment]
Can you please assign this bug to me?

**Comment by erhardtstiefel** [comment]
I'm interested in the solution of @cluzier and would like to participate mabey as reviewer

**Comment by erhardtstiefel** [comment]
Trying  to reproduce the behaviour called the profil of an UNAVAILABLE user and got this
![bug2409](https://user-images.githubusercontent.com/49943365/71682850-2a375a80-2d91-11ea-98cd-b25f5a865807.png)

**Comment by erhardtstiefel** [comment]
Trying a 2nd time to reproduce the behaviour I called the profile of the deleted user and I got this
![bug2409_2](https://user-images.githubusercontent.com/49943365/71683515-1260d600-2d93-11ea-9c62-48831c6d63aa.png)
So in my opinion it seems like the bug is not reproducible

**Comment by erhardtstiefel** [comment]
Maybe the behaviour is different when a user does dlete his contributions and/or comments. Il try to get another user to delete his account and his data simultaneously.

**Comment by erhardtstiefel** [comment]
How can I call a user profile which had been deleted? Please give more info.

**Comment by erhardtstiefel** [comment]
> 
> ## 🐛 Bugreport
> 
> The page "User not found" is not yet translated.
> 
> ![user](https://user-images.githubusercontent.com/13457963/70033753-60c25f80-15b0-11ea-9a47-70999235d222.png)
> ### Steps to reproduce the behavior
> 
>     1. Call a user profile which had been deleted
> 
> 
> ### Expected behavior
> 
> The Page should
> 
>     1. Be translated
> 
>     2. Explain, why this page comes up. For example: "The user deleted his own account".
> 
> 
> ### Version & Environment
> 
> any
> ### Additional context

How can I call a user profile which had been deleted? Please give more info.

**Comment by Mogge** [comment]
@erhardtstiefel May be we could work together on this?

**Comment by Mogge** [comment]
@datenbrei Can I work on this one?

**Comment by erhardtstiefel** [comment]
Ok, go ahead Moriz. I'm busy today and tomorrow, but keep me informed if you are finished with it before friday.
