### ISSUE TITLE
🚀 [Feature] Collect performance analysis data

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#2411]
## :rocket: Feature

It's always difficult to say "improve performance on X" because we never know when this issue is finished. There is always something to improve on performance.

That's why I would like to set the goal of this issue to: "Collect performance analysis data" on our kubernetes cluster, because we just don't know how long a request takes time in our webapp, backend and database pods respectively.

### User Problem
We have non-deterministic performance problem on the network right now. It's difficult to know what causes the performance issues. Certainly it's even more difficult if we don't have any statistical data on performance.

### Implementation
Hard to tell.

### Validation
A goal could be to get sth. like a [flame graph](http://www.brendangregg.com/flamegraphs.html) on our kubernetes cluster.

**Comment by mattwr18** [comment]
I would like to take some steps forward on this... here I found some docs about `Tools for Monitoring Resources` https://kubernetes.io/docs/tasks/debug-application-cluster/resource-usage-monitoring/
I like this line `"Prometheus, a CNCF project, can natively monitor Kubernetes, nodes, and Prometheus itself."`

It is the second place, I have seen `Prometheus` recommended for monitoring, as the Neo4j docs also suggest it.
https://neo4j.com/docs/operations-manual/current/monitoring/metrics/expose/#metrics-prometheus

I found this tutorial on how to set it up as a separate service/deployment and am going to give it a go on the `develop` server.

**Comment by mattwr18** [comment]
I was able to get `Prometheus` set up for `staging`, but haven't set up additional config yet...
I wonder if this is the type of performance analysis meant by this issue though... 
![Screenshot from 2020-01-14 15-35-21.png](https://images.zenhubusercontent.com/5ac663b44b5806bc2bcdd1d7/62191c2e-3385-4306-9940-5c68d7932ac6)

**Comment by datenbrei** [comment]
Grafana and Prometheus will be set up for production. We then have to learn how to interpret the data.
