### ISSUE TITLE
🐛 [Refactor] Favor Transaction Function over Auto-commit transactions

### ISSUE THREAD

**Issue by mattwr18** [Human-Connection/Human-Connection#2412]
## :zap: Refactor

Related to https://github.com/Human-Connection/Human-Connection/pull/2402

We have been receiving this error message in production `no available threads to serve it at the moment.` on our `neo4j` pod

There is an open issue on `neo4j` GitHub page https://github.com/neo4j/neo4j/issues/12014
where they talk about different causes, one of which is leaky `transactions/statements`.

Currently, we are using mostly `Auto-commit transactions`, which the `Neo4j` docs say, `"It is not recommended to use auto-commit transactions in production environments or when performance or resilience are a primary concern."`. Please see, https://neo4j.com/docs/driver-manual/1.7/sessions-transactions/#driver-transactions-auto-commit.

We should refactor the backend to use `Transaction functions`. See, https://neo4j.com/docs/driver-manual/1.7/sessions-transactions/#driver-transactions-transaction-functions

**Comment by Tirokk** [comment]
Very good you find this out @mattwr18 🤗🙏🏼
