### ISSUE TITLE
🚀 [Feature] Set up Metrics for Neo4j

### ISSUE THREAD

**Issue by mattwr18** [Human-Connection/Human-Connection#2413]
## :rocket: Feature

Since we have the enterprise edition of `Neo4j`, we should take advantage of the ability to set up `Metrics` and monitor performance https://neo4j.com/docs/operations-manual/current/monitoring/metrics/
Related to https://github.com/Human-Connection/Human-Connection/issues/2411
### User Problem

We have performance issues, but we don't know why or what we can do to improve them incrementally.
### Implementation

follow the advice on the `Neo4j` docs
We should decide if we want to use [Graphite](https://graphiteapp.org/), [Prometheus](https://prometheus.io/), or `CSV` files are adequate.
### Validation

Once we have some metrics coming in, we can see what the best way to evaluate them to identify specific ways to incrementally improve our `backend/database` performance.

**Comment by mattwr18** [comment]
Metrics are already enabled in production, they are written to `CSV` anyone @Human-Connection/hc-dev-team think we should set up `Graphite` or `Prometheus`?? @datenbrei ??

**Comment by Tirokk** [comment]
I can not say something about this …

**Comment by Tirokk** [comment]
Still for the future …

**Comment by mattwr18** [comment]
Metrics are already enabled @Tirokk 
I have a command I can share with you to copy them to your encrypted HD
