### ISSUE TITLE
🐛 [Bug] Develop server is down

### ISSUE THREAD

**Issue by mattwr18** [Human-Connection/Human-Connection#2429]
## :bug: Bugreport

At the moment, our develop server is down and won't pull down the latest images.
We are getting this error,
`Failed to pull image "humanconnection/nitro-web:latest": rpc error: code = Unknown desc = failed to register layer: Error processing tar file(exit status 1): open /usr/local/share/.cache/yarn/v6/npm-@babel-runtime-corejs2-7.5.5-c3214c08ef20341af4187f1c9fbdc357fbec96b2-integrity/node_modules/@babel/runtime-corejs2/helpers/esm/arrayWithHoles.js: no space left on device
`

You can see this by running `kubectl -n human-connection <pod_id>`

It is reporting there is no space left on device, but why and what can we do about it?

**Comment by mattwr18** [comment]
I was able to `ssh` into the backend on `nitro-staging` and this is what the size of the directories :point_up_2: look like 
```
439.9M	.cache/yarn/v6
439.9M	.cache/yarn
439.9M	.cache/
```

**Comment by roschaefer** [comment]
I think figured it out.
