### ISSUE TITLE
🐛 [Bug] Missing chance for italian Users to delete Data before deleting account

### ISSUE THREAD

**Issue by erhardtstiefel** [Human-Connection/Human-Connection#2495]
## :bug: Bugreport
The italian Users have no chance to delete their posts and/or comments when deleting their account

### Steps to reproduce the behavior
1. Switch language to Italiano
2. Select User > Impostazioni > Cancellare laccount utente 
3. See that the checkboxes for data deletion are missing

### Expected behavior
there should be checkboxes like in other languages e.g, English

### Additional context
Solution:
These two lines have to be added to the function deleteUserAccount in webapp/locales/it.json
            "contributionsCount": "Cancellare i miei {count} messaggi",
            "commentedCount": "Cancella i miei {count} commenti",

**Comment by sushidave** [comment]
Duplicate of #3498
