### ISSUE TITLE
🚀 [Feature] Set up some reporting on mail delivery

### ISSUE THREAD

**Issue by mattwr18** [Human-Connection/Human-Connection#2501]
## :rocket: Feature

Set up some reporting on our mail delivery
### User Problem

We currently have an issue with users reporting they do not receive emails when they request password resets, for example. It is difficult for us to debug what is happening.
### Implementation

We are using https://github.com/nodemailer/nodemailer for our mail deliver, and we can set up some logging or delivery status notifications, so we can potentially see when there are errors.
See https://nodemailer.com/smtp/dsn/

### Validation

A reduction in users writing support with reports of unreceived emails would be a great outcome.
Seeing some errors reported would be good as well because it would give us more data to try to discover the cause of the bug.

**Comment by sushidave** [comment]
Still needed
