### ISSUE TITLE
🐛 [Bug] spelling mistake: "Kommentar Gesendet"

### ISSUE THREAD

**Issue by tidus9** [Human-Connection/Human-Connection#2528]
## :bug: Bugreport
If you publish your comment, you get the message "Kommentar Gesendet".

Correct is "Kommentar gesendet".

![image](https://user-images.githubusercontent.com/51242288/70900816-e0f9b380-1ff9-11ea-9ebd-b975daf6d376.png)

**Comment by Mogge** [comment]
@tidus9 Thank you for the report. Please check this link:
https://lokalise.com/public/556252725c18dd752dd546.13222042/
This is where we translate from English to other languages. Please take a look at it. I am sure you can contribute a lot to improve for example the German expressions.

**Comment by tidus9** [comment]
>  I am sure you can contribute a lot to improve for example the German expressions.

I tried, but there are only two strings with the word "gesendet" and they are correct.

**Comment by Mogge** [comment]
@tidus9 I was searching for "Kommentar" and found it.

**Comment by tidus9** [comment]
I found it too when I click on "Kommentar gesendet". Then I see "Kommentar Gesendet" as a second suggestion for the translation. But when I try it on the platform, it still shows me the version with the capital letter...
