### ISSUE TITLE
Cache npm dependencies on Travis CI

### ISSUE THREAD

**Issue by appinteractive** [Human-Connection/Human-Connection#255]
Currently yarn always downloads all dependencies. Let’s find a way to use Travis yarn cache inside docker. Maybe it’s possible to mount the cache in the build dockerfile?

**Comment by Mastercuber** [comment]
@appinteractive I renamed this issue to a more general topic.

Now we have a build time nearly 20 minutes. We should use all caching mechanisms we find. 
I know there is a caching mechanism in travis https://docs.travis-ci.com/user/caching/.

We could compose the `cache:` property of the `travis.yml` as follows for the [yarn](https://docs.travis-ci.com/user/caching/#yarn-cache) and [directory](https://docs.travis-ci.com/user/caching/#cache-rvm-ruby-version-for-non-ruby-projects) caching:
```yaml
cache:
  yarn: true
  directories:
    - /home/travis/<dir-name>
```

**Comment by appinteractive** [comment]
@Mastercuber the question is how to use it in conjunction with our docker build. We need to mount the cache somehow into the build image.

**Comment by Mastercuber** [comment]
@appinteractive isn't it possible to cache a directory and mount this with the `volumes` keyword when building the image with travis?

**Comment by mattwr18** [comment]
I think this could still be relevant, what do you think @roschaefer 
not sure if it makes a difference we are using `docker` images in our build process
