### ISSUE TITLE
🐛 [Bug] English Not Fully Translated: 'languageSelectLabel'

### ISSUE THREAD

**Issue by ogerly** [Human-Connection/Human-Connection#2583]
In the english version it is named:
`"languageSelectLabel": "Language of your contribution“`

In german that would be:
"languageSelectLabel": „Sprache deines Beitrags“

I would like to change this, because a lot of people seem to think this is as well the language of the web app and not of the post.

_Originally posted by @Tirokk in https://github.com/Human-Connection/Human-Connection/pull/2351_

**Comment by Tirokk** [comment]
Wonderful @ogerly 
Thanks !!! 🤗

**Comment by Tirokk** [comment]
Is this still valid @ogerly @mattwr18 ?

**Comment by erhardtstiefel** [comment]
Alex, I'm confused. Why is it so a big problem just to change an expression. Or is it a variable or procedure name and nobody knows what happens if it will be changed? Why is this system so complicated? I tried to help but I'm disappointed and guess I'll never understand. Sorry.

**Comment by Tirokk** [comment]
Was this not already changed @ogerly ?
I don’t see the problem like it is now.

What you think is a better label name in german or english? In case.

**Comment by Tirokk** [comment]
I think it's solved
