### ISSUE TITLE
User description: no line/word wrapping

### ISSUE THREAD

**Issue by bad-gateway** [Human-Connection/Human-Connection#259]
**Describe the bug**
css issues, word wrapping, line wrapping in user description

**To Reproduce**
1. https://nitro-master.human-connection.org/profile/sepp
2. when you see it, you'll shit bricks

**Expected behavior**
line wrapping or useful limitations (120-400 characters)

**Screenshots**
![image](https://user-images.githubusercontent.com/48162069/53687882-d3a95c00-3d3a-11e9-8dd3-0b975c10db4e.png)

![image](https://user-images.githubusercontent.com/1238238/59601719-2bf74480-9105-11e9-8362-0b0e1611a722.png)
https://nitro-production.human-connection.org/post/5d001d1dcbac47002b175fc0/britanskaya_kolumbiyadiscoverygroup

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Edge, Firefox, Chrome ..

**Smartphone (please complete the following information):**
same

**Comment by roschaefer** [comment]
Nice catch! @bad-gateway
