### ISSUE TITLE
Add form to write a comment

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#260]
In order to write a comment, we need a `<comment-form>` component in the frontend. This comment form should create or update a comment, send it via `apollo` to the backend and update the UI.

![Screenshot (64).png](https://images.zenhubusercontent.com/57a4768be40e5714b16cfc65/28498c16-a6a9-4518-a0de-7993f1a1a461)

**Comment by Mastercuber** [comment]
In the Nitro version the creation of comments and replies to comments is not implemented yet.

**Comment by ulfgebhardt** [comment]
Use the Editor Component
