### ISSUE TITLE
📖 [Story] Enable advertising fees

### ISSUE THREAD

**Issue by proofy** [Human-Connection/Human-Connection#2601]
https://github.com/proofy/Human-Connection/issues/1

**Comment by proofy** [comment]
#https://github.com/proofy/Human-Connection/issues/1

**Comment by sushidave** [comment]
Hello @proofy, Verein Menschheitsfamilie & busFaktor() reviewed this issue. At the moment, it does not seem possible for the network of HC that is purely non-profit. However, it could be relevant in the future for other networks using this code.
