### ISSUE TITLE
🐛 [Bug] Following counter on all user profile pages shows "0"

### ISSUE THREAD

**Issue by sushidave** [Human-Connection/Human-Connection#2603]
## :bug: Bugreport

The following counter on all profile pages shows "0" people following.

![hc-bug-following-zero-users](https://user-images.githubusercontent.com/17728384/71281689-d3785c80-235e-11ea-8187-62e8c2ca6ebd.png)

### Steps to reproduce the behavior
1. Log into the network.
2. View your own profile page or the profile page of any other user.
3. The followers counter is correct but the following counter shows "0".

### Expected behavior

The following counter should show the number of following users.

### Version & Environment
 Type: []       Desktop
 - OS: []       MacOS
 - Browser: []  Firefox
 - Version []   71.0
 - Device: []   MacBook

### Additional context

HC version 0.2.0

**Comment by Mogge** [comment]
@sushidave Thank you for the report. The bug will be fixed in the next deploy.
