### ISSUE TITLE
🐛 [Bug] Horizontal shift of the site on mouseover or dropdown menu

### ISSUE THREAD

**Issue by Oubi44** [Human-Connection/Human-Connection#2607]
## :bug: Bugreport

We have a horizontal shift if you mouseover a username or if you click a dropdown menu!

![output](https://user-images.githubusercontent.com/56165041/71309994-d468c700-240e-11ea-8cf0-2cd2e89ab62f.gif)

### Expected behavior
To have no shift!

### Version & Environment
 Type: Desktop
 - OS:      Linux Mint
 - Browser: opera, firefox & chromium

### Additional context
This is this my first Bugreport! Is this new issue ok?

**Comment by roschaefer** [comment]
Excellent bug report, thanks :+1: I guess this is related to #2564 ? And a user @leternoz has tried to fix it in #2048 but added some unwanted side effect by accident.

@Oubi44 are you up to fix this bug which apparently annoys a number of people?

**Comment by Oubi44** [comment]
@roschaefer Sorry but i am not a programmer...

**Comment by DennisHack** [comment]
@alina-beck Good issue for you?

**Comment by alina-beck** [comment]
Hehe, maybe – but I'm very busy this sprint, so let's see if someone else wants to take it and otherwise assign it during our `planning` meeting next Tuesday. :wink:

**Comment by rbeer** [comment]
https://github.com/rbeer/Human-Connection/tree/fix/%232607 proposes a fix by setting `padding-right`, whenever `.dropdown-open` is added. Differences of the width of the scrollbar bar, across browsers/platform is accounted for, as the `padding-right` value is calculated; although it seems a bit expensive to do that on each component _render_(?). 

I saw the other day that PRs from a fork are not the preferred way, so I'll refrain from opening one, for now. Let me know how to go about this! :)

https://streamable.com/cz63p - Showcasing the change in Chrome.
