### ISSUE TITLE
User profile: Contact information

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#263]
```
As a user
I'd like to add contact information to my user profile (e.g. email, phone number)
In order to allow other users to reach me via public communication channels outside the network
```

**Comment by sushidave** [comment]
@appinteractive Sorry to bother you. I have difficulties in finding the feature request which is about the "about me" and "user location fields". Issue #9 that has been mentioned above refers to something else now. Has this feature been lost in action or can you guide me to the correct one?
