### ISSUE TITLE
💬 [Question] Do We Have Double Categories On Posts?

### ISSUE THREAD

**Issue by erhardtstiefel** [Human-Connection/Human-Connection#2658]
![too many categories](https://user-images.githubusercontent.com/49943365/71714989-2860ac00-2e10-11ea-8d73-46e6a26ff958.png)
Why do I see so many categories in my frontend webapp? What can I do to get rid of them. Is it a bug in the feed data?
Beside  this: When I write a contribution and try to save it then this is shown
![maximumcallstacksize](https://user-images.githubusercontent.com/49943365/71715148-b046b600-2e10-11ea-847a-30697d629a95.png)
What does it mean?

**Comment by sushidave** [comment]
@erhardtstiefel We could not reproduce this error. Please reopen the issue if it's still valid. Thank you.

**Comment by erhardtstiefel** [comment]
I saw this never again.
