### ISSUE TITLE
Report & Hide User Content

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#270]
**Is your feature request related to a problem? Please describe.**
It might happen that if the social network goes public, that we receive troll content or even illegal content. If we are not able to hide this content we might get sued.

**Describe the solution you'd like**
For every moderator there should a button on every user contribution to hide it.

![download](https://user-images.githubusercontent.com/2110676/47382386-7bb27700-d702-11e8-9071-4dc3549839e1.png)

**Comment by mattwr18** [comment]
closing this @roschaefer as we already have the ability for our moderators to `disable` content, which hides it from everyone that is not a `moderator` or `admin`
if I've misunderstood, please re-open
