### ISSUE TITLE
Disable all user content at once

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#271]
```gherkin
As a moderator
I'd like to disable all content of a user, ie. every post and every comment etc.
In order to save time if I have to fight a spamming bot or a user abusing the network on a great scale.
```

**Comment by mattwr18** [comment]
Closing this since the `moderators` have the ability to `disable` a `User`... I can't think of any reason why we would want to disable all content by a user, but allow them to continue to create content...
do we want to have read-only users? 
Can be reopened if I've misunderstood
