### ISSUE TITLE
🐛 [Bug] If you click the text inside an embed, the text disappears

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#2727]
## :bug: Bugreport

![Human Connection - Human Connection - Edited](https://user-images.githubusercontent.com/2110676/72225814-0a224b00-358a-11ea-8b46-a2d7f331cf11.gif)

### Steps to reproduce the behavior
1. Visit https://develop.human-connection.org/post/create
2. Paste in a link like https://www.youtube.com/watch?v=kDLg8oEWFYY&feature=youtu.be
3. Click on the text
4. Text suddenly not visible anymore

### Expected behavior
If you click on the text nothing should happen.

### Version & Environment
Chromium 79.0.3945.117 Arch Linux
Mozilla Firefox 72.0.1

**Comment by sushidave** [comment]
Same on Firefox 72.0.1 on a MacBook.

It also happens if clicking:
- outside the embed box 
- within the embed box anywhere below the preview image, except on the link
