### ISSUE TITLE
Locking users

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#274]
As a network responsible I'd like to have a dashbord to get an overview about a user's profile and his actions in order to be able to lock a user's account and to prevent generation of abusive content, if needed.

**Comment by mattwr18** [comment]
I think this needs clarification as well... I'll close as we already have a way of `locking` users... by a moderator disabling them... how is this issue different from that
If it needs to be re-opened please give more information on how this differs from the current work flow
