### ISSUE TITLE
🚀 [Feature] terms of use extend point - no parties 

### ISSUE THREAD

**Issue by ogerly** [Human-Connection/Human-Connection#2750]
## :rocket: Feature
terms of use extend point - no parties 

it concerns only party in the political sense. 

no organizations

**Comment by tidus9** [comment]
German text: Nutzerkonten von politischen Parteien oder offizielle Nutzerkonten eines politischen Vertreters sind unzulässig.

English Text: User accounts of political parties or official user accounts of a political representative are not permitted.

**Comment by DennisHack** [comment]
Political Parties / Politische Parteien

**Comment by DennisHack** [comment]
(TITLE) within terms of use

**Comment by ogerly** [comment]
which text should now be inserted exactly where ? 

![FireShot Capture 315 - Human Connection - Human Connection - human-connection social](https://user-images.githubusercontent.com/1324583/74008897-5fcbf680-4982-11ea-8305-06a4852f7d9a.png)

**Comment by tidus9** [comment]
https://human-connection.social/terms-and-conditions

It could stand between 7 and 8.

> which text should now be inserted exactly where ?
> 
> ![FireShot Capture 315 - Human Connection - Human Connection - human-connection social]

https://human-connection.social/terms-and-conditions

It could stand between 7 and 8.
