### ISSUE TITLE
🚀 [Feature] Blacklist Users

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#279]
## :rocket: Feature

~~~ gherkin
As a network User 
I'd like to filter out content of other users 
in order to better concentrate on the content I really search for.
~~~
This is deciding, **what I'd like to see**.
This is different from blocking users: Deciding, what the other user can't do anymore.
This is part of the blacklist (filter users, categories and for terms).
This is agreed with Dennis on 2019-09-23.

**Details of blacklisting Users**
- [ ] I don't see his articles anymore
- [ ] I see his comments on articles blurred
- [ ] I don't see his contributions in my search results

- [ ] Optionally ask, if a user should also be blocked

### Design & Layout

![blacklist](https://user-images.githubusercontent.com/13457963/65607711-44e97e80-dfad-11e9-99d4-fe4ca672a49b.png)

### Additional context

Later there should be multiple blacklists which can be shared. 

Also there will be a "family friendly"/ "Ponyhof" blacklist which is trimmed for new users so the don't get offended when entering the network

**Comment by mattwr18** [comment]
re-opening this issue as we have kind of already implemented this, but have called it `BLOCKED`
