### ISSUE TITLE
Private Messaging 

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#282]
As a user I'd like to chat securely and confidentially with other people to share potentially sensitive information.

**Comment by mattwr18** [comment]
This needs clarification... this is the third issue I've seen today that could be considered `chat` feature
But `private messaging` could also mean that I wan to be able to send a `DM` direct message to someone, no?
The main difference being that chat would involve `websockets`, whereas `DM`ing might not(?)
