### ISSUE TITLE
🚀 [Feature] Access all notifications via 🔔 icon when there are 0 unread

### ISSUE THREAD

**Issue by sushidave** [Human-Connection/Human-Connection#2823]
## :rocket: Feature

Currently, if all notifications are read and the counter shows "0" there is no link to the notifications page. Users can only access that page by entering https://human-connection.org/notifications into the address field of the browser. But usually they don't know this address.

### User Problem

This feature enables users to access the notifications page at anytime.

### Implementation

- [ ] Add a link to the "0" counter. Onclick opens the existing dropdown list.
- [ ] Show "No new notifications" on the dropdown list, plus the existing link to the notifications page.

### Design & Layout

![hc-feature-request-permanent-access-to-notifications-page](https://user-images.githubusercontent.com/17728384/72612572-75bf3c00-392d-11ea-90dd-3d63b62aaa10.png)

**Comment by alina-beck** [comment]
We already have this feature in the `Avatar Menu`:
<img width="220" alt="Screenshot 2020-02-10 at 12 21 42" src="https://user-images.githubusercontent.com/11694483/74145832-0bce4580-4c00-11ea-9da8-2fa6885f3fb8.png">

**Comment by sushidave** [comment]
@alina-beck Thanks for your info.
As a user I am used to access notifications through the notifications icon. Imho, that way of accessing the notifications page would be more intiutive. What do you think?

**Comment by alina-beck** [comment]
Fair enough, I think it could be more intuitive to allow users to click the :bell: icon when there are no unread notifications, to go directly to the `all notifications` page.

Technically we could implement this by checking if there are unread notifications and if not, display an optically identical link instead of the notifications menu button

**Comment by sushidave** [comment]
@alina-beck Thank you Alina. To me as a user it feels inconsistent if it in some cases it shows a popup menu and in others it leads to the notifications page. Currently, I don't know a better solution than the one I mentioned.

**Comment by Tirokk** [comment]
Is merged

**Comment by Tirokk** [comment]
Is merged
