### ISSUE TITLE
Display dimensions of target image on profile page

### ISSUE THREAD

**Issue by oliverzet** [Human-Connection/Human-Connection#283]
At the moment it is very hard to fit an image on the profile page to my liking, because it is unclear which dimensions the target image has and therefore it is likely going to be cropped randomly by the system.

To avoid a random cropping done by the system, it would be very helpful if the dimensions (width and height) of the target image were displayed within the image placeholder on mouse over.

Alternatively it might be preferable for the user to display a preview of the cropped target image, and make it adjustable, so the user can fit it to its liking.
![hc feature request profile image](https://user-images.githubusercontent.com/45514309/49332844-c900ee80-f5b4-11e8-9797-d752de16ee25.png)

**Comment by mattwr18** [comment]
really nice to read this discussion a year after this ticket was opened... should definitely be kept in mind when implementing profile header images...
blocked by https://github.com/Human-Connection/Human-Connection/issues/397
