### ISSUE TITLE
Badge Selection

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#284]
As a user
I'd like to choose from a list of available badges which badges to show or not to show
in order to control, which of my private information (like badges for specific donations) is shown to the public. The default should be not to show a badge, as long not explicitly enabled.

**Comment by mattwr18** [comment]
should this be closed in favor of https://github.com/Human-Connection/Human-Connection/issues/1183
or is it better to keep it open since it's smaller and maybe easier to implement on its own? @datenbrei anything change about the motivation for this?
