### ISSUE TITLE
Optimize and unify mobile navigation

### ISSUE THREAD

**Issue by appinteractive** [Human-Connection/Human-Connection#292]
**Is your feature request related to a problem? Please describe.**
Currently the navigation (main and sub) are a bit broken on mobile.

<img width="426" alt="Broken-Mobile-Navigation" src="https://user-images.githubusercontent.com/432828/53742065-12a0f400-3e98-11e9-8b73-9b0180b8b812.png">

**Describe the solution you'd like**
Optimize our current Navigation for Mobile use and find a way to display sub navigation in a prominent position so that it is not overlooked on mobile. (floating button?)

**Additional context**
We should taka a look into the navigation component in the styleguide and optimize it as needed.

**Some inspiration** 
I really like the approach that apple is using:

![Apples-Approach](https://user-images.githubusercontent.com/432828/53742462-efc30f80-3e98-11e9-99e1-03352ce7e355.gif)

**Comment by mattwr18** [comment]
@alina-beck you wanted to improve this after the migration maybe?
should we leave this open?

**Comment by alina-beck** [comment]
I want to give the `header` a makeover, yes! 😍 

I first thought `sub navigation` referred to the `side bar`, which is too big on mobile and should probably be collapsed as well. But after reading it again I think it's probably about the dropdown menus? Then we could even open another issue for the `side bar` to figure out how to improve that one. :wink:

**Comment by alina-beck** [comment]
has been improved (a bit) in PR #2582
