### ISSUE TITLE
Refactoring: Prefix URLs pointing to the backend

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#296]
**Describe the bug**
The server side rendered frontend serves our images at `/api/uploads`. All requests to `/api` are proxied to the backend, which serves images at `/uploads/`. Right now, the backend mutates all URLs in the response to be prefixed with `/api`. This is a design flaw as the backend *knows* how the frontend proxies requests.

**Expected behavior**
We should prefix all `<img src="URL">` urls **in the frontend** with `/api` so the backend does not need to do it for the frontend.

**Screenshots**
![2019-02-05-094935_1920x1080_scrot](https://user-images.githubusercontent.com/2110676/52262117-ccee1b80-292b-11e9-9c4d-adfc3ac01c60.png)

**Comment by aonomike** [comment]
```<img title="indiegogo_en_turtle" src="/img/badges/indiegogo_en_turtle.svg" class="hc-badge">```
@roschaefer @appinteractive we looked at the badges and they are not being loaded from the uploads folder. All the badges are in `webapp/static/img/badges` and the backend does not seem to be involved.

**Comment by aonomike** [comment]
<img width="1440" alt="Screen Shot 2019-04-04 at 7 25 51 PM" src="https://user-images.githubusercontent.com/1543546/55572131-9ce6ad00-570f-11e9-9314-9380cfce2512.png">
Other images come from amazon and there is no `/uploads` directory seen

**Comment by tansaku** [comment]
@roschaefer @appinteractive looked at this together with @aonomike  - we can see the `backend/src/middleware/fixImageUrlsMiddleware` that is doing the rewriting on the back end but we can find no mention of it on the frontend in the current system.  We understand that maybe you'd like the rewriting to take place on the frontend, but is the /api/upload url something we will only see from legacy data from the old system?

or will those URLs be created when image uploading is enabled on the new frontend?

**Comment by tansaku** [comment]
@ulfgebhardt @appinteractive we just heard from @mattwr18 that this ticket got de-prioritized.  I had written this blog post outlining some approaches that @aonomike and I were taking

https://nonprofits.agileventures.org/2019/03/28/pairing-with-mike-on-human-connection-vuejs/

We understand that it's low priority and perhaps difficult to explain, but I think Mike and I were on the cusp of understanding it; so if you do have a chance to review and answer our questions we'd very much appreciate it :-)

**Comment by roschaefer** [comment]
@tansaku @aonomike this ticket is still part of our ongoing milestone [Inanna](https://github.com/Human-Connection/Human-Connection/milestone/14) so I don't think it got de-prioritized.

In general. all volunteers are free to choose whatever task they like. I would prefer to have everyone productive over having everyone working on the important tasks. Plus, if there's a `good-first-issue` I try to keep that open for new developers. :slightly_smiling_face:

**Comment by roschaefer** [comment]
I will have a look, if anybody wants to pair: https://hangouts.google.com/hangouts/_/t7c5bc33cjburi5vbmaxg5w67ye

**Comment by roschaefer** [comment]
![2019-04-23-175825_1920x1080_scrot](https://user-images.githubusercontent.com/2110676/56596653-3a3b4f80-65f1-11e9-99d9-341b279f1536.png)

The backend is capable of serving `/public/` I will now have a look why the frontend does not serve the assets from the backend.

**Comment by appinteractive** [comment]
Just a comment on the upload on the Frontend side: it’s not a good idea from my perspective to separate the data and do some part on the Frontend and some part on the backend, this will explode if we want to serve images for activity pub for example or other aspects. Separating that seems to be a really bad idea from my point of view. At least the Frontend should really not be responsible for that.

**Comment by Lulalaby** [comment]
> 
> 
> @roschaefer Just a comment on the upload on the Frontend side: it’s not a good idea from my perspective to separate the data and do some part on the Frontend and some part on the backend, this will explode if we want to serve images for activity pub for example or other aspects. Separating that seems to be a really bad idea from my point of view. At least the Frontend should really not be responsible for that.
> 
> Maybe a microservice for that job would be a solution, acting like a cdn.

I agree to you

**Comment by roschaefer** [comment]
@appinteractive @Lulalaby I believe that https://github.com/Human-Connection/Human-Connection/pull/499 is going into this direction, isn't it? The frontend does not need to save images for badges, that are stored in the database + the frontend knows that it is proxying to `/api` so it's the responsibility of the frontend to prefix images with `/api`.

Did I understood your comment correctly, @appinteractive ?

**Comment by ulfgebhardt** [comment]
@roschaefer is this fixed?

**Comment by roschaefer** [comment]
@ulfgebhardt nope, it's closed once #499 gets merged
