### ISSUE TITLE
Change seed data to also seed a keypair

### ISSUE THREAD

**Issue by Mastercuber** [Human-Connection/Human-Connection#299]
**Describe the bug**
Now the seeded users in the database have no keypair. The keys are just `null`.

**To Reproduce**
Seed the data and get the users through the playground to see the public and private keys are `null`.

**Expected behavior**
When seeding the database the playground should show also a public and private key for a user.

**Additional context**
Use the generateRsaKeyPair function in conjuntion with the PRIVATE_KEY_PASSPHRASE to generate keypairs for use in the seed data.

**Comment by ulfgebhardt** [comment]
Not reproducable:

```
cd backend
yarn db:seed
query neo4j: MATCH (u:User {id: "u3"}) RETURN u
query graphql: query {User(id: "u3"){publicKey, privateKey}}
```

Result:

![image](https://user-images.githubusercontent.com/1238238/55397337-47ab6f80-5546-11e9-9d62-3f32ca528b49.png)

![image](https://user-images.githubusercontent.com/1238238/55397389-6b6eb580-5546-11e9-86eb-9964ef9a18af.png)

![image](https://user-images.githubusercontent.com/1238238/55397477-9c4eea80-5546-11e9-92bf-dcbb6ead6cf0.png)

Remark: Even tho exposing the Public & Private Key via GraphQL renders them useless, the described issue is no longer applicable

**Comment by roschaefer** [comment]
Good catch! @ulfgebhardt could you create a ticket to not expose private keys through our API? I think this should be a ticket of the "Migrate to Nitro" release because we create RSA keys once we create users. If we migrate the production database that would be the moment when the generation happens.
