### ISSUE TITLE
[DevOps] Rebuild staging server using helm

### ISSUE THREAD

**Issue by mattwr18** [Human-Connection/Human-Connection#3002]
## :fire: DevOps ticket

The staging server should be torn down and rebuilt with our new helm charts
### Motive

We decided to start using helm charts because it's easier to install all the needed resources(deployments, services, persistentvolumeclaims, etc.) with one command. 
It's also easier to upgrade when we deploy. More information about it's benefits can be found in their docs
https://helm.sh/
and in this blog
https://hackernoon.com/what-is-helm-and-why-you-should-love-it-74bf3d0aafc
### Related issues

https://github.com/Human-Connection/Human-Connection/issues/1629
### Implementation

A good idea would be to first take a copy of the existing configuration in case we would like to revert the changes. This command should be good enough 
```
kubectl get deployments,ingress,services,secrets,configmaps,pvc -n human-connection  -o yaml > staging-hc-namespace-config-backup.yaml
```
Then all the resources in the `human-connection` namespace can be safely deleted.
Most of the resources can simply be deleted with `kubectl delete <resource_type> ```
<resource_name>`

The exception being `PersistentVolumeClaims`, which have `finalizers: kubernetes.io/pvc-protection`
If you edit the `pvc` with `kubectl edit pvc uploads-claim -n human-connection` and replace it with `finalizers: []`, you can remove it. :skull_and_crossbones: **CAREFUL!!** this is a destructive action which can delete all `PersistentVolumes` if the `ReclaimPolicy` is not configured properly. 
In the case of staging, we don't care because we will add back the data to the database.
We could also try restoring the `uploads_claim` and `neo4j-data-claim` from a snapshot since they are in the same cluster. See https://docs.human-connection.org/human-connection/deployment/volumes/volume-snapshots
 
We also want to delete all the `cert-manager` resources. As we will be installing them using `Helm` v3. This goes for all `Tiller` resources as it's been removed in `Helm v3`
See https://helm.sh/docs/faq/#removal-of-tiller

You can get a list of resources to be deleted by running 
```
kubectl get all --all-namespaces | grep cert-manager(or tiller)
```
You also need to delete the `apiservice` for cert-manager
```
kubectl get apiservices | grep cert-manager
```
You also need to delete all clusterroles, clusterissuers, roles, rolebindings, MutatingWebhookConfiguration, ValidatinagWebhookConfiguration. 
If you run the `helm install cert-manager --namespace cert-manager --version v0.13.0 jetstack/cert-manager --dry-run` it will lead you to what you need to delete.

Once we have a clean slate, we can install everything again using our `Helm` charts.
See https://github.com/Human-Connection/Human-Connection/pull/1613 for docs on how to set it up. 
### Validation

The task would be considered successful when the site is reachable via `https://nitro-staging.human-connection.org` and this is redirected to `https://staging.human-connection.org`. 
Also, one should be able to do all the things they are accustomed to in the `develop` and `production` servers, ie log in, create resources, etc...

**Comment by Tirokk** [comment]
Hey @mattwr18 , 
for sure I have no insight in every detail, but in general you described really understandable what this is about and what to do. 🚀💫
It looks like a really big step into the scalable und better manageable DevOps future!!! @roschaefer  
😍

**Comment by mattwr18** [comment]
thanks @Tirokk ... I think maybe I could do a better job, in general, with issue creation by adding more screen shots ... not sure... with `DevOps` maybe it's not as important.
What I think I did a pretty good job of is linking to documentation.

**Comment by mattwr18** [comment]
this has been finished and now `nitro-staging` redirects to `staging` which has certs. 
there are several questions about using `Helm` to manage our clusters though, and it seems maybe to be more work that it's worth?
Or maybe I just need to get the hang of it, but so far it's been more work.
