### ISSUE TITLE
🚀 [Feature] Remove Hover Menu from User Teaser

### ISSUE THREAD

**Issue by alina-beck** [Human-Connection/Human-Connection#3004]
## :rocket: Feature
The `hover menu` should be completely removed from the `user teaser` component.

### User Problem
At the moment, the `user teaser` has two effects and a third one in planning:
- it opens a small popup on hover
- it links to the `user profile` on click
- planned: it toggles the `user id` on button click

Three different functionalities on one element is no good practice, it clutters the page and is hard to use. While the other two functionalities cannot (sensibly) be moved somewhere else, removing the hover menu only requires one further click to achieve the same goal (e.g. see follower numbers or follow the person).

### Implementation
Remove the `hover menu` from the `user teaser` component – make sure to also delete related CSS. :wink:

### Validation
We will wait for user feedback and see if many people complain about the missing menu. If so, it is easily reintroduced. If not, it probably wasn't used much in the first place.

**Comment by abdellani** [comment]
Hi
I'll work on this one :)

**Comment by abdellani** [comment]
As I understand, the goal is to avoid showing the popover menu when the user puts the cursor on `UserTeaser` area?

**Current behavior**

![Peek 2020-02-06 17-05](https://user-images.githubusercontent.com/16113997/73955139-2902cb80-4903-11ea-8d31-684a1e7f93b0.gif)

**Wanted behavior**

![Peek 2020-02-06 17-14](https://user-images.githubusercontent.com/16113997/73955754-23f24c00-4904-11ea-9ce4-9d0c4a334ed0.gif)

**Comment by Joellehelm** [comment]
I'd like to work on this if it's still available.

**Comment by mattwr18** [comment]
hey @Joellehelm, @abdellani was actually interested in working on it, and asked for clarification, which we gave with a :+1: , but he didn't see it, and we didn't assign him. 
Sorry for the confusion. Let me know if we can help you find another issue your interested in.

**Comment by sushidave** [comment]
As a user I prefer the popup. The downside of the removal is that it's more time and effort for me as a user. It leads to more clicks, increased system load and loss of performance. I used the popup to check out new users on the newsfeed. It allowed me to easily see their location and decide whether i would check their profile and connect with them or not.
