### ISSUE TITLE
🐛 [Bug] While Editing A Comment Don't Show Replay Button And Commenting Not Possible

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#3012]
## :bug: Bugreport

If a user edits their post:

- the replay button for this comment should not be seen under its edit field
- the edit field for the creation of a new comment at the very end shouldn’t show the commenting not possible hint

### Steps to reproduce the behavior
1. go to your comment under a post
2. click on the context menu and edit your post
3. you see still the replay button under your comment
4. the create new comment edit field is replace by the message `commenting not possible`

<img width="1876" alt="Bildschirmfoto 2020-02-05 um 17 17 54" src="https://user-images.githubusercontent.com/25344101/73935147-322e7100-48e0-11ea-92a6-d55b5bd3d6c1.png">

<img width="1876" alt="Bildschirmfoto 2020-02-05 um 17 17 54 Kopie" src="https://user-images.githubusercontent.com/25344101/73935118-20e56480-48e0-11ea-89af-5127833605b1.png">

### Version & Environment

Not important.

### Additional context

None.

**Comment by mattwr18** [comment]
closed in https://github.com/Human-Connection/Human-Connection/pull/3034
