### ISSUE TITLE
🚀 [Feature] Set The Teaser Image To The Appropriate Size Ratio From The Beginning

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#3013]
## :rocket: Feature

Set the teaser image to the appropriate size ratio from the beginning!
This avoids jumping in general and wrong scrolling to a comment.

### User Problem

If you go by a comment link on a page it scrolls to the comment first and then the teaser image gets downloaded and your target comment jumps again out of your view.
That's bad user experience.

### Implementation

On the post card of the newsfeed the size is already set after the ratio of the teaser image stored in the database. 😉

### Design & Layout

See above.

### Validation

Test it out yourself.

### Additional context

None.

**Comment by Ruben80** [comment]
Hi Can I help in this issue?

**Comment by Tirokk** [comment]
Sorry @Ruben80 that I haven’t responded so long.
Are you still interested in helping?

**Comment by DriesCruyskens** [comment]
I can help with this one if help is still needed.

**Comment by Tirokk** [comment]
Hey @DriesCruyskens ,
great to read that you like to jump in and offer your help. 💫
Therefore I have invited you to our repository as volunteer via an e-mail invitation you can except.
After you excepted, please push your feature branch directly to this repo and create a `PR` using `master` as the base branch.
