### ISSUE TITLE
[Epic] Dashboard

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#303]
```gherkin
Feature: Dashboard
  As a user
  I want to see new contributions, statistics, connected users and other network related information
  In order to keep up to date and get an idea about what's going on.
```

**Comment by roschaefer** [comment]
@datenbrei this is very broad. It would help to understand *why* you want to see this information and *what exactly*.

E.g: If you follow a user, you should see a notification for every new post or comment of that user.

If you want to see a statistic, where would you expect it? What number should be part of it? We do have an admin dashboard in place. Should part of it become available to every user?
![Screenshot (50)](https://user-images.githubusercontent.com/2110676/55105202-49031500-50cc-11e9-94e8-3ee20400dfb4.png)
![Screenshot (51)](https://user-images.githubusercontent.com/2110676/55105207-4b656f00-50cc-11e9-86ef-ad66236d4184.png)
