### ISSUE TITLE
🐛 [Bug] FilterMenu layout broken with seed data

### ISSUE THREAD

**Issue by mattwr18** [Human-Connection/Human-Connection#3055]
## :bug: Bugreport

Categories are not getting created correctly in seed data since the introduction of `rosie`

### Steps to reproduce the behavior
1. pull down latest code from `master`
2. reset and seed the database with `yarn db:reset` and `yarn db:seed`
3. open the filter menu 
4. see there are missing translations
5. Profit

![Screenshot from 2020-02-12 16-05-12](https://user-images.githubusercontent.com/26943915/74347979-3bbd4a80-4db2-11ea-8ff3-49f2ab82b766.png)

### Additional context

this is made worse by the fact that we translate in the frontend, so the frontend needs to know about the contents of the database. If we had a different solution, there might be missing buttons because the categories wouldn't exist, but at least there wouldn't be a broken layout

**Comment by sushidave** [comment]
Bug seems to be fixed.
