### ISSUE TITLE
🐛 [Bug] Scrollbar not usable in 'mentioned bell info' window

### ISSUE THREAD

**Issue by erhardtstiefel** [Human-Connection/Human-Connection#3065]
## :bug: Bugreport
If you touch the scrollbar with the mouse, the whole window disappears

### Steps to reproduce the behavior
1. If your 'mentioned bell' shows a red number greather than 2 
2. a mouseclick to the bell opens a window
3. if a scollbar is visible, move the mouse pointer to the scrollbar
4. the window disappears
5. I have to use my scrollwheel to find the first comment at the bottom of the list

### Expected behavior
the scrollbar should behave normally
![Screenshot 2020-02-13 143740](https://user-images.githubusercontent.com/49943365/74442843-80a8b600-4e72-11ea-9746-b2e5750e2329.jpg)

### Version & Environment
 Type: []      Laptop
 - OS: []      Windows 10
 - Browser: [] Mozilla Firefox
 - Version []  73.0 (64-Bit)
 - Device: []  

### Additional context
low priority

**Comment by ogerly** [comment]
i can confirm this error 
Betriebssystem: [] Linux Ubuntu 18.04 (64-Bit)
Browser: [] Chrome, Chromium
Version [] Version 79.0.3945.130  Built on Ubuntu , running on Ubuntu 18.04 (64-Bit)

**Comment by rbeer** [comment]
Is this still a problem?
I can't reproduce this on the develop instance.
Should have been fixed with #3218

**Comment by erhardtstiefel** [comment]
trouble is fixed, thank you
