### ISSUE TITLE
💥 [DevOps] Remove wsEndpoint to unblock deployment

### ISSUE THREAD

**Issue by mattwr18** [Human-Connection/Human-Connection#3082]
## :fire: DevOps ticket

At the moment, we have an issue with deploying websockets due to ability to configure websockets_uri for different production environments. See https://github.com/Human-Connection/Human-Connection/issues/3064 and https://github.com/nuxt/nuxt.js/issues/5100

This is blocking our deployment of other features/bug fixes, but most importantly a security related bug fix. If we remove the `wsEndpoint`, it will not try to connect to websockets and we can work on a solution.
### Motive

see :point_up_2: 
### Related issues

see :point_up_2: 
### Implementation

comment out the line in `apollo-config.js`
### Validation

when it's deployed and does not try to connect to websockets, it should be considered successful.

**Comment by roschaefer** [comment]
@mattwr18 closing, fixed in #3089
