### ISSUE TITLE
🚀 [Feature] Projects

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#312]
```gherkin
Feature: User Projects
  As an engaged single user or organization
  I want to set up and steer projects
  In order to get bigger challenges done which can not be done by few people alone.
```
### Features
- [ ] Project Info
- [ ] Project Events
- [ ] Project Jobs
- [ ] Project CanDos
- [ ] Project Chat
- [ ] Project Timeline
- [ ] Project Participants
- [ ] Project Invitations

## Project on Dashboard
![onDashboard_project](https://user-images.githubusercontent.com/13457963/59335530-0a5d1e00-8cfd-11e9-896e-07921c1d81db.png)

## Project Main View shows Events and Jobs
![humanconnection-project-150716](https://user-images.githubusercontent.com/13457963/59335601-324c8180-8cfd-11e9-8c87-f9f9a8f066c1.png)

## Project with CanDo
![project](https://user-images.githubusercontent.com/13457963/59335388-c9650980-8cfc-11e9-8369-05ac3e8c2c15.jpg)

## Project Timeline
![Project_0002_timeline](https://user-images.githubusercontent.com/13457963/59339931-6035c400-8d05-11e9-8e65-5d216bf37678.jpg)

##Project Chat
![Project_0000_chat](https://user-images.githubusercontent.com/13457963/59340132-b1de4e80-8d05-11e9-885c-8e6308905de8.jpg)

## Project Participants
![Project_0002_Participants](https://user-images.githubusercontent.com/13457963/59340038-8bb8ae80-8d05-11e9-8cd6-af4a7648ccaa.jpg)

## Project Invitations
![Project_0003_Invited](https://user-images.githubusercontent.com/13457963/59340227-d76b5800-8d05-11e9-8b97-3dcb188d79b6.jpg)

**Comment by roschaefer** [comment]
@datenbrei what is a project compared to a job? What would be different to a normal posting?
