### ISSUE TITLE
[Epic] More Info

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#317]
```gherkin
Feature: More Info
  As a user
  I want to see additional related information aside a contribution
  In order to get deeper into a topic and learn more about it.
```

**Comment by roschaefer** [comment]
@datenbrei I don't know how this should work? Do you want to see *related* content, maybe? We could relate two posts via collaborative filtering or just plain by categories, tags.

**Comment by ulfgebhardt** [comment]
closed in favor of https://github.com/Human-Connection/Human-Connection/issues/393
