### ISSUE TITLE
Setup a (data-privacy friendly) analytics service

### ISSUE THREAD

**Issue by appinteractive** [Human-Connection/Human-Connection#32]
We want to get some statistics without using external services. Therefore we need a working matomo docker compose with all needed services to run inside conditioners so we can deploy it. 

https://matomo.org/

Edit:
As @datenbrei mentions below we could use https://usefathom.com/ instead.

**Comment by realB12** [comment]
Is there an overall plan and proper evaluation process that is putting this into context? Why analytic? What kind of analytics and most important: what are the concrete actions and benefits out of this?
Are we 100% clear about what we need - now and in the future - that we have all the stable requirements that make Matomo the only possible and never changing option everybody is and will be happy with in the future. Who decides all this?

**Comment by appinteractive** [comment]
It’s the least intrusive way to get deeper insights to what works, what doesn’t and how we can improve the platform in the future. You will be able to opt out of it so you will not have to participate in helping with your anonymous data. It’s a tool for improvement. It was discussed internally multiple times and is by our knowledge the best option for maintaining data privacy. Any other suggestion for a modern, self hosted, open source analytics that is not selling your privacy? If so, please share it with us. 

I don’t want to make It a multi decade standardization process like the w3c does it and we do not need to. It’s important to iterate fast (as it also costs money) so we all can use this tool here sooner then later and improve it. Don’t agree? Fork, host and maintain it for your self. It’s MIT.

**Comment by datenbrei** [comment]
Still needed now that we have [Fathom](https://usefathom.com/)?

**Comment by mattwr18** [comment]
still relevant? I didn't know we have `Fathom`... are we collecting analytics already? there is no opt-out from the user perspective, as far as I know, if we are already collecting anonymous data...
can you clarify this @datenbrei? It still seems like something that would be good to implement, no?
