### ISSUE TITLE
[Feature] Chat

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#321]
```gherkin
Feature: Chat
  As a user
  I want chat with other users 1:1 or maybe in chat groups
  In order to talk to people more directly and also to share personal information not visible to the public.
```

**Comment by mattwr18** [comment]
@datenbrei is this somehow different from https://github.com/Human-Connection/Human-Connection/issues/38
I know this was created first, but there is more conversation about the issue and its implementation there, so can we close this?

**Comment by volanar** [comment]
I suggest to make integration with Rocket chat. It is free, there is live chat, you can communicate with personal messages and there are group chats

**Comment by mattwr18** [comment]
this is a duplicate of https://github.com/Human-Connection/Human-Connection/issues/38
