### ISSUE TITLE
🚀 [Feature] Delete a post

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#330]
**Is your feature request related to a problem? Please describe.**
As a user I can already create and update a post, but I cannot delete the post entirely. This is even required by european GDPR.

**Describe the solution you'd like**
I would like to click on the context menu and in case I am the author I should see a "Delete Contribution" button. When I click on this button, I should see a confirmation dialog and when I click on "OK", the post should be deleted.

**Additional context**
![Screenshot (52).png](https://images.zenhubusercontent.com/57a4768be40e5714b16cfc65/74cc4ec3-ed24-47f2-87dd-acb6cb043e66)

### Userstory
```
Feature: Posts
  As a user
  I want to delete posts and see them no longer listed
  In order to stop sharing my personal interests and ideas with others.
```

**Comment by roschaefer** [comment]
**Is your feature request related to a problem? Please describe.**
As a user I can already create and update a post, but I cannot delete the post entirely. This is even required by european GDPR.

**Describe the solution you'd like**
I would like to click on the context menu and in case I am the author I should see a "Delete Contribution" button. When I click on this button, I should see a confirmation dialog and when I click on "OK", the post should be deleted.


**Additional context**
![Screenshot (52).png](https://images.zenhubusercontent.com/57a4768be40e5714b16cfc65/74cc4ec3-ed24-47f2-87dd-acb6cb043e66)

**Comment by roschaefer** [comment]
@datenbrei in the source code I see several references to a `softDelete` functionality. If a user deletes his or her own post, should the original post stay preserved in the database? Aren't we required by law to delete a comment or post irrecoverably?

**Comment by ulfgebhardt** [comment]
Post should stay - softdelete is good

**Comment by roschaefer** [comment]
@ulfgebhardt why?

**Comment by danielgrijalva** [comment]
Hi, is this issue available? I can work on it :)

**Comment by ulfgebhardt** [comment]
yes you can @danielgrijalva

**Comment by danielgrijalva** [comment]
@ulfgebhardt Okay then! For now I'll be reading your contribution guidelines, setup instructions and then I'll dive into the docs and code :ok_man:

**Comment by roschaefer** [comment]
@danielgrijalva we :heart: you. In case you don't know, we have a group chat for the open-source community. If you get stuck, we're can help: https://discordapp.com/invite/6ub73U3

**Comment by danielgrijalva** [comment]
@ulfgebhardt @roschaefer hey guys, I just opened a PR :sweat_smile:  mind if you review it?
