### ISSUE TITLE
🐛 [Bug] Comment updates only shown after page reload

### ISSUE THREAD

**Issue by sushidave** [Human-Connection/Human-Connection#3357]
## :bug: Bugreport

Sometimes comment updates are not shown instantly but only after a page reload.

### Steps to reproduce the behavior
1. Update an existing comment.
2. Click on the save button
3. Check the comment. Sometimes the updates are not shown.
4. Reload the page and check the updated comment.

### Expected behavior

Comment updates shown immeditately after clicking on the Save button. 

### Version & Environment
 Type: [Notebook]      
 - OS: [macOS]      
 - Browser: [Firefox] 
 - Version [74.0]  
 - Device: [MacBook]  

### Additional context

Reported by user joeletaxi on 26/27 March 2020

**Comment by Elweyn** [comment]
hi @sushidave,
thanks for the comment on #2112 I will write here what we found:

in webapp/components/CommentList/CommentList.vue we can find at line 39 a computed postComments
When deleting or updating a comment we use in the same file the methode line 50 updateCommentList()
This methode tries to change the computed postComments
<img width="603" alt="Bildschirmfoto 2020-08-06 um 11 22 19" src="https://user-images.githubusercontent.com/33051975/89515226-1d6f5f00-d7d7-11ea-933a-7c9417baf628.png">

We tried to change the updateCommentList methode from:
```
this.postComments = this.postComments.map((comment) => {
        return comment.id === updatedComment.id ? updatedComment : comment
      })
```
to:
```
     this.postComments.map((comment) => {
        return comment.id === updatedComment.id ? updatedComment : comment
      })
```
or
```
      this.post.comments.map((comment) => {
        return comment.id === updatedComment.id ? updatedComment : comment
      })
```
but neither of the changes has changed anything to the behavior.

**Comment by sushidave** [comment]
@Elweyn Thank you for sharing your findings. @Tirokk Could you please have a look at it?

**Comment by Elweyn** [comment]
Like @Mogge said: Here should be added a Test!
