### ISSUE TITLE
💥 [DevOps] Take a volume snapshot of the uploads-claim 

### ISSUE THREAD

**Issue by mattwr18** [Human-Connection/Human-Connection#3394]
## :fire: DevOps ticket

we have all our images hosted on `DO spaces` and will soon be deleting the `uploads-claim`.

### Motive

we have backups on our local encrypted `HD`, but it is much faster/simpler to create an upload claim from a `volumesnapshot`
### Implementation

check that you are in the production context
1) `kubectl config get-contexts`
2) `kubectl get volumesnapshots -n human-connection` See the latest number of the snapshot, currently `uploads-snapshot-4`
3) edit `deployment/volumes/volume-snapshots/snapshot.yaml` name to one number higher
ie `yyyy-mm-dd-uploads-snapshot`.
4) `kubectl apply -f deployment/volumes/volume-snapshots/snapshot.yaml`
5) `kubectl get volumesnapshots -n human-connection` to check it was successfully created.

### Validation 

you can restore this in `staging` to "test" that it was successfully created
(this would require deleting the `uploads-claim` there, and recreating it from a volumesnapshot, and can be tested before deleting the volumesnapshot in production)
### Additional context

https://docs.human-connection.org/human-connection/deployment/volumes/volume-snapshots

**Comment by Tirokk** [comment]
Done 💫
