### ISSUE TITLE
🚀 [Feature] Backup

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#340]
**Is your feature request related to a problem? Please describe.**

Backup the Database and be able to restore it with minimum downtime

**Describe the solution you'd like**

Something like
```
server.stop()
db.dump()
db.restore()
server.start()
```

**Describe alternatives you've considered**

No Backup ¯\_(ツ)_/¯

**Additional context**

**Comment by ulfgebhardt** [comment]
No automation for Alpha

**Comment by roschaefer** [comment]
I believe, except the automation, this issue is pretty much covered, isn't it @ulfgebhardt ?

See: https://docs.human-connection.org/human-connection/deployment/volumes and its sub-chapters.
