### ISSUE TITLE
🚀 [Feature][Neo4j] Remove Apoc Plugin

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#341]
**Is your feature request related to a problem? Please describe.**

Remove Neo4j Apoc Plugin - it might not be needed anymore

See:
https://github.com/Human-Connection/Human-Connection/pull/339/commits/cd6838a4682fd22046efcc4f46df4b681b497097#diff-6fb47b21a24e15924bdc4eb6acfdb527R75

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by roschaefer** [comment]
I did some research on this. It seems that [neo4j-graphql-js](https://github.com/neo4j-graphql/neo4j-graphql-js) depends on the plugin. [From what I can tell](https://github.com/neo4j-graphql/neo4j-graphql-js/search?q=apoc&type=Code) it's using it only for `runFirstColumn` and the `uuid`.

This means, we cannot get rid of this dependency right now. We need to fix it in `neo4j-graphql-js` itself.  The few occurences of apoc in the framework don't seem like a justification for having that dependency. @ulfgebhardt could you ask them, if it would be possible to remove that dependency?

E.g. in our case, we want to create the unique ids ourselves. It won't be a `uuid` but a [nanoId](https://github.com/ai/nanoid) and we generate it in our middleware.

**Comment by ulfgebhardt** [comment]
closing this since we as HC now have dependencies on this plugin
