### ISSUE TITLE
[Docu] Merge Nitro-Documentation into HumanConnection Repo

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#342]
**Is your feature request related to a problem? Please describe.**
Our [Docs](https://docs.human-connection.org/nitro) are not part of this repository yet. This creates problems because documentation and actual implementation get out of sync.

As a developer you would e.g. refactor the code and do a `git grep SOMETHING` and search for any remaining occurrences of a renamed identifier. Since the documentation is not part of the repository, it is very easy to overlook the documentation and to fail on keeping it up to date.

**Describe the solution you'd like**

TODOs:
- [ ] Merge Nitro-Documentation into HumanConnection Repo (e.g. Use [tomono](https://github.com/unravelin/tomono))
- [ ] Update `.travis.yml` to deploy the documentation with [gitbook](https://www.gitbook.com/)

**Comment by roschaefer** [comment]
@ulfgebhardt it is fine to remove the issue template if it does not fit such a maintenance task like this. I will update the issue description.
