### ISSUE TITLE
🐛 Whitelist all auto-generated Mutations/Queries

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#343]
**Describe the bug**
Disable all Mutations/Queries via middleware and recheck which can be enabled under which circumstance.

We use [neo4j-graphql-js](https://github.com/neo4j-graphql/neo4j-graphql-js) as a query builder. None of the generated mutations/queries has authentication/authorization by default. Therefore we need to white-list only those mutations that we need and which are tested on security we before migrating our [production server](https://alpha.human-connection.org/) to the new nitro code base.

**To Reproduce**
1. Go to 'http://localhost:4000'
2. Create e.g. a comment:
```graphql
mutation {
  CreateComment(content: "I am a comment") {
    id
  }
}
```
3. Click submit
3. You just created a comment without an author.

**Expected behavior**
No private data should be exposed, ie. emails of users. No disabled or deleted content should be visible. No data should be created without authorship of the current user.

**Comment by roschaefer** [comment]
@ulfgebhardt it is really important to explain the reason for a feature. We discussed it in our meeting this afternoon and we should put the context into the issue description. This creates transparency for our open-source contributors. I'll update.
