### ISSUE TITLE
Send and receive notifications via ActivityPub

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#349]
In order to notify users of the current instance of Human Connection, remote instances of Human Connection or users of a 3rd-party social network like Mastodon and Friendica, we should send out notifications on each `CreatePost` and each `CreateComment`, probably also for each `UpdatePost` and `UpdateComment` as well as `DeletePost` and `DeleteComment`.

This action should create, update or delete a notification entity in our database **and** it should create a local copy of the post/comment if it does not yet exist in the database of the current instance.

**Comment by roschaefer** [comment]
@Mastercuber can you verify this? Is this the only technical implementation related to activityPub of the epic #345?

**Comment by Mastercuber** [comment]
For all functions an corresponding activity need to be created and then send through the `sendActivity` function of the `ActivityPub` class. Where the activities are send to depends on the "known network". This is represented by all shared inbox endpoints known by the instance, so first some shared inbox endpoints are needed..

**Comment by Mastercuber** [comment]
For all functions an corresponding activity need to be created and then send through the `sendActivity` function of the `ActivityPub` class. Where the activities are send to depends on the "known network". This is represented by all shared inbox endpoints known by the instance, so first some shared inbox endpoints are needed..

**Comment by Mastercuber** [comment]
Give [this](https://www.w3.org/TR/activitystreams-vocabulary/#microsyntaxes) a read to see that the usage of the primary audience should also send a notification to the users.

So instead of the above six functions the ActivityPub service needs to create a notification when a post or comment is created updated or deleted.

**Comment by ulfgebhardt** [comment]
@roschaefer is this still a valid issue? Or can we remove it completely?
-> in reference to https://github.com/Human-Connection/Human-Connection/issues/345#issuecomment-484561887

**Comment by roschaefer** [comment]
No! Don't close it. It is a feature in the scope of federation. We would have to send out notifications for other 3rd party applications if sb. writes a post who is followed by a user of the 3rd party app.

I just found out that we there is no direct dependency, we can implement notifications on our side without federating notifications - for now.

**Comment by mattwr18** [comment]
> No! Don't close it. It is a feature in the scope of federation. We would have to send out notifications for other 3rd party applications if sb. writes a post who is followed by a user of the 3rd party app.
> 
> I just found out that we there is no direct dependency, we can implement notifications on our side without federating notifications - for now.

what he said :point_up_2: `stale_bot`
