### ISSUE TITLE
Geographical sozializing

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#35]
**Is your feature request related to a problem? Please describe.**
Several users have told us in the "Kamingespräch" that they would like to get in touch with other members of the community in their local vicinity. There is currently no way to find events, groups or members who are located e.g. in my home town.

**Describe the solution you'd like**
As a start, I would like to "tag" posts or can-dos with GPS coordinates. These coordinates could also be entered with a "reverse geocoded" address, ie. address -> coordinates. There should be a map that visualizes those coordinates and lets me select all items within a certain area.

**Describe alternatives you've considered**
We could let users add geographical coordinates to their profile. However I believe, that it would be nicer to your data privacy if not people but things are tagged geographically. A user should know his or her current location and that should be sufficient enough to socialize with other users of that interest.

**Additional context**
![screenshot 6](https://user-images.githubusercontent.com/2110676/45952869-aa0c3c00-c008-11e8-8833-2b669e00cfb6.png)

I would suggest "marker clustering" visualizations: 

https://developers.google.com/maps/documentation/javascript/marker-clustering
https://asmaloney.com/2015/06/code/clustering-markers-on-leaflet-maps/
https://regionbound.com/region-aware-marker-clustering-for-maps

**Comment by Lulalaby** [comment]
Nice one, would love to see that

**Comment by appinteractive** [comment]
We are using Mapbox already which you can see on the take action screen at the bottom with seeded data locally. 

https://www.mapbox.com/mapbox-gl-js/example/cluster/

**Comment by appinteractive** [comment]
https://medium.com/neo4j/working-with-neo4j-date-and-spatial-types-in-a-react-js-app-5475b5042b50

**Comment by mattwr18** [comment]
I guess that this is still relevant, but maybe needs to be updated @roschaefer ?
we certainly don't have a way for others to find others based on geography...
