### ISSUE TITLE
Kubernetes Cronjob to backup Neo4J

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#354]
We should depend on community edition because we cannot expect sb. who wants to host Human Connection to pay for Neo4J enterprise edition. The community edition has only offline backups available. We need to find a way to download a Neo4J dump regularly in order to avoid data loss.

**Comment by roschaefer** [comment]
@mattwr18 why? This feature is not how to do backups but how to create backups regularly with a CronJob.

**Comment by mattwr18** [comment]
I didn't close this on purpose, I was in zenhub talking about it in our pairing session, and then I noticed it had been closed. not sure what happened

**Comment by daumie** [comment]
@roschaefer I have worked with Kubernetes Cron Jobs Before, though I will need more clarification on where to store the data dump.

**Comment by roschaefer** [comment]
@daumi from the slack channel `#human-connection` at [Agile Ventures](https://agileventures.slack.com/messages/CEANP62HG/):


> Robert Schäfer [10:01 PM]
@ dominic hey Dominic, I saw your direct message, you asked where to store the neo4j backup for the kubernetes cronjob
To me it is still unclear where the backup should be stored
But I would assume we either upload it somewhere via `scp` or we use some cloud storage like S3
I know that there is a tool which does disaster recovery for kubernetes
Called velero
That's exactly what we need
https://github.com/heptio/velero
On-premise are fine too!
I would just like to have a backup solution without a downtime
https://docs.human-connection.org/human-connection/deployment/backup
This is where we are right now: we're able to do offline backups so we have to start and stop the database
But this procedure will not be a good solution if we e.g. want to do a backup before a deployment
Having a downtime will not be accetable
@ dominic is this understandable?
Do you see where the pain is :slightly_smiling_face:
?
