### ISSUE TITLE
ActivityPub: outbox#first results in HTTP 500 error

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#361]
**Describe the bug**
I just seeded again with `activityPub` middleware enabled and I can see public keys on nitro:
![Screenshot (67)](https://user-images.githubusercontent.com/2110676/55438371-ac47e800-55a1-11e9-841c-152cae5cce6d.png)
But I still cannot see my posts on Mastodon:
![Screenshot (68)](https://user-images.githubusercontent.com/2110676/55438427-d4cfe200-55a1-11e9-9f83-765c07495a5f.png)

I believe now it's because of a HTTP 500 error on our nitro:

**To Reproduce**
1. Visit https://nitro-staging.human-connection.org/activitypub/users/jenny-rostock/outbox
2. Click on ' "first": "https://nitro-staging.human-connection.org/activitypub/users/jenny-rostock/outbox?page=true",'
3. See "This page is not working" (500 error)

**Expected behavior**
I would expect the first post.

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Browser `Chromium 73.0.3683.86 Arch Linux`

**Comment by roschaefer** [comment]
@Mastercuber ideas?

**Comment by Mastercuber** [comment]
That's one thing which makes me crazy: also if the endpoint would serve the items in the paged collection, posts sometimes though the collections have the exact same structure as the mastodon collections, they are not visible. This I have perceived  also between mastodon instances. 

For the actual issue I will push a fix in a minute
