### ISSUE TITLE
🚀 [Feature] Increase margin of headings and rulers

### ISSUE THREAD

**Issue by sushidave** [Human-Connection/Human-Connection#3628]
## :rocket: Feature

Increase the margin of headings and rulers of content of posts and comments to increase readability.

### User Problem

The margins on headings and rulers are too little. Currently, the content of posts doesn't look nice if they contain headings or rulers and the readability suffers. The reason for this is that the stylesheet neutralizes margins for headings, lists and paragraphs...
```
h1, h2, h3, h4, h5, h6, ol, p, ul {
    margin: 0;
}
```
...but doesn't apply custom styles for headings.

### Implementation

Add margins to the stylesheet for headings H3 H4 and rulers.

### Design & Layout

Example for H3:

Before:
![hc-editor-styling-for-headings-now](https://user-images.githubusercontent.com/17728384/84441237-b6e91d00-ac3b-11ea-8cb9-c23e728e1dc0.png)

After:
![hc-editor-styling-for-headings-future](https://user-images.githubusercontent.com/17728384/84441247-ba7ca400-ac3b-11ea-8317-d938b0ed4dec.png)

### Validation

Better readability and user satisfaction. Healthier eyes 👀

### Additional context

As discussed with @Raimundo-dev today.

**Comment by varunpusarla** [comment]
Can I work on this issue ? @sushidave

**Comment by sushidave** [comment]
@varunpusarla Hello Varun and thank you very much for your readiness to contribute to this project! Yes, you're welcome to work on it. @Tirokk Please provide Varun with the necessary information. Thank you.

**Comment by Tirokk** [comment]
Hello @varunpusarla ,

I have invited you to our repository as volunteer via an e-mail invitation you can except.
After you excepted, please push your feature branch directly to this repo and create a PR using master as the base branch.

I assigned you to this issue …

Our conversation runs over our discord channels:
http://hc.world/discord
Another possibility to get to it:
https://discord.com/invite/DFSjPaX

On Discord we have kind of every day a Daily Standup at UTC 09:30 am (CEST 11:30 am) in the Conference Room.

**Comment by ritesh-pandey** [comment]
@varunpusarla are you still working in it?

**Comment by Tirokk** [comment]
Are you still interested in overtaking this @ritesh-pandey ?

**Comment by Tirokk** [comment]
Hello @ritesh-pandey  ,

I’ll organise that you get invited to our volunteers-team via an e-mail invitation you can except.
After you excepted, please push your feature branch directly to this repo and create a PR using master as the base branch.

I assigned you to this issue …

Our conversation runs over our discord channels:
http://hc.world/discord
Another possibility to get to there:
https://discord.com/invite/DFSjPaX

On Discord we have kind of every day a Daily Standup at UTC 09:30 am (CEST 11:30 am) in the Conference Room.

**Comment by sushidave** [comment]
@ritesh-pandey @Tirokk @ogerly How nice that you could fix it! Thanks a lot for your efforts 🙏
