### ISSUE TITLE
🚀 [Feature] Redesign data privacy warning box

### ISSUE THREAD

**Issue by sushidave** [Human-Connection/Human-Connection#3657]
## :rocket: Feature

Redesign the data privacy warning box for embedded content. 

This is step 1 of 2 to enhance the data privacy warning box. 2nd step see #3658 .

### User Problems

1. The text in the box contains the term "video" for non-video content like from SoundCloud.
2. The button text says "Watch now" even for audio content.
3. The buttons are both in green and don't correspond to the latest styleguide.

### Implementation

- [ ] Replace the word "video" by "content", see screenshot below.
- [ ] Change the text of the first button from "Watch now" to "Continue".
- [ ] Change button colors: Green (filled) for Continue, red (borders) for Cancel.

### Design & Layout

![hc-embedded-content-privacy-notice-redesign](https://user-images.githubusercontent.com/17728384/85072143-e27a8300-b1b8-11ea-8946-dc4aaa61ae88.png)

### Validation

Text and style update.

### Additional context

This is step 1 of 2 to enhance the data privacy warning box. 2nd step see #3658 .

**Comment by Tirokk** [comment]
Hey @sushidave ,
thanks for creating this issue! 🤗

**Comment by Thiruppathi** [comment]
Hi @sushidave 
Can I pick this up?

**Comment by sushidave** [comment]
Good evening @Thiruppathi 
Thanks for your willingness to contribute! You're very welcome to pick it up.
@Tirokk Please provide Thiru with the necessary details. Also, should the buttons be swapped (1st: Cancel, 2nd: Continue) so that the order is consistend with the ones on other pages like the post editing page?

**Comment by Tirokk** [comment]
Hello @Thiruppathi ,

I have invited you to our volunteer team via an e-mail invitation you can except.
After you excepted, please push your feature branch directly to this repo and create a PR using master as the base branch.

I assigned you to this issue …

Our conversation runs over our discord channels:
http://hc.world/discord
Another possibility to get to it:
https://discord.com/invite/DFSjPaX

On Discord we have kind of every day a Daily Standup at UTC 09:30 am (CEST 11:30 am) in the Conference Room.
