### ISSUE TITLE
💬 [Question] Add labels for functional areas

### ISSUE THREAD

**Issue by sushidave** [Human-Connection/Human-Connection#3659]
## :speech_balloon: Question

As discussed with @Tirokk and @Raimundo-dev the network operator "Verein Menschheitsfamilie" proposes to add labels for features (functional areas). 

Benefits:
1. Issues can be filtered by functional area, e.g. all issues about posts.
2. Manually updating EPICs which were created in order to group some issues can be avoided.

Here is the list of suggested labels:
- features:account-registration
- features:account-settings
- features:comment
- features:filter
- features:notification
- features:post
- features:post-editor
- features:search
- features:sorting
- features:user-profile
- features:widget

@Tirokk Since these lables apply to the whole repository we kindly ask for busFaktor()'s agreement.

**Comment by Tirokk** [comment]
@Human-Connection/hc-dev-team 

What you think of this idea. We hope that we can administrate the issues better that way.
Menschheitsfamilie has created now it’s own project-roadmap …

**Comment by sushidave** [comment]
@Tirokk Thanks for your green light. Tags have been added. Closing this issue.
