### ISSUE TITLE
🎉 Community Repository 🎉

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#3674]
Hey people, it's creativity time!

In order to continue the development of Human Connection and to keep the ball rolling, we decided to create a new dedicated community repository. We don't know a good name for the software project and its repository, yet.

The community-repository will live at:
{NAME}-community/{NAME}

That's where we need your help!

The {NAME} should at least be:
* easy to spell
* easy to pronounce
* not be occupied by another software project

Ideally, the {NAME} should also mention:
* openness and inclusiveness
* a cute animal
* an endangered species
* the "fediverse"
* free and open source software
* active citizenship

Please write a comment with your ideas and inspirations! :hugs: 

Yours,
Robert

@abdellani @adarsh-av13 @ALau2088 @andreasposur @AndreiBu @aonomike @appinteractive @ATOMktn @bocajnannerb @DakshMiglani @daumie	Dominic @DennisHack @DriesCruyskens @drowvoloper @emmerlin1 @erhardtstiefel @ewanold @faithngetich @FedericoEsparza @gha-gozu @HC-Team @iylim @janethavi @Kachulio1 @KapilJ22 @koushik-ms @leternoz @Lulalaby @MarcoBomfim @Mastercuber @matthib @mattwr18 @mcdead154 @Mogge @MoldaB @Mozar10 @nila99 @nimitbhargava @ogerly @okobiajoshua @ppelegrin @proofy @Raimundo-dev @rbeer @roschaefer @Ruben80 @steffi201028 @sushidave @tansaku @tidus9 @Tirokk @ulfgebhardt @vardyb @vbelolapotkov @victorrms2

**Comment by Kachulio1** [comment]
this is awesome, you said "We don't know a good name for the software project and its repository", are you/we looking for a great frontend library, like `React`

**Comment by Kachulio1** [comment]
@roschaefer ☝️

**Comment by roschaefer** [comment]
@Kachulio1 :trollface: no, we're not considering to replace React for Vue, at least not yet :wink: 

We're asking you to come up with a nice name for the community repository. It's not going to be called "Human Connection".

**Comment by sushidave** [comment]
Yes, keep the ball rolling!

How about:

"Communiverse"
= portmanteau of community and fediverse

"Renkontejo"
= means "meeting point" in Esperanto

**Comment by sushidave** [comment]
"Confedi"
= portmanteau of connect + fediverse ...and it sounds like confetti in American English

**Comment by proofy** [comment]
https://namelix.com/app/?keywords=openness+animal+endangered+free+citizenship

**Comment by erhardtstiefel** [comment]
What about "slugover-community" 
I've learned that a community of **slug**s will be connected with **o**pen source software in a fedi**ver**se network. Slugover is related to Hangover, both little cute animals and endangered species.

**Comment by proofy** [comment]
matengage = mate + engage = Connect with commitment!
Not hits at github
Mate = https://en.wikipedia.org/wiki/Mate_(horse) Name of  a racehorese

**Comment by Lulalaby** [comment]
And for what exactly?

**Comment by roschaefer** [comment]
Development in this repository has stalled. So the former core maintainers want to copy the repository to continue development. The new repository needs a new name. @Lulalaby @medizinmensch @baba43 does that make more sense now?

**Comment by DennisHack** [comment]
Aus steuerrechtlichen Gründen kann das geplante Konstrukt nicht übernommen/angewandt werden, deswegen wird dieses Isue geschlossen. Bei Fragen stehen wir sehr gerne zur Verfügung.
