### ISSUE TITLE
🚀 [Feature] Sorting

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#375]
### Sorting

![image](https://user-images.githubusercontent.com/1238238/55476214-46e20e80-5616-11e9-9a70-3a53e586d2bf.png)

- [ ] Latest (newest)
- [ ] Oldest
- [ ] Most Popular (shouts)
- [ ] (optional) Most commented/interactions https://github.com/human-connection/human-connection/issues/265

### Userstory

missing @roschaefer 

### Design & Layout - Alpha

Closed:
![image](https://user-images.githubusercontent.com/1238238/55476266-7264f900-5616-11e9-971e-6b5275a0a318.png)

Open:
![image](https://user-images.githubusercontent.com/1238238/55476214-46e20e80-5616-11e9-9a70-3a53e586d2bf.png)

### Design & Layout - Nitro
missing

**Comment by Tirokk** [comment]
# Additional functionality suggestion

- [ ] Prefer posts with a `Can Do` in the Post-Feed, because we are an action network.

**Comment by ulfgebhardt** [comment]
Can be filtered @Tirokk see https://github.com/Human-Connection/Human-Connection/issues/374

**Comment by Tirokk** [comment]
I like to say @ulfgebhardt : As the default setting, have always Posts with `Can Do` at first in the sorting. I corrected my suggestion now …

**Comment by ogerly** [comment]
![Bildschirmfoto vom 2019-07-10 22-31-05](https://user-images.githubusercontent.com/1324583/61002763-91d09800-a362-11e9-90f7-359de6b196f1.png)
![FireShot Capture 177 - Human Connection - Human Connection - localhost](https://user-images.githubusercontent.com/1324583/61002764-91d09800-a362-11e9-94a3-0351ed4012b1.png)
![FireShot Capture 176 - Human Connection - Human Connection - localhost](https://user-images.githubusercontent.com/1324583/61002765-92692e80-a362-11e9-9a2c-ccc7f6a15f03.png)
![FireShot Capture 175 - Human Connection - Human Connection - localhost](https://user-images.githubusercontent.com/1324583/61002766-92692e80-a362-11e9-9aea-5ee199099da9.png)
