### ISSUE TITLE
🐛 Sign Up Page is Broken

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#3788]
## :bug: Bugreport

@appinteractive reported me that the sign up page is broken.

### Steps to reproduce the behaviour

1. go on our social network
2. don’t log in
3. click on sign up
4. here you see

<img width="843" alt="Bildschirmfoto 2020-08-10 um 09 40 38" src="https://user-images.githubusercontent.com/25344101/89761195-2d948080-daee-11ea-9a1e-5f788b002942.png">

### Expected behavior

I expect the page to be designed well.

I guess the logo is much to big.
See log in page …

### Version & Environment

Every

### Additional context

None

**Comment by Mogge** [comment]
I cannot reproduce this behavior on firefox.
![image](https://user-images.githubusercontent.com/15882241/89795806-2048b780-db29-11ea-91aa-b6a6f3a9b209.png)

**Comment by Tirokk** [comment]
@mogge I had the problem on macOS Safari.
Where you hat the problem @appinteractive ?

**Comment by appinteractive** [comment]
I definitely had it on iOS Safari (iPad) and I think also on MacOS Firefox. It's definitely broken HTML/CSS as the Login looks good, the signup not. 

As a note: I opened the signup directly from a link (human-connection.org). This may behave a bit differently from when you click from the login. Might be a SSR issue or what ever. I still suggest to use tailwind.css but 🤷‍♂️

Happy fixing.

**Comment by Tirokk** [comment]
Hello @arifszn ,

I cared for your invitation to our repository as volunteer via an e-mail invitation you can accept.
After you accept, please clone this repo (don’t fork) **push your feature branch directly to this repo and create a PR using master** as the base branch.

I assigned you to this issue …

Our conversation runs over our discord channels:
http://hc.world/discord
Another possibility to get to there:
https://discord.com/invite/DFSjPaX

On Discord we have kind of every day a Daily Standup at UTC 09:30 am (CEST 11:30 am) in the Conference Room.

PS: I and we will be not available till Monday.
