### ISSUE TITLE
🚀 [Feature] Emotion Reactions on Posts

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#384]
### Emotion Reactions on Posts
![image](https://user-images.githubusercontent.com/1238238/55489564-743cb580-5632-11e9-85e3-7fbb3f805391.png)

- [ ] Emotions
- [ ] Image active + inactive @appinteractive can you provide the images?
- [ ] ~Percentage~ Absolute values by Userreaction distribution
- [ ] User Interaction (click/click again -> change)

> HC users wish better filter possibilities in order to suppress "annoying" user and usercontent from their personal Newsfeed. Extending the range of emojis from 5-10 is a good and easy way to create more comfort.

Emotions:
- Funny
- Happy
- Surprised
- Cry
- Angry
- Love (heart)
- Disconnected (broken heart)
- fear (bibbernd)
- questioning (questioning emoji)
- resignated (hand touching face)
- help! (siren on head feat. Minion :-D)  

Note: Once selected deselection is not possible

### Userstory
```
As a User
  I`d like posts to be tagged with emotions
  in order to be able to filter them by such
```

### Design & Layout - Alpha

No User Selection:
![image](https://user-images.githubusercontent.com/1238238/55489575-7a329680-5632-11e9-93ce-7c2ec24280ba.png)

With User Selection:
![image](https://user-images.githubusercontent.com/1238238/55489634-933b4780-5632-11e9-8f8a-0819d9204276.png)

### Design & Layout - Nitro
missing

**Comment by DennisHack** [comment]
@ulfgebhardt 

group emotions:

POSITIVE
- Funny
- Happy
- Love (heart)

OTHER
- Surprised
- questioning (questioning emoji)

NEGATIVE
- Cry
- Angry
- fear (bibbernd)
- help! (siren on head feat. Minion :-D)
- resignated (hand touching face)
- Disconnected (broken heart)

Note: Once selected deselection is not possible WARUM?
