### ISSUE TITLE
Does Any One Can access the demo users mentioned in the readme ? 💬 [Question]

### ISSUE THREAD

**Issue by mohammad0omar** [Human-Connection/Human-Connection#3866]
I am trying to see the demos in this [link](https://develop.human-connection.org/login)

email | password | role
user@example.org | 1234 | user
moderator@example.org | 1234 | moderator
admin@example.org | 1234 | admin

Is there a solution so I can try?

**Comment by Tirokk** [comment]
Probably all demo users are delete by somebody.

We have to re-deploy the develop network @mohammad0omar .
Sorry for that!
We have a problem with automatic deployment at the moment. I hope to fix this tomorrow.

Thanks for you hint! 🤗👍🏼🍀

**Comment by Tirokk** [comment]
So @mohammad0omar the deployment problem ist solved and I renewed the database.

**Comment by mohammad0omar** [comment]
Why the demo is not inside a sandbox?

**Comment by Tirokk** [comment]
We had no time to care for this, til now.
And not all functions should be disabled in the demo.
I guess it would be nice as well if the database would be refreshed every day. @mohammad0omar

**Comment by Tirokk** [comment]
Solved

**Comment by mohammad0omar** [comment]
Thank You, Sir
