### ISSUE TITLE
Consider to switch from yarn to npm

### ISSUE THREAD

**Issue by Mastercuber** [Human-Connection/Human-Connection#39]
Maybe this [blog post](https://blog.risingstack.com/yarn-vs-npm-node-js-package-managers/) is interessting related to the topic, that yarn is just pointing to the standard npm registry.

**Comment by appinteractive** [comment]
Yeah but ist way faster then npm. That’s the whole point of using it, and the better console output.

**Comment by mimicc83** [comment]
but it's facebook and collecting data like everything facebook produces. I would rather not trust facebook.

**Comment by appinteractive** [comment]
Our „package statistic“ is on GitHub anyway and we are tracked by Microsoft through GitHub and we have a hardware Backdoors inside all 86x and ARM chips through the successor of the trusted computing platform. 

But I get your point and agree to share less data where possible even if I thing that FB don’t get any sensitive information at all through yarn. 
Do you have any information on that? Traced the connection maybe? Would interest me what they get. 

And I heard that npm seams to have grown up a bit.

**Comment by appinteractive** [comment]
And by the way, please don’t get me wrong, don’t want to offend any one, just needed to write it from my soul 😬😅
