### ISSUE TITLE
🚀 [Feature] UserSettings - YourData - Email

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#407]
### UserSettings - YourData - Email
![image](https://user-images.githubusercontent.com/1238238/55570461-c7326d80-5703-11e9-8b29-44917c9baa21.png)

- [ ] Display EMail
- [ ] (optional) Change EMail

(optional)
When I visit https://alpha.human-connection.org/auth/settings I want to change my email address, just as I can change my name already.

### User Story
```
As a user, I would like to change my login email address. E.g. to change my email provider, because I lost access to my former email address, etc.
```

### Design & Layout - Alpha

![image](https://user-images.githubusercontent.com/1238238/55570461-c7326d80-5703-11e9-8b29-44917c9baa21.png)

![image](https://user-images.githubusercontent.com/1238238/55572657-5ccffc00-5708-11e9-9971-04bb192a83fc.png)

### Design & Layout - Nitro

Not implemented:
![image](https://user-images.githubusercontent.com/1238238/55570589-01037400-5704-11e9-8f08-22104fb3b714.png)

### Additional Context
@appinteractive notes:
```
Keep in mind that we need to validate that address by double opt in again!
```

**Comment by mattwr18** [comment]
this was closed by https://github.com/Human-Connection/Human-Connection/pull/1711
