### ISSUE TITLE
[Bug] Don't expose private RSA key

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#411]
## 🐛 Bugreport

It should be not possible to query for a private key of a user.

### Expected behavior

If there is a query for the privat key of a user "******" should be returned.

### Additional context
Introduced by @roschaefer .
Related to PR #406 .
WIP by @Tirokk .

**Comment by ulfgebhardt** [comment]
closed via https://github.com/Human-Connection/Human-Connection/pull/406
