### ISSUE TITLE
🚀 [Feature] Administration - Users

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#419]
### Administration - Users
![image](https://user-images.githubusercontent.com/1238238/55622722-4a55d100-57a1-11e9-8a03-209b78252f7e.png)

- [x] Search
- [x] Name + Picture + Profile Link
- [ ] Verified #1183
- [ ] Legal Accepted
- [ ] Last Active
- [ ] Language
- [x] Badges #1183
- [x] Role #1183
- [x] Pagination
- [x] Remove User https://github.com/Human-Connection/Human-Connection/issues/17

### Design & Layout - Alpha

![image](https://user-images.githubusercontent.com/1238238/55622728-4c1f9480-57a1-11e9-9dfc-fc98fa194c95.png)

### Design & Layout - Nitro

![image](https://user-images.githubusercontent.com/1238238/55622617-f9de7380-57a0-11e9-8395-bdd8d63cf4bd.png)

**Comment by mattwr18** [comment]
we will create a new user story with the minimum requirements for our `Nitro` release
@roschaefer
