### ISSUE TITLE
Core-Feature: Post/Contribution builder

### ISSUE THREAD

**Issue by mimicc83** [Human-Connection/Human-Connection#42]
**Is your feature request related to a problem? Please describe.**
The current contribution editor is not flexible enough as sometimes I want to add a post and insert a "can do". At this moment the can do is a separate post type which requires me to create another post with the can do included.

**Describe the solution you'd like**
refactoring contributions form component and separating "can do" by adding it as a content element to the quill editor. This will allow more flexibility when creating posts.

**Additional context**
While this change is made I suggest to also change the contribution creation UI for more creative "space" like drafted in the image below.

![posts-draft](https://user-images.githubusercontent.com/5682197/46213805-d2ae7180-c339-11e8-807d-eb3ac02317ee.png)

**Comment by mimicc83** [comment]
please ignore the footer bug seen in the screenshot, this is related to my html draft editing!

**Comment by mimicc83** [comment]
The draft causes some issues on mobile, so as alternate solution it would be good to just have the content box as growing element. (adjust height depending on it's content)

**Comment by appinteractive** [comment]
Its already adjusting the size. 😊 @sabine give us some creative ui 😁

**Comment by roschaefer** [comment]
This issue is relevant to the legacy web-app which we're not going to develop any further. I go ahead and close this, feel free to reopen if you disagree.
