### ISSUE TITLE
🚀 [Feature] Administration - Pages

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#421]
### Administration - Pages
![image](https://user-images.githubusercontent.com/1238238/55622968-f1d30380-57a1-11e9-8fc0-70a9e7d418d0.png)

- [ ] Not able to delete Flag
- [ ] Title (link to editor)
- [ ] Slug (link to page)
- [ ] Type
- [ ] Active Slider
- [ ] Add Button
### Userstory

```gherkin
Feature: Administration - Pages
  As an administrator
  I need to have different web pages for imprint, privacy statement, code of conduct and more
  In order to provide additional static content, inform the users and fulfill regulations by law.
```

### Design & Layout - Alpha

![image](https://user-images.githubusercontent.com/1238238/55622980-f7c8e480-57a1-11e9-85ec-b497b56b5658.png)
![image](https://user-images.githubusercontent.com/1238238/55622993-feeff280-57a1-11e9-9e94-1ecb33dcaae7.png)
![image](https://user-images.githubusercontent.com/1238238/55623000-02837980-57a2-11e9-99ae-e7ba8c4af9dd.png)

### Design & Layout - Nitro

![image](https://user-images.githubusercontent.com/1238238/55623034-13cc8600-57a2-11e9-8f25-6cb11a203feb.png)

**Comment by mattwr18** [comment]
closing in favor of static pages, which can be updated by developer's when needed
