### ISSUE TITLE
🚀 [Feature] Administration - System Notifications

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#422]
### Administration - System Notifications
![image](https://user-images.githubusercontent.com/1238238/55623240-abca6f80-57a2-11e9-839f-d0dfebdd3771.png)

- [ ] Title
- [ ] Type
- [ ] Some unexplained checkbox & lock @appinteractive 
- [ ] Language
- [ ] Active Slider
- [ ] Pagination
- [ ] Add Button
- [ ] (optional) This whole feature could be replaced by a "HC-Bot"

### Design & Layout - Alpha

![image](https://user-images.githubusercontent.com/1238238/55623242-ad943300-57a2-11e9-8197-ab3788ed8e01.png)

### Design & Layout - Nitro

![image](https://user-images.githubusercontent.com/1238238/55623251-b5ec6e00-57a2-11e9-894a-1117a7b83032.png)

**Comment by ogerly** [comment]
i have first created a simple frontend form. i am still revising some points.
![vorschlag](https://user-images.githubusercontent.com/1324583/60916367-75fbc200-a28e-11e9-91d8-9a064d2ff3b5.png)
![Bildschirmfoto vom 2019-07-06 13-19-37](https://user-images.githubusercontent.com/1324583/60916368-75fbc200-a28e-11e9-8402-fa8109102ebe.png)
