### ISSUE TITLE
🚀 [Feature] Administration - Categories

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#423]
### Administration - Categories
![image](https://user-images.githubusercontent.com/1238238/55623346-095ebc00-57a3-11e9-94ea-b6e2e871c9e0.png)

- [ ] Title + edit
- [ ] Identifier + edit
- [ ] Icon Css class + edit
- [X] Icon
- [ ] Delete Button
- [ ] Add Category Button
- [ ] Save Button

### Design & Layout - Alpha

![image](https://user-images.githubusercontent.com/1238238/55623346-095ebc00-57a3-11e9-94ea-b6e2e871c9e0.png)
![image](https://user-images.githubusercontent.com/1238238/55623357-0f549d00-57a3-11e9-9662-68134fb9a5f9.png)

### Design & Layout - Nitro

![image](https://user-images.githubusercontent.com/1238238/55623368-19769b80-57a3-11e9-9db5-3ed3d8201375.png)

**Comment by mattwr18** [comment]
Is this still a feature the `admins` want @datenbrei ??
Maybe a good issue for the open-source community?
We have been getting along ok without, so maybe no deadline?
