### ISSUE TITLE
🚀 [Feature] Administration - Settings

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#424]
### Administration - Settings
![image](https://user-images.githubusercontent.com/1238238/55623485-6e1a1680-57a3-11e9-8094-bd91607371a2.png)
- [ ] Invites slider
- [ ] Max Invites input
- [ ] badge limiter, add badge functionality
- [ ] Developer Mode @appinteractive pls explain
- [ ] Save Button

### Design & Layout - Alpha

![image](https://user-images.githubusercontent.com/1238238/55623485-6e1a1680-57a3-11e9-8094-bd91607371a2.png)

### Design & Layout - Nitro

![image](https://user-images.githubusercontent.com/1238238/55623491-75412480-57a3-11e9-9eaa-4b27120eb887.png)

**Comment by mattwr18** [comment]
closing as it's useless haha
