### ISSUE TITLE
💬 Hide all unfunctional content till its implemented

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#429]
## 💬 Question

Hide all unfunctional content till its implemented

Especally in the Admin-Section

**Comment by ulfgebhardt** [comment]
@roschaefer agree?

**Comment by roschaefer** [comment]
:woman_shrugging: for me it's OK. I had the idea we could show a message where to contribute, so people get an incentive to join development. But it's OK for me too, to not show unimplemented UI.
