### ISSUE TITLE
🚀 [Feature] Reenable Post once it has been disabled

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#432]
### Reenable Post once it has been disabled
![image](https://user-images.githubusercontent.com/1238238/55709617-05bc7680-59e9-11e9-9ac9-40a4a15a1de2.png)

Replace the `Disable Contribution` with `Enable Contribution` once its disabled

### Design & Layout

![image](https://user-images.githubusercontent.com/1238238/55709628-0b19c100-59e9-11e9-9835-63e5f233adb7.png)

**Comment by ogerly** [comment]
releasing and disabling a post now works and after 1500 ms a router.reload() will be done automatically
 https://app.zenhub.com/workspaces/nitro-5c0154ecc699f60fc92cf11f/issues/human-connection/human-connection/399

**Comment by roschaefer** [comment]
@ogerly can you link the PR here? Is it #525 ? @appinteractive has given you a code review on that. @ogerly could you remove the respective files?

**Comment by roschaefer** [comment]
Implemented in #736 

@ogerly if you write `close #432` or `fix #432` this issue gets closed once your PR is merged.
