### ISSUE TITLE
🚀 User interface also with a formal (respectful) language variant (translation of Sie/Du, vous/tu, вы/ты etc.)

### ISSUE THREAD

**Issue by infinite-dao** [Human-Connection/Human-Connection#495]
## :rocket: Feature
In German—and also in other languages like français or по-русски—it is a sign of courtesy and respect to communicate with each other in a formal language variant in the process of getting to know each other and become familiar to one another, e.g. if the German head of the Federal Chancellery would log in to Human Connection ;-) I would definitely choose the formal communication over the informal, you know. I know, in fact we all are human beings—no upper/lower classification treatment intended—but that’s the way people and language can signal each other in a respectful manner. That’s why I would like to have this kind of user interface translation.

### Is your feature request related to a problem? Please describe.
The problem arises especially when a user with formal language settings communicates with a user having informal language settings on how to signal both sides that one likes to be treated with  more respect so to say and the other is more general and uses perhaps more in slang in his communication which can offend the other.

### Describe the preferred solution and alternatives you've considered
To obtain the translation file itself is not a problem, because in lokalise.co one can add a standard language normally, but then modify the ISO-code and the label of the language, e.g. a 

- “de”  for “German” (expressing the informal language variant)
- “de-formal” for “German (formal)” the language admin in lokalise.co has to activate user defined settings for this very newly crated language variant and rename it accordingly

### Design & Layout

- language ISO-code plus “formal” affix uses the formal language variant, e.g. de-formal, ru-formal, fr-formal etc.
- the language fallback is always to the default language standard (e.g. de, ru, fr), which should always be the informal language variant
- signal in comments, versus, contact, chat etc.—all features that communicate—via an info box,  to a user who has informal language settings, that she or he is going to communicate to the other one who likes to communicate in formal language.

May be one can call that technically “respect mode” or “respectful language” or …

**Comment by ewanold** [comment]
Since this topic is important for a lot of non-central-european/non-northern-american folk I keep that issue open for the time when the team has caught up with the pressing and urgent issues of today ;-)

**Comment by ewanold** [comment]
Keep it open
