### ISSUE TITLE
Spendenbutton und Formular

### ISSUE THREAD

**Issue by SebastianStehle** [Human-Connection/Human-Connection#5]
Hi,

ich habe gerade was gespendet. Habe erstmal eine gefühlte Ewigkeit nach dem Spendenbutton gesucht. Das sieht eher wie eine Überschrift aus:

![image](https://user-images.githubusercontent.com/1236435/37874388-42e483b2-302e-11e8-9c6d-628c8b97456d.png)

Leider ist das Formular auch echt schlecht lesbar. Der "light" Text auf grau macht sich nicht gut und das helle grün hat einen sehr schlechten Kontrast.

![image](https://user-images.githubusercontent.com/1236435/37874384-31196d96-302e-11e8-9e16-5e257b5caf6f.png)

**Comment by mimicc83** [comment]
sorry das ist irgendwie untergegangen. Wird soonish angepasst.
