### ISSUE TITLE
🐛 Rapidly double clicking on `Comment` button causes two database writes

### ISSUE THREAD

**Issue by mattwr18** [Human-Connection/Human-Connection#542]
## :bug: Bugreport

At the moment, if you rapidly click on the `Comment` button, it is possible to create multiple comments with the same content.

Currently, in the `handleSubmit` method, the button is disabled and set to loading, but it is still possible to fire two events before the button is disabled and apollo is sending two requests.
![Screenshot at 2019-05-05 12:33:22](https://user-images.githubusercontent.com/26943915/57196288-02f26a00-6f32-11e9-9c9c-d95497deb35f.png)

### Steps to reproduce the behavior
1. visit `/`
2. click on a post
3. write a comment
4. click rapidly twice on the `Comment` button

### Expected behavior

There should be some way of handling this situation, if a user wants to comment the same thing twice, for whatever reason, they should need to type the same message/copy && paste it.

More often than not, this will happen by accident, and therefore we should have some protection against this.

have found this https://github.com/Akryum/vue-apollo/issues/185
 which suggests that adding `optimisticResponse` prevents two database writes https://github.com/Akryum/vue-apollo/issues/185#issuecomment-364696038

I've yet to successfully test this in favor of opening a new issue to explore options

### Version & Environment
 Type: []      
 - OS: []      
 - Browser: [] 
 - Version []  
 - Device: []

**Comment by appinteractive** [comment]
This has nothing to do with Apollo but with our state management. Just set a var (disabled or progress) on click and reset it on result/error.

**Comment by mattwr18** [comment]
As I stated :point_up: @appinteractive "Currently, in the handleSubmit method, the button is disabled and set to loading, but it is still possible to fire two events before the button is disabled and apollo is sending two requests."

**Comment by ulfgebhardt** [comment]
Can you link the coresponding code @mattwr18 - i will have a look

**Comment by mattwr18** [comment]
hey @ulfgebhardt... here is the bit of code that sets `this.disabled` to true, which disables the button until the mutation returns https://github.com/Human-Connection/Human-Connection/blob/master/webapp/components/comments/CommentForm/index.vue#L81

here is the `PR`, I put in to expose the bug
https://github.com/Human-Connection/Human-Connection/pull/561

**Comment by ulfgebhardt** [comment]
@mattwr18 the problem is here:
https://github.com/Human-Connection/Human-Connection/blob/master/webapp/components/comments/CommentForm/index.vue#L99

Look here for the solution: https://github.com/Human-Connection/Human-Connection/blob/master/webapp/components/ChangePassword.vue#L78

You have to put the `this.loading = false`into a finally block:
```
this.loading = true
try {
} catch (err) {
} finally {
  this.loading = false
}
```

**Comment by mattwr18** [comment]
I don't think this is a problem @ulfgebhardt, these are just two different ways of doing the same thing.
one is using async await, while the other is using promises

the `then()` callback is not reached unless and until the `mutation` resolves

**Comment by ulfgebhardt** [comment]
i agree - Just a thought - ignore it ;-)

**Comment by mattwr18** [comment]
no idea is a bad idea! I tried it out and pushed up the code... but same result, unfortunately....
how big of a bug is this do you'all think?

**Comment by mattwr18** [comment]
up to this point, this is not reproducible outside a dev environment... we have agreed to close this for now
