### ISSUE TITLE
🚀 Update Comment

### ISSUE THREAD

**Issue by mattwr18** [Human-Connection/Human-Connection#552]
## :rocket: Feature

**As** a user
**I should be able to** edit(update) my comment
**So that** I can correct anything about my comment I want

### Is your feature request related to a problem? Please describe.

At the moment, comments can only be created

**Comment by Tirokk** [comment]
I would suggest to not show the CommentForm for writing new Comments if one updates a Comment. @ALau2088 @mattwr18
