### ISSUE TITLE
💬 Add `yarn lint fix` to the build server

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#570]
## :speech_balloon: Question

Should we add `yarn lint --fix` before `yarn lint` to the build server?

## Reason

Because builds fail often by little lint errors, the server time and work waste may not be acceptable, @mattwr18 and I have discussed.

**Comment by ulfgebhardt** [comment]
closed in favor of https://github.com/Human-Connection/Human-Connection/issues/590 and https://github.com/Human-Connection/Human-Connection/issues/591

**Comment by ulfgebhardt** [comment]
closed in favor of https://github.com/Human-Connection/Human-Connection/issues/590 and https://github.com/Human-Connection/Human-Connection/issues/591
