### ISSUE TITLE
💬🚀 [Feature] Delete SocialMedia - Modal Dialog?

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#571]
## 💬:rocket: Feature we like to have?

As a User
I'd like to get asked before my social media gets deleted.
In order to manage my social media accounts.

### Is your feature request related to a problem? Please describe.

I would like to get asked by a modal dialog, if my SocialMedia should be deleted.

### Describe the preferred solution and alternatives you've considered

A modal dialog for deletion on `webapp/pages/settings/my-social-media.spec.js`.

### Additional context

Look at the Delete post PR #511 . Wait until it’s merged.
From there you can use a lot of code !!!

I separated this from issue #535 , because of the foreseen code usage.

**Comment by datenbrei** [comment]
@Tirokk I think this is some kind of minor improvement. Anyways, I'll take it into the Roadmap.

**Comment by Tirokk** [comment]
@datenbrei I am not sure if this is really necessary.
Because my own social media data I can always reconstruct hopefully.

The only thing is in my eyes not deleting it accidentally by an unwilling click without noticing for a reason.

**Comment by datenbrei** [comment]
Would it be possible to work out a generic js-only version that we could use in ANY delete button/action?

**Comment by Tirokk** [comment]
It is kind of already done with or even further to do with `ConfirmModal.vue`.
And @alina-beck is working on something like this as well.

**Comment by alina-beck** [comment]
Not really working on it yet and I haven't had a close look at the `ConfirmModal` but yes, ideally this modal would just receive a `text` to render and then return `true` on confirm and `false` on cancel. So it would be very easy to reuse!

I think we could improve our `Modals` in general (code- and reusability-wise) but I will have to get a little further with the styleguide migration before I can start working on it. :wink:
