### ISSUE TITLE
🚀 Refinement of SocialMedia Administration

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#581]
## :rocket: Feature

Several refinements of the administration of the users SocialMedia would be nice:
- [x] the `Add link` button should be inactive, if the URL is not appropriate
- [x] let the user be able to edit an existing SocialMedia
- [x] add a title (hint) to the edit and delete icon
- [x] the SocialMedia should not be doubled (Frontend + Backend)
Localisation:
- [x] EN: button `Add link` → `Add Link` ?

### Is your feature request related to a problem? Please describe.

No

### Describe the prefered solution and alternatives you've considered

No

### Design & Layout

No

### Additional context

No

**Comment by alina-beck** [comment]
@Tirokk You suggested to change `Add link` to `Add Link`, i.e. to capitalize first letters. I like it – but maybe that's just us German-speakers. :wink:

There are many other places in the English version of the app where only the first letter in a "sentence" is capitalized (e.g. `Social media`, `Your data`) so I guess we should either change them all or leave the button as is. I'd be up for both. What do you think?

**Comment by mattwr18** [comment]
This reminds me that I added `Delete Data` to the settings menu while all the rest of the links the second word is not capitalized. I think we should decide and stick with it

**Comment by roschaefer** [comment]
Keep it simple stupid I guess? I say, only first letter capitalized. Otherwise I never know if words like `and`, `or`, `the` get capitalized as well.

**Comment by mattwr18** [comment]
Ahhh, I thought @alina-beck used your line, haha.... I was coming here to say, "oh no, now we have two who use that line" :stuck_out_tongue_closed_eyes: 

That's cool with me, I'll put in a micro-PR to update the `Delete Data` then :smile_cat:

**Comment by Tirokk** [comment]
Capitalize only the first letter is okay with me. @alina-beck 
I like only to have one version and we make it that way than!
