### ISSUE TITLE
🐛 No Edit Field displayed in CommentForm

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#582]
## :bug: Bugreport

There is sometimes no edit field displayed in the CommentForm …

<img width="1401" alt="First - Comment Form has no Edit Field" src="https://user-images.githubusercontent.com/25344101/57438642-b31ee600-7244-11e9-9f27-dc883382b772.png">

If you refresh the page the edit field is displayed …

<img width="1377" alt="Refresh Page - Comment Form has Edit Field" src="https://user-images.githubusercontent.com/25344101/57438878-26c0f300-7245-11e9-83d0-282f1d0df017.png">

### Steps to reproduce the behavior
1. If you go to the profile of a user …
2. … and click on a post …
3. … and on this post scroll down to the bottom …
4. ... the CommentForm has no edit field

### Expected behavior

There should be an edit field displayed in the CommentForm.

### Version & Environment
 Type: Desktop      
 - OS: macOS      
 - Browser: Safari, FireFox

**Comment by mattwr18** [comment]
great @Tirokk, thanks for opening this issue... I had noticed it, @roschaefer as well, and I said I would open it, and then got busy and didn't do

**Comment by mattwr18** [comment]
how would we start to debug this issue @roschaefer @Tirokk @ulfgebhardt @tansaku?? 
I'm a bit lost on this... :disappointed:
