### ISSUE TITLE
🚀 [Feature][Tests] Console errors in testruns should always fail the test

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#589]
### Console errors in testruns should always fail the test

It happens that a test generates a console error but does not fail.
The default behaviour should be to fail the test (or build)

- [ ] Reproduce behaviour
- [ ] Decide how to fail (test or build)
- [ ] Technically possible?
- [ ] Is there a case where we need a console error to be raised in a test and is this mappable in the chosen scenario?

### Additional context

![image](https://user-images.githubusercontent.com/1238238/57493427-181a2080-72c5-11e9-81d1-b0b4c728d378.png)

Rev: https://travis-ci.com/Human-Connection/Human-Connection/builds/111197547

**Comment by roschaefer** [comment]
![yes](https://media.giphy.com/media/nFjDu1LjEADh6/giphy.gif)

Oh yes, I thought `vue-test-utils` would fail the test if there were any console errors. I'm surprised that it does not behave that way.

Here are the docs: https://vue-test-utils.vuejs.org/
