### ISSUE TITLE
🚀 [Feature] [Docs] Provide docs for githooks for yarn lint --fix on commit

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#591]
### Provide docs for githooks for yarn lint --fix on commit

Before committing `yarn lint --fix` should be called. Since this git hook needs to be setup by every developer themselfs this can only be provided by docs

- [ ] Test `yarn lint --fix` githook
- [ ] Document how to setup
- [ ] Are there more hooks which can be useful?

**Comment by mattwr18** [comment]
certainly still relevant as contributors need to run `yarn lint --fix` before pushing up every time...
even those who contribute daily forget some times and that uses build time, aka resources unnecessarily.
maybe someone from the open-source community is willing to research this and add a `how-to` to our docs?
