### ISSUE TITLE
BugReporter

### ISSUE THREAD

**Issue by ReggaePanda** [Human-Connection/Human-Connection#6]
Das Formular für die Bugreports funktioniert nicht

https://human-connection.org/alpha/#bugreport

<img width="1680" alt="bildschirmfoto 2018-04-12 um 11 51 06" src="https://user-images.githubusercontent.com/2183135/38670015-fc4ced04-3e47-11e8-965f-9bf52b7b2e63.png">

**Comment by sebako86** [comment]
Hey hey, danke für den report. Ich konnte das jetzt nicht reproduzieren. Welchen Browser hast Du verwendet?

**Comment by ReggaePanda** [comment]
safari
der scheint diese url abrufen zu wollen
https://human-connection.org/wp-json/contact-form-7/v1/contact-forms/14178/feedback

**Comment by sebako86** [comment]
strange, der Safari macht da wieder irgendwas völlig absurdes.

**Comment by Lulalaby** [comment]
Ist das noch aktiv?

**Comment by ReggaePanda** [comment]
hab es gerade nochmal getestet und jetzt funktioniert das Formular bei mir. also kann geclosed werden 🤩
