### ISSUE TITLE
Find registered users by email address to reach out and ask for a donation

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#60]
**Is your feature request related to a problem? Please describe.**
We have a couple of one-time donators who registered to https://alpha.human-connection.org/auth/login. We would like to ask them if they want to become a monthly donator.

**Describe the solution you'd like**
We have a list of email addresses of our one-time donators. We would like to send them mails, but only if they ever registered and know the app already. We need to filter this list of emails and exclude those who never registered. The approach is to write a script that takes the list of one-time donators, queries the database for registered users and outputs a list of one-time donators who already registered. The script would be copied via SCP to our production server and the output would be copied back.

**Describe alternatives you've considered**
We could also create a UI for bulk export of email addresses based on some filter criteria. But for security concerns, we never want to expose any endpoint to bulk export sensitive data, including email addresses.

**Additional context**
Here's the workflow:
![workflow bulk export](https://user-images.githubusercontent.com/2110676/47568411-56578000-d931-11e8-9015-72d5fad833a1.png)

Administrators would be required to copy the script and the input/output as well as to run the script.

**Comment by appinteractive** [comment]
We do not need any script for this as it would be easer to do it by hand in the database.

**Comment by arjustini** [comment]
first time trying to work on an open source project. is it okay if I try to help with this issue?
