### ISSUE TITLE
Get all email addresses of users with unclaimed registration codes

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#61]
**Is your feature request related to a problem? Please describe.**
We have a number of unclaimed registration codes. We want to re-contact the owners via mail to slowly increase our user base. We want a user increase because that might convert some donators and we want a slow increase to not overwhelm our moderation team.

**Describe the solution you'd like**
~A script should output the corresponding emails of all unclaimed registration codes into a CSV file. The script runs on the production server and has the same requirements as explained in #60.~

We need a query for our `mongo` client that outputs  a list of emails of all unclaimed registration codes. In order to execute the query you will need admin permissions on our production database.

**Describe alternatives you've considered**
We don't want a bulk export feature of all emails in our UI  for security reasons, see #60.

**Comment by arjustini** [comment]
first time trying to work on an open source project. do you mind if I try helping with this issue?

**Comment by Lulalaby** [comment]
Try yourself and create a pull request afterwards

**Comment by roschaefer** [comment]
@arjustini along with @appinteractive we decided not to create a script for that but a simple query in your `mongo` client. We will use this presumably for one time only so it was a slight overkill to open this issue.

Since you already told us you want to try it out, please write down the relevant query here as a comment.

I will update the issue description accordingly.

**Comment by arjustini** [comment]
@roschaefer no problem! just one question, is there a good place in the code to look at to get a good understanding of the hierarchy of the database? I've never worked with a mongodb before
