### ISSUE TITLE
🐛 Model for Contributions is not consistent

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#623]
### Model for Contributions is not consistent

The Model for `contributions` is not consistent and it is the question how we want to model it.

Currently we have "Posts" in the Database, but the Network should support different types of contributions at some point:

Contribution:
- Post
- CanDo
- Poll
- ...

How do we model this in Database?

Do we have a universal `contribution` entity with a type-property specifying which type it is?
Or do we have an entity for each type of contribution `Post`, `CanDo`, ...

@roschaefer Can you tell me how you plan to do this?

**Comment by roschaefer** [comment]
@ulfgebhardt I have no plans at all!

Most people understand what a "post" is. So I would probably go for that term, your opinion @ulfgebhardt ?

**Comment by mattwr18** [comment]
This has also tripped me up recently while working on the `Delete Account` ticket cause I have the tendency to want to call the variables something to do with `post` cause at the moment these are the only types of contributions, but there are attributes like `contributionsCount` in the `User` schema. 

Maybe we could have separate nodes for separate types of contributions, like the ones @ulfgebhardt mentioned, for example. Then, a `contributionsCount`, if we wanted a total, would give a sum of all, wheras would could have a `postsCount`, `canDoCount`, etc...
