### ISSUE TITLE
🚀 Automatic import of production data on deployments

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#641]
## :rocket: Feature
@ulfgebhardt and I discussed that it would be helpful to import and migrate the production data from our legacy application into the kubernetes cluster on a regular schedule, e.g. after deployments. 

### Is your feature request related to a problem? Please describe.
The problem is that we get informed too late in case we have performance issues or issues that are not noticeable on seed data.

### Describe the prefered solution and alternatives you've considered

A solution would be to change update [this script](https://github.com/Human-Connection/Human-Connection/blob/master/scripts/deploy.sh). We would not only update the images on kubernetes (aka trigger a rollout deployment) but we would run a [kubernetes job](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/) that would download the data with `mongoexport` , run the import and then terminate the pod in order to release the persistent volume claim of the database volume. We have two helper scripts `import_legacy_db` and `import_legacy_uploads` in the [maintenance worker container](https://github.com/Human-Connection/Human-Connection/tree/master/deployment/legacy-migration/maintenance-worker/binaries).

**Comment by mattwr18** [comment]
not absolutely necessary
