### ISSUE TITLE
🐛 [Bug] Hover effect on Userprofile Image to suggest upload

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#688]
### Hover effect on Userprofile Image to suggest upload

There should be an hover effect like in the Alpha in oder to show the user that he/she can upload own Images for the own Userprofile.

### Steps to reproduce the behavior
1. Go to own Userprofile
2. Hover over Avatar
3. No hint showing up for upload
4. ...
5. Profit

### Expected behavior

An Hover effect should be visible hinting the User to change his Profile image
![image](https://user-images.githubusercontent.com/1238238/58437399-17a5c600-80ca-11e9-9b35-7a9fcc19c524.png)

![image](https://user-images.githubusercontent.com/1238238/58437347-d2819400-80c9-11e9-8cc0-4cd073e0db98.png)

Note the border change on Hover (dashed) (optional)

**Comment by mattwr18** [comment]
Closed via https://github.com/Human-Connection/Human-Connection/pull/732
