### ISSUE TITLE
Infrastructure - Technical Groundwork

### ISSUE THREAD

**Issue by appinteractive** [Human-Connection/Human-Connection#69]
We need to specify best practices and write documentation for them before we start implementing large parts of the application

**Comment by roschaefer** [comment]
@appinteractive I don't know how to implement this issue. Maybe have a look at the suggestions [I gave to Simon](https://github.com/Human-Connection/Nitro-Web/issues/65#issuecomment-443689279).

**Comment by appinteractive** [comment]
@roschaefer Its not an issue but an epic with child issues. See zenhub for more info.

**Comment by roschaefer** [comment]
@appinteractive on Zenhub this epic is completed
