### ISSUE TITLE
🚀 [Feature] Migrate all available Data from Alpha to Nitro

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#692]
### Migrate all available Data from Alpha to Nitro

- [x] Modify import scripts to work with windows
- [x] Make a List of all available Data
- [x] Check off which Data is already transferred
- [ ] Transfere all Data remaining / List Todo's

**Comment by roschaefer** [comment]
* Invites cannot be imported at all
* We import candos later, because we don't know how to model the data before we implement the feature
