### ISSUE TITLE
🐛 [Bug]High Severity Security Vulnerability

### ISSUE THREAD

**Issue by mattwr18** [Human-Connection/Human-Connection#705]
## :bug: Bugreport

High Severity Security Vulnerability
![Screenshot at 2019-05-30 08:04:12](https://user-images.githubusercontent.com/26943915/58629022-a163b800-82b1-11e9-8d0e-554acbd39b75.png)

**Comment by mattwr18** [comment]
there has been a fix merged to `master` from axios, but not published yet
https://github.com/axios/axios/issues/2183

we are not using axios as a direct dependency, but rather as part of `@nuxtjs/axios`, so we cannot simply pull from master... there has also been an issue raised there https://github.com/nuxt-community/axios-module/issues/255

I guess we follow along until we can upgrade? @ulfgebhardt @Tirokk @roschaefer

**Comment by pi0** [comment]
https://github.com/nuxt-community/axios-module/releases/tag/v5.5.3

Please upgrade ASAP.

**Comment by mattwr18** [comment]
thanks a lot @pi0... great work!!! appreciate you letting me know... I'll merge in the changes now :smile_cat:
