### ISSUE TITLE
🐛 [Bug] Postcard content excerpt overflow

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#716]
### Postcard content excerpt overflow
![image](https://user-images.githubusercontent.com/1238238/58756293-0b6c9f00-84f6-11e9-9fd1-0acb5f077b53.png)

Content of postcards can overflow

### Expected behavior

Break words so it does not overflow

### Version & Environment
 Type: [Desktop]      
 - OS: [unknown]      
 - Browser: [unknown] 
 - Version [unknown]  

### Additional context

https://nitro-production.human-connection.org/post/5cebafec0a98fd001c2b88b7/sehr-gute-analyse-von-vera-lengsfeld

**Comment by aonomike** [comment]
Hi @ulfgebhardt how can one reproduce this issue in their dev environment? I have been able to reproduce it in staging but not able to on my dev environment. Please see below an image from staging when in mobile view 
![Screen Shot 2019-06-05 at 2.59.41 PM.png](https://images.zenhubusercontent.com/5c87d45b8382af59ca1b81bf/5003ea41-98f4-419b-90bb-3effa4b1f596)
I recreated a post in my local dev environment on mobile view with the same text as in the post above(in staging) in my local but every the post just displays three dots as below
![Screen Shot 2019-06-05 at 3.08.34 PM.png](https://images.zenhubusercontent.com/5c87d45b8382af59ca1b81bf/e4f5b190-732e-485b-bc4e-ea179e8e8368)
Is it the correct behavior when to see the three dots whenever a url is encountered in the posts? Kindly let me know if I make sense,
