### ISSUE TITLE
Setup database cleaner and factories

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#74]
```gherkin
Feature: Setup database cleaner and factories
  As a developer
  I want to bring the database into a desired state for each test
  In order to test the behaviour in predefined situations which are relevant for the test scenario
```

E.g. this [bug 49](https://github.com/Human-Connection/Nitro-Backend/issues/49) is only reproducible with an empty database. The current setup requires us to seed the database once and leave it as it is from there. With this setup we wouldn't be able to test against the above bug.

Instead we clean the database after each test and create the required data for each test scenario.

**Comment by appinteractive** [comment]
@roschaefer this is done already doesn`t it?
