### ISSUE TITLE
🚀 [Feature] Author (self) + last active in Create Post

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection/Human-Connection#760]
## :rocket: Feature

Who is the Author? 😎 Who I am. 🖖🏼🤔
And when I was last active?

- show the Avatar and name of the User above the Post title
- show the users last activity date-time underneath the users name

### Design & Layout

<img width="814" alt="Alpha - Create Post - Avatar, Name, Date-Time - Bildschirmfoto 2019-06-06 um 09 12 53" src="https://user-images.githubusercontent.com/25344101/59015465-557bba80-883f-11e9-87b3-c8ac90ca5a08.png">

### Additional context

It is already done in the PostCard on the User Profile, Post List. See here:

<img width="1098" alt="Nitro - User Profile, Post List, Post Card – Avatar, Name, Date-Time - Bildschirmfoto 2019-06-06 um 09 44 09" src="https://user-images.githubusercontent.com/25344101/59015743-f5394880-883f-11e9-8e5e-8f81115ec29d.png">

**Comment by mattwr18** [comment]
closed via https://github.com/Human-Connection/Human-Connection/pull/936
