### ISSUE TITLE
🐛 [Bug] Untranslated Texts in Post Page

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#764]
### [Bug] Untranslated Texts in Post Page

![image](https://user-images.githubusercontent.com/1238238/59045187-dbb7f100-887f-11e9-83ff-b8ff018d1523.png)

There is several Texts not translated correctly (we are not talking about switching language)

### Expected behavior

All Texts should be translated/translatable

**Comment by ogerly** [comment]
that I do ;) a small exercise for me
