### ISSUE TITLE
Beiträge werden nur in einer Reihe angezeigt

### ISSUE THREAD

**Issue by plipK** [Human-Connection/Human-Connection#8]
Ich sehe regelmäßig die einzelnen Beiträge nicht wie sonst in drei, sondern nur in einer Reihe. Außerdem werden oft beim nach unten Scrollen keine Beiträge mehr nachgeladen.

**Comment by appinteractive** [comment]
Sollte behoben sein, falls das Problem weiterhin besteht, gerne das issue wieder öffnen.

**Comment by Lulalaby** [comment]
@plipK immer noch?

**Comment by plipK** [comment]
Nein.
