### ISSUE TITLE
🐛 [Bug] Broken avatar urls on production

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#800]
## :bug: Bugreport
Apparently we add the prefix `/api` twice to each url of an avatar. E.g.
```
https://nitro-production.human-connection.org/api/api/uploads/e5aa3db1315b61c7ef94660c300094dd358177d3ba42711281b46ccbb5f7c2db.jpeg
```
Is obviously wrong because it's pointing to `https://nitro-production.human-connection.org/api/api/uploads/` when it should point to `https://nitro-production.human-connection.org/api/uploads/`

The effect of this bug is that no avatar is visible on [https://nitro-production.human-connection.org/](https://nitro-production.human-connection.org/) right now:

![Screenshot - 2019-06-12T112704 069](https://user-images.githubusercontent.com/2110676/59339703-f4535b80-8d04-11e9-96be-89f382c86511.png)

### Steps to reproduce the behavior
1. Visit https://nitro-production.human-connection.org/
2. Login with your account
3. Open javascript console and see all the 404 errors

### Expected behavior
Avatars should be visible.

**Comment by ogerly** [comment]
actually everywhere where the user picture appears
