### ISSUE TITLE
🐛 [Bug] HcContributionForm submit is not disabled by default

### ISSUE THREAD

**Issue by mattwr18** [Human-Connection/Human-Connection#806]
## :bug: Bugreport

This means a user can try to submit the form without a title, for example.
It will fail the frontend validations, but it would still be better to make it disabled by default so that the button is disabled and only after meeting the validations would the button be disabled.

![ezgif com-video-to-gif (11)](https://user-images.githubusercontent.com/1324583/59379980-5be6c680-8d58-11e9-9a8c-892bac8430f8.gif)

**Comment by Tirokk** [comment]
Solved by #977
