### ISSUE TITLE
🐛 [Bug] Build server always fails on forks of our repo

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/Human-Connection#808]
## :bug: Bugreport
Our build server depends on an encrypted environment variable. Encrypted variables are never exposed to forks for security.

The problem is that any open source contributor who forks the repo in order to send us PRs will always have a failing build, no matter what changes he/she made.

### Steps to reproduce the behavior
1. Fork the repo
2. Commit & Push
3. See the build server failing on that commit

### Expected behavior
Build server should pass.

**Comment by roschaefer** [comment]
@ulfgebhardt I think `codecov` depends on encrypted variables, is that correct?

**Comment by ulfgebhardt** [comment]
@roschaefer no it does not
