### ISSUE TITLE
🚀 [Feature] Automatic loading of more Content when scroll hits load more

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#845]
### Automatic loading of more Content when scroll hits load more

The Frontpage should load more content automatically once the `load more` option becomes visible.

The same applies to the profile page.

> wird das noch umgestellt auf automatisches Nachladen der Beiträge? Wäre aus meiner Sicht deutlich smarter, als wenn man ständig da drauf klicken muss. 

### Design & Layout

![image](https://user-images.githubusercontent.com/1238238/59601859-a0ca7e80-9105-11e9-94e2-97713b512c3f.png)

![image](https://user-images.githubusercontent.com/1238238/59601932-cf485980-9105-11e9-8e44-311a3179ae7a.png)

**Comment by Tirokk** [comment]
Hey @MoldaB ,

thanks a lot for your wonderful and important contribution. 🚀💫🚀

There are still build errors with the Cypress tests and we need a moment to have time to get working on them …

**Comment by Tirokk** [comment]
We would be very happy if you could apply this to the users profile page as well @MoldaB .

**Comment by roschaefer** [comment]
closed by #1176
