### ISSUE TITLE
🚀 [Feature] Text description for Filter Bubble

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#849]
## :rocket: Feature

I would better like to see a text description for the filter bubble.

### Design & Layout

![screen](https://user-images.githubusercontent.com/13457963/59631238-a052d780-9147-11e9-8025-8b2b9010e50f.png)

### Additional context

Actually I can switch between all posts and the posts of my friends with a little symbol.

**Comment by ogerly** [comment]
FIX:  https://github.com/Human-Connection/Human-Connection/pull/856
