### ISSUE TITLE
🐛 [Bug] GraphQl error when saving the residence in the profile settings

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#850]
## :bug: Bugreport

When I choose "Augsburg" or another city for to set it as my residence, I get an error, when I try to save it.

![ezgif com-video-to-gif (14)](https://user-images.githubusercontent.com/1324583/59633873-c4b1b280-914d-11e9-9cfc-0dffaf638537.gif)

### Steps to reproduce the behavior
1. Got to my Settings
2. Choose a City
3. Press save
4. see an Error "locationName is invalid"

### Expected behavior

The saving should work without error

### Version & Environment
 Type: [Desktop]      
 - OS: [Linux]      
 - Browser: [Firefox] 
 - Version [60+]  
 - Device: [Notebook]

**Comment by datenbrei** [comment]
@ogerly , your video shows, that the feedback message is green but the city is not saved. On the Nitro staging I see that I write a city, than I get matches displayed in a dropdown list, then when I save I get an Error.
---
Dein VIdeo zeigt, dass die Rückmeldung grün ist, die Stadt aber nicht gespeichert ist. Auf der Nitro-Instanz sehe ich, dass ich eine Stadt schreibe, dann bekomme ich Treffer in einer Dropdown-Liste angezeigt, dann bekomme ich beim Speichern einen Fehler.

**Comment by ogerly** [comment]
I've noticed something else. 
if i enter a city in the nitro and select a city and save it. then i get an error message. if i click F5 and reload the page hard the city is saved. the error message is incorrect. 

![ezgif com-add-text (1)](https://user-images.githubusercontent.com/1324583/59743683-13a43880-9271-11e9-9589-212346dc1aff.gif)

**Comment by ogerly** [comment]
> https://api.mapbox.com/geocoding/v5/mapbox.places/Berlin,Deutschland.json?access_token=pk.eyJ1IjoiaHVtYW4tY29ubmVjdGlvbiIsImEiOiJjajl0cnBubGoweTVlM3VwZ2lzNTNud3ZtIn0.KZ8KK9l70omjXbEkkbHGsQ&types=region,place,country&language=de

this is the result ... i've only put a part of it here as an example. 

there is a point of relevance. 1 = absolute relevance
< 1 = less relevant. 
> {
  "type": "FeatureCollection",
  "query": [
    "berlin",
    "deutschland"
  ],
  "features": [
    {
      "id": "place.14880313158564380",
      "type": "Feature",
      "place_type": [
        "region",
        "place"
      ],
      "relevance": 1,
      "properties": {
        "short_code": "DE-BE",
        "wikidata": "Q64"
      },
      "text_de": "Berlin",
      "language_de": "de",
      "place_name_de": "Berlin, Deutschland",
      "text": "Berlin",
      "language": "de",
      "place_name": "Berlin, Deutschland",
      "bbox": [
        13.088333,
        52.338242,
        13.760469,
        52.674917
      ],
      "center": [
        13.38333,
        52.51667
      ],
      "geometry": {
        "type": "Point",
        "coordinates": [
          13.38333,
          52.51667
        ]
      },
      "context": [
        {
          "id": "country.10743216036480410",
          "short_code": "de",
          "wikidata": "Q183",
          "text_de": "Deutschland",
          "language_de": "de",
          "text": "Deutschland",
          "language": "de"
        }
      ]
    },
    {
      "id": "place.4724776899227450",
      "type": "Feature",
      "place_type": [
        "place"
      ],
      "relevance": 0.9583333333333333,
      "properties": {
        "wikidata": "Q690219"
      },
      "text_de": "Perlin",
      "language_de": "de",
      "place_name_de": "Perlin, Mecklenburg-Vorpommern, Deutschland",
      "text": "Perlin",
      "language": "de",
      "place_name": "Perlin, Mecklenburg-Vorpommern, Deutschland",
      "bbox": [
        11.140978,
        53.566887,
        11.206269,
        53.610012
      ],
      "center": [
        11.16667,
        53.56667
      ],
      "geometry": {
        "type": "Point",
        "coordinates": [
          11.16667,
          53.56667
        ]
      },
      "context": [
        {
          "id": "region.10596494575582460",
          "short_code": "DE-MV",
          "wikidata": "Q1196",
          "text_de": "Mecklenburg-Vorpommern",
          "language_de": "de",
          "text": "Mecklenburg-Vorpommern",
          "language": "de"
        },
        {
          "id": "country.10743216036480410",
          "short_code": "de",
          "wikidata": "Q183",
          "text_de": "Deutschland",
          "language_de": "de",
          "text": "Deutschland",
          "language": "de"
        }
      ]
    },
    {
      "id": "country.10743216036480410",
      "type": "Feature",
      "place_type": [
        "country"
      ],
      "relevance": 0.5,
      "properties": {
        "short_code": "de",
        "wikidata": "Q183"
      },
      "text_de": "Deutschland",
      "language_de": "de",
      "place_name_de": "Deutschland",
      "text": "Deutschland",
      "language": "de",
      "place_name": "Deutschland",
      "bbox": [
        5.866003,
        47.270461,
        15.041428,
        55.0845576
      ],
      "center": [
        10,
        51
      ],
      "geometry": {
        "type": "Point",
        "coordinates": [
          10,
          51
        ]
      }
    },
    {
      "id": "place.15095411613564380",
      "type": "Feature",
      "place_type": [
        "place"
      ],
      "relevance": 0.5,
      "properties": {
        "wikidata": "Q614184"
      },
      "text_de": "Berlin",
      "language_de": "de",
      "place_name_de": "Berlin, Maryland, Vereinigte Staaten",
      "text": "Berlin",
      "language": "de",
      "place_name": "Berlin, Maryland, Vereinigte Staaten",
      "bbox": [
        -75.3649910169188,
        38.1913376057363,
        -75.0929459881765,
        38.4095040154251
      ],
      "center": [
        -75.2177,
        38.3226
      ],
      "geometry": {
        "type": "Point",
        "coordinates": [
          -75.2177,
          38.3226
        ]
      },
      "context": [
        {
          "id": "region.17411009488772660",
          "short_code": "US-MD",
          "wikidata": "Q1391",
          "text_de": "Maryland",
          "language_de": "de",
          "text": "Maryland",
          "language": "de"
        },
        {
          "id": "country.9053006287256050",
          "short_code": "us",
          "wikidata": "Q30",
          "text_de": "Vereinigte Staaten",
          "language_de": "de",
          "text": "Vereinigte Staaten",
          "language": "de"
        }
      ]
    },
    {
      "id": "place.16922023226564380",
      "type": "Feature",
      "place_type": [
        "place"
      ],
      "relevance": 0.5,
      "properties": {
        "wikidata": "Q1086827"
      },
      "text_de": "Berlin",
      "language_de": "de",
      "place_name_de": "Berlin, New Jersey, Vereinigte Staaten",
      "text": "Berlin",
      "language": "de",
      "place_name": "Berlin, New Jersey, Vereinigte Staaten",
      "bbox": [
        -74.9845524573365,
        39.7103732515883,
        -74.8813645395855,
        39.8091770007344
      ],
      "center": [
        -74.9291,

**Comment by ogerly** [comment]
## Using Axios to Consume APIs 
https://vuejs.org/v2/cookbook/using-axios-to-consume-apis.html
