### ISSUE TITLE
🐛 [Bug] Tripple / Duplicate Tags on Production

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#857]
### Tripple / Duplicate Tags on Production

![image](https://user-images.githubusercontent.com/1238238/59675786-50ffbc00-91c6-11e9-9ee4-1db027db78a5.png)

The Production Server contains the same Tags twice or more.
It is to be researched if that is due to double import or a error in the import script.

After checking the current production this cannot be reproduced. This issue is to check wether there are duplicate tags or not and wether we can prevent this from happening

### Expected behavior

No duplicate Tags ever (limitations of Neo4J - only the enterprise edition can ensure uniqueness)

### Additional context

https://nitro-production.human-connection.org/post/5ceb15900a98fd001c2b7f2a/doppelspalt-quantenphysik-quantenmechanik

**Comment by Tirokk** [comment]
I proved the production and the error on the post above is not there anymore. ;-))
