### ISSUE TITLE
🐛 [Bug] Content Excerpt removes Linebreaks without replacing them with Spaces

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#858]
### Content Excerpt removes Linebreaks without replacing them with Spaces

![image](https://user-images.githubusercontent.com/1238238/59676409-ce77fc00-91c7-11e9-9266-b7cdbb88fc4e.png)

![image](https://user-images.githubusercontent.com/1238238/59676436-dafc5480-91c7-11e9-9fea-fbdcf85441ce.png)

![image](https://user-images.githubusercontent.com/1238238/59676474-f0717e80-91c7-11e9-8665-cd017173896b.png)

Is is to check wether the generated excerpt in alpha has this Problem and we cannot correct it easily or if this is a Problem on nitro side.

### Expected behavior

Converting linebreaks is ok - just make sure to insert at least one space for it

### Additional context

https://nitro-production.human-connection.org/profile/5ab6a050896325000a59e514/wolfgang-huss

**Comment by Tirokk** [comment]
The Problem is solved on production.
I tried out …

**Comment by Tirokk** [comment]
Ups. Didn’t clicked on close …
