### ISSUE TITLE
💬 [Question] Fixate Profile side menus when scrolling?

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#859]
### Fixate Profile side menus when scrolling?

![image](https://user-images.githubusercontent.com/1238238/59676800-a6d56380-91c8-11e9-9b3a-b9541202b27d.png)

It is to clearify if we make parts of the Profile sticky, like the Userprofile picture when scrolling through posts.

How should it behave if you have alot of followers and following?

**Comment by ogerly** [comment]
@ulfgebhardt  i would suggest a fixed size for the page menu fields. if there is more information in it then unfold the element. or just jump and load to the overview of my friends and followers.
