### ISSUE TITLE
Setup Nitro Staging with Kubernetes

### ISSUE THREAD

**Issue by appinteractive** [Human-Connection/Human-Connection#87]
We need a Staging environment so users and devs can test new features in a near production environment.

**Comment by roschaefer** [comment]
Is the deployment code already checked in? We could set up our pipeline.

**Comment by appinteractive** [comment]
No I need to clean it up before that. Will follow this week. What do you mean with setting up the pipeline? What is the goal?

**Comment by roschaefer** [comment]
Setting up the pipeline means to add
```
kubectl create -f something.yml
```
in [deploy.sh](https://github.com/Human-Connection/Nitro-Web/blob/master/scripts/deploy.sh#L3)

**Comment by appinteractive** [comment]
I can’t imagine that this would be the workflow as it’s already deployed!? Do you have a reference for that to be the correct way? Can’t find anything right now.

**Comment by roschaefer** [comment]
Here's one reference: https://kubernetes.io/docs/reference/kubectl/cheatsheet/#creating-objects

What do you mean by "it's already deployed"? Do the images get updated each time we push to dockerhub? That's exactly how I don't want it to be. Instead I want to trigger the deployment *from the build server*. I do not want a tool like rancher to manage the deployment. Rancher is for convenience.

**Comment by roschaefer** [comment]
The "create" in `kubectl create` does not really relate to creating clusters or pods, but a deployment. That deployment is just a desired state and can be anything. I even used that command to update the permissions of a user. That's at least how far I understood kubernetes.

So, I guess it should also be possible to update the images of a cluster.

**Comment by roschaefer** [comment]
Ok, apparently I'm wrong, see here: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#updating-a-deployment

You can edit and start a rollout with other commands. But those commands should be added to the deploy script.

**Comment by roschaefer** [comment]
This blog post might help: https://nebo.blog/2017/07/31/travis-ci-as-continuous-delivery-pipeline-to-your-kubernetes-cluster/
