### ISSUE TITLE
🚀 [Feature] Mobile Responsive Menu/Navbar

### ISSUE THREAD

**Issue by mattwr18** [Human-Connection/Human-Connection#907]
## :rocket: Feature

As a site owner
I would like to have a mobile responsive design
So that I can attract a larger base of users

**Comment by appinteractive** [comment]
Shouldn’t it be phrased from the user perspective? 😬

**Comment by mattwr18** [comment]
Good point @appinteractive

**Comment by ogerly** [comment]
here is the ur issue: https://github.com/visualjerk/vue-cion-design-system/issues/14

**Comment by appinteractive** [comment]
@ogerly, we will need to implement it ourself I think. At least there is a big merge ahead of us if we want to use the latest styleguide from Jörg which used now css variables instead of scss vars.

**Comment by ogerly** [comment]
https://github.com/Human-Connection/Human-Connection/pull/933
