### ISSUE TITLE
🐛 [Bug] See PDF

### ISSUE THREAD

**Issue by Usus08** [Human-Connection/Human-Connection#946]
### Steps to reproduce the behavior
1.
2.
3.
4. ...
5. Profit

### Version & Environment
 Type: []      
 - OS: []      
 - Browser: [] 
 - Version []  
 - Device: []

**Comment by Usus08** [comment]
[nitro_test.pdf](https://github.com/Human-Connection/Human-Connection/files/3347253/nitro_test.pdf)
best wishes

**Comment by datenbrei** [comment]
All Bugs in this report are fixed so my proposel would be to close this?

**Comment by Tirokk** [comment]
Thanks @Usus08 for all your hints. 👍🏼🙏🏼
I proved and it seems that all the errors you pointed out are solved.
