### ISSUE TITLE
🐛 [Bug] thumbnail for the contributions must get a maximum height.

### ISSUE THREAD

**Issue by ogerly** [Human-Connection/Human-Connection#961]
## :bug: Bugreport
 if I load big pictures then he cuts out a piece. but in the overview it cuts the grid layout

![Bildschirmfoto vom 2019-07-03 15-01-30](https://user-images.githubusercontent.com/1324583/60593653-851cd480-9da3-11e9-989e-c908785679b8.png)

### Steps to reproduce the behavior
1. write a post with an oversized picture 
take what you find on the appendix for testing. 

2. after saving back to the overview. the grid will be destroyed.

## Example Image
![FireShot Capture 153 - Human Connection - Human Connection - localhost](https://user-images.githubusercontent.com/1324583/60592736-8baa4c80-9da1-11e9-914c-10139754053b.png)

### Expected behavior
The thumbnail of the posts must have a maximum height.

### Additional context
the whole image will be saved. and the section are only coordinates. when reloading the image these coordinates will be used again. but the whole image will be loaded in the background. 
this destroys the grid. a maximum size has to be specified or a real image with the selected section has to be stored. 
two ways ... i would prefer the second one

**Comment by ogerly** [comment]
@mattwr18 ?

**Comment by mattwr18** [comment]
yes?

**Comment by ogerly** [comment]
close: is merged
