### ISSUE TITLE
🚀 [Feature] Info Message

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/Human-Connection#962]
## :rocket: Feature

~~~gherkin
Feature: As a network admin 
I'd like to show up a good visible message on top of the main cockpit 
in order to inform network users about important news 
and upcoming downtimes or service restrictions.

Scenario: An informal message is shown
Given that a User has logged in to the network
When he enters the main cockpit
Then he can see the informal message on top of the page
~~~

### Design & Layout

![feature-info-message](https://user-images.githubusercontent.com/13457963/60595029-7edc2780-9da6-11e9-9e7a-ed9794b1345c.png)

### Additional context

Eventually the info message could be implemented as a sticky and highlighted post.

**Comment by roschaefer** [comment]
Great user story and screenshot! But could you give some more examples, please? I would like to know, why, when and for how long you need the info messages. Is it enough to send a notification to all users? Does it necessarily need to be visible in the newsfeed? Is it relevant only for some time?

**Comment by ogerly** [comment]
There should be the following possibilities for the admin. 

1. close a normal alert box
2. a modal box with confirmation
- a possibility to inform a single user or user groups ( with 1 & 2 )

Example: for 1. 
- Donation status, call for donation

Example: for 2. 
- Changes in the AGB

**Comment by ogerly** [comment]
proposition:

![vorschlag](https://user-images.githubusercontent.com/1324583/60705899-8ca9be00-9f08-11e9-86a1-dbcabc2badef.png)

**Comment by ogerly** [comment]
![Bildschirmfoto vom 2019-07-06 13-19-37](https://user-images.githubusercontent.com/1324583/60755500-edacc100-9ff0-11e9-89e3-695fa0c25fda.png)

**Comment by ogerly** [comment]
That's the original issue. https://github.com/Human-Connection/Human-Connection/issues/422

**Comment by datenbrei** [comment]
Let's keep things seperated, this issue is actually just for an info message, as described above. To answer @roschaefer  's questions:

why: is answered in the user story: in order to inform users about important news 
and upcoming downtimes or service restrictions.

when: each time an important information of users is needed. I'd propose to keep it simple in the beginning and not develop a whole CMS right now: Just an easy box to inform people, no need for keeping a history. One field or box, which can show up or be hidden, if empty.
how long: For the pure information let's take an on/off switch, means: switched intentionally, not with a timer.

Changes in terms of service (ToS) or code of conduct (CoC) should be part of the login process: Login should not be possible, if not agreed with. This is more some kind of part of a workflow. Since there is always just one ToS and one CoC active and valid, from my point of view we do not need a history here too. For the very beginning it could be done with a fixed text, but later we need at least a configurable message, so that we can give some details about what has changed.

Anyway, because of legal alignment we later need some kind of protocol to track, what the last ToS and CoS the specific user has agreed to.
