### ISSUE TITLE
🐛 [Bug] Required Software-Design Refactoring

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/Human-Connection#991]
#### The current implementation of the Software looks like this
![image](https://user-images.githubusercontent.com/1238238/60749010-308c7b80-9f94-11e9-9217-b54591a806cd.png)

The basis is Neo4J as Database, which is a wise choice for a Social Network, since there can be many types of Relations between all kinds of Nodes, which could not be modeled in a hierarchical database structure like mongoDB or any relational database.

For simplicity it was chosen to use `neo4j-graphql-js` as primary library to model the server. The concept of this library is to generate the Database-Graph from the GraphQL-API-Graph. But this bares a lot of problems which are the result of this principal.

While `neo4j-graphql-js` is suitable for none-complex matters or such, which do not rely on server-side business logic or its security, but it is certainly not suitable for our purpose which implies alot of security requirements aswell as several subsystems which are not coupled to the API, but require the Models of the Database schema.

Above all we require extensive Business-Logic to provide all functionality. `Neo4j-graphql-js` does not provide enough extensibility for a business logic layer. The business logic is split between custom resolvers and middlewares. This is not suitable for our endeavour. 

#### To illustrate the server-side-business-logic problem:

Since `neo4j-graphql-js` manages the generation of queries from the graphql-schema as single source of truth every field which is required to send to the Server needs to be in those models. But not every field needs to be in the Database. `neo4j-graphql-js` supports those fields wich are the result from a database-query like `commentsCount` or similar via the `@cypher` schema-directive. Other fields like the `UploadImage`-parameter which is required for the Image-Upload is not saved directly into the Database and requires middlewares and resolvers to filter them out or transform them.

This results in a business logic which is spread between middlewares and resolvers and cannot be maintained over a long period of time due to complexity and interdependencies.

#### To illustrate the security problem

An `User` in the Database requires an `email`. But we do not want to expose this EMail to someone who is not that User. But `neo4j-graphql-js` defines the schema as a single source of truth. Therefore the EMail must be included in the corresponding `User`-Model which can be requested by anyone already logged in. He then can include the `email` field in his query to retrieve the corresponding email address. To solve this we use middlewares to filter out sensitive Data on the way out towards the Frontend. This requires alot of work and is not foul-proof. Therefore it is not secure by design, but insecure by design and needs manual filtering to provide security. This is a major Security flaw.

#### To illustrate the none-API-subsystem problem

The GraphQL-Models are the single source of truth in the `neo4j-graphql-js`-library and are used to generate the Database Schema. But this generated Schema is not exposed and cannot be influenced. Therefore subsystems which are not directly coupled to the GraphQL-API require a second source of truth which redefines the Database-Model and make the whole Single-Source-Of-Truth-Theorem behind `neo4j-graphql-js` obsolete.

Such systems required by us are:
- Database Migrations
- Alpha-Data Database Import

#### How the implementation of the Software should look like
![image](https://user-images.githubusercontent.com/1238238/60749311-27051280-9f98-11e9-935e-da439cf0cb05.png)

This Model shows the separation of GraphQL-Schema and Database Schema which is required for our purposes. The conversion from API to Database and vice-versa is controlled by the business-logic-layer which is fully under our control. This tackles all the problems described above.

#### The downsides

This implies three major downsides:
- time required to make the transition and remove `neo4j-graphql-js`
- its is required to write all cypher-queries manually
- more then one query might be sent to the database unlike `neo4j-graphql-js` which generates only one

The first downside is obvious but devastating never the less due to given time limits

The second downside also comes with the major advantage of full control and in my opinion is not that much work as one would expect.

The third downside can be solved manually by writing more complex queries ourselfs. But this is not supported by current ORMs available like `neode` and breaks the concept of Database Models.

Therefore is is required to analyse if we can use an ORM like `neode` or if the library is too limited to fulfill our needs. @roschaefer 

### Additional context

From my experience it is wise to keep all iterations of Database modelling available in order to manipulate the Database in whatever state it currently is.

![image](https://user-images.githubusercontent.com/1238238/60749337-b9a5b180-9f98-11e9-91b4-7202ff3c72f2.png)

#### neode as OGM Layer

While it is quite temping to use `neode` as layer to define the database models it might come with some major downsides aswell.

While `neode` allows us to define a single-source-of-truth for the database models with all the required features like data-constraints it implies a major performance issue onto our software.

Assume the following:
`What are the Posts User A has written, how many shouts and what comments do those posts have?`
Can we use neode to find the answer to this using the corepsonding neode-models within one query?

In cypher that would be:
`MATCH (u:User)-[:WROTE]->(p:Post)<-[:COMMENTED]-(c:Comment) WITH p MATCH (p)<-[s:SHOUTED] RETURN u,p,c,COUNT(s)`

Assuming we can do that in `neode` we will certainly be limited to single-model-transactions when writing to the database in order to validate model restrictions. It might not be necessary (?) to do multi-model-transactions but certainly it is required to insert relations aswell.

So:
- Is `neode` qualified to fulfill all those requirements?
- Do we need multi-model-transaction?
- Can we insert relations with the model in `neode` within one query?
- Is it ok for us to have a multi-query write operation?
- Are models properly validated when inserting with `neode`?

We cannot implement HC with `neo4j-graphql-js` in the long run. But can we wait for the Alpha-to-Nitro migration to take place till we remove it?

The graphics can be edited in [draw.io](https://draw.io) with this file: [HC_Architecture.zip](https://github.com/Human-Connection/Human-Connection/files/3364337/HC_Architecture.zip) (might need to unpack first)

**Comment by roschaefer** [comment]
@ulfgebhardt what are schema migrations or what's the difference to migrations?

**Comment by ulfgebhardt** [comment]
@roschaefer Let me explain that:

While when using `neo4j-graphql-js` there is only graphql-schema which defines the api-schema and the database schema - when seperating those two systems there now are two sets of definitions. The Database-Schema and the GraphQl-Schema.

It is probably obvious why Database-Migrations are required in oder to transform the Database over time. This also applies to the API-Schema (namely GraphQL). The API-Schema changes over time and it will not be possible to maintain full backward compatibility with every version of the API. This is not a main priority for the project since the API on frontend and backend are fully under control of HC, but it certainly is a requirement for an App like DEMOCRACY since we cannot control when a User updates his App on the phone. While i have archived Database-Migrations providing all the previous Models in DEMOCRACY within the last release (mongoDB context), I did not yet for the graphql-API. This poses a major threat for the control of compatibility.

Schema-Migrations or better GraphQL-Schema-Migrations or in short API-Migrations would version each change of the API-Graph and would allow compatibility checks, force-update messages and alike.

As I said its not a major concern for HC, since front- and backend are under full control, but it is certainly a nice concept to version the API, determine compatibility and allow 3. party frontend implementations.

The major focus regarding migrations should be on the Database-Migrations since they are essential to change and adjust Database-Models to specific requirements like performance, mistakes made, simplifications and other necessary changes.

In a side-note: The proposed architecture of the software would allow "Database driven development" (not sure that's a real thing). What I mean is that the Database defines the structure of the software, logic and API since it is the major bottleneck for performance and accuracy (Model the Data most efficiently in oder to fulfill given purpose). Currently the API is the driving force which is unwise in my opinion.

**Comment by datenbrei** [comment]
I agree, that a versioned api has advantages, if we at one point in time have independent apps or such alike. Though, this would mean, that we'd need to adapt all available api versions to the single actual version of the database each time we change the database. For me this sounds to follow to the same efforts: Working database centric and adapt each time all api versions or change the api (and the underlying database) and therefore also all other api versions. 

Thinking about this I feel, that I'd best like to see the most actual api the one source of truth, ignoring, how the database is build under beneath. If the api will change some day, one way would be to let all apps check, if they are compatible with the most recent api version and ask for update, if not. From my point of view the api should be something more or less stable. Breaking the api should not be something done carelessly, there should be good reasons. 

Apart from that there may be a difference between breaking the api and extending the api. But from my non-technical point of view I can't say so much about this.
